<#
  Architect Hub -- patch 5: expanded test coverage
  Generated by Claude -- 2026-08-22

  Adds Senior Architect RBAC coverage to rbac.test.ts, plus new test
  files for rate-limit.ts, password-policy.ts, and the v2 file-picker
  guard. All 33 tests run and pass in a clean sandbox before this was
  sent to you (via `npx vitest run`).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-5.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 5 (test coverage)..." -ForegroundColor Cyan

# --- [MOD] src/lib/rbac.test.ts ---
$content = @'
import { describe, expect, it } from "vitest";
import type { Session } from "next-auth";
import {
  canAccessProject,
  canCreateProjects,
  canManageClients,
  canManageFirmSettings,
  canManageStaff,
  canReassignProjects,
  canRecordPayments,
  canViewPayments,
  isAdmin,
  isSeniorArchitect,
  projectAccessWhere,
  relatedProjectAccessWhere,
} from "./rbac";

function makeSession(
  role: "ADMIN" | "SENIOR_ARCHITECT" | "ARCHITECT",
  userId = "user-1"
): Session {
  return {
    user: { id: userId, role, email: "test@archub.io", name: "Test User" },
    expires: "2099-01-01T00:00:00.000Z",
  } as Session;
}

describe("rbac", () => {
  it("grants admins every admin-only capability", () => {
    const admin = makeSession("ADMIN");
    expect(isAdmin(admin)).toBe(true);
    expect(canManageStaff(admin)).toBe(true);
    expect(canManageClients(admin)).toBe(true);
    expect(canCreateProjects(admin)).toBe(true);
    expect(canReassignProjects(admin)).toBe(true);
    expect(canRecordPayments(admin)).toBe(true);
  });

  it("denies architects every admin-only capability", () => {
    const architect = makeSession("ARCHITECT");
    expect(isAdmin(architect)).toBe(false);
    expect(canManageStaff(architect)).toBe(false);
    expect(canManageClients(architect)).toBe(false);
    expect(canCreateProjects(architect)).toBe(false);
    expect(canReassignProjects(architect)).toBe(false);
    expect(canRecordPayments(architect)).toBe(false);
  });

  it("gives admins an unscoped project query (no WHERE restriction)", () => {
    const admin = makeSession("ADMIN");
    expect(projectAccessWhere(admin)).toEqual({});
  });

  it("scopes architects' project query to their own architect/supervisor assignments", () => {
    const architect = makeSession("ARCHITECT", "arch-42");
    expect(projectAccessWhere(architect)).toEqual({
      OR: [{ architectId: "arch-42" }, { supervisorId: "arch-42" }],
    });
  });

  it("lets an architect access a project only if assigned as architect or supervisor", () => {
    const architect = makeSession("ARCHITECT", "arch-42");

    expect(
      canAccessProject(architect, { architectId: "arch-42", supervisorId: null })
    ).toBe(true);
    expect(
      canAccessProject(architect, { architectId: null, supervisorId: "arch-42" })
    ).toBe(true);
    expect(
      canAccessProject(architect, { architectId: "someone-else", supervisorId: "another-person" })
    ).toBe(false);
  });

  it("lets an admin access any project regardless of assignment", () => {
    const admin = makeSession("ADMIN");
    expect(
      canAccessProject(admin, { architectId: "someone-else", supervisorId: null })
    ).toBe(true);
  });

  // --- Senior Architect: firm-wide oversight, between ADMIN and ARCHITECT ---

  it("grants senior architects project create/reassign and firm-wide visibility", () => {
    const senior = makeSession("SENIOR_ARCHITECT");
    expect(isSeniorArchitect(senior)).toBe(true);
    expect(isAdmin(senior)).toBe(false);
    expect(canCreateProjects(senior)).toBe(true);
    expect(canReassignProjects(senior)).toBe(true);
    expect(projectAccessWhere(senior)).toEqual({});
    expect(relatedProjectAccessWhere(senior)).toBeUndefined();
    expect(
      canAccessProject(senior, { architectId: "someone-else", supervisorId: null })
    ).toBe(true);
  });

  it("denies senior architects admin-only capabilities (staff, clients, firm settings, payments)", () => {
    const senior = makeSession("SENIOR_ARCHITECT");
    expect(canManageStaff(senior)).toBe(false);
    expect(canManageClients(senior)).toBe(false);
    expect(canManageFirmSettings(senior)).toBe(false);
    expect(canRecordPayments(senior)).toBe(false);
  });

  it("lets both architects and senior architects view (but not record) payments", () => {
    const architect = makeSession("ARCHITECT");
    const senior = makeSession("SENIOR_ARCHITECT");
    expect(canViewPayments(architect)).toBe(true);
    expect(canViewPayments(senior)).toBe(true);
    expect(canRecordPayments(architect)).toBe(false);
    expect(canRecordPayments(senior)).toBe(false);
  });

  it("still scopes a plain architect's related-project queries to their own assignments", () => {
    const architect = makeSession("ARCHITECT", "arch-42");
    expect(relatedProjectAccessWhere(architect)).toEqual({
      OR: [{ architectId: "arch-42" }, { supervisorId: "arch-42" }],
    });
  });
});

'@
Write-PatchFile "src/lib/rbac.test.ts" $content

# --- [NEW] src/lib/rate-limit.test.ts ---
$content = @'
import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import { rateLimit, getClientIp } from "./rate-limit";

describe("rateLimit", () => {
  it("allows requests up to the limit within the window", () => {
    const key = `test-${Math.random()}`;
    for (let i = 0; i < 5; i++) {
      expect(rateLimit(key, 5, 60_000).ok).toBe(true);
    }
  });

  it("blocks the request once the limit is exceeded", () => {
    const key = `test-${Math.random()}`;
    for (let i = 0; i < 3; i++) {
      rateLimit(key, 3, 60_000);
    }
    const result = rateLimit(key, 3, 60_000);
    expect(result.ok).toBe(false);
    expect(result.retryAfterMs).toBeGreaterThan(0);
  });

  it("tracks separate keys independently", () => {
    const keyA = `test-a-${Math.random()}`;
    const keyB = `test-b-${Math.random()}`;
    for (let i = 0; i < 3; i++) rateLimit(keyA, 3, 60_000);
    // keyA is now exhausted, keyB should be untouched
    expect(rateLimit(keyA, 3, 60_000).ok).toBe(false);
    expect(rateLimit(keyB, 3, 60_000).ok).toBe(true);
  });

  describe("with fake timers", () => {
    beforeEach(() => vi.useFakeTimers());
    afterEach(() => vi.useRealTimers());

    it("resets the bucket once the window elapses", () => {
      const key = `test-window-${Math.random()}`;
      rateLimit(key, 1, 1000);
      expect(rateLimit(key, 1, 1000).ok).toBe(false); // 2nd request, still in window

      vi.advanceTimersByTime(1001);

      expect(rateLimit(key, 1, 1000).ok).toBe(true); // window elapsed, bucket reset
    });
  });
});

describe("getClientIp", () => {
  it("prefers the first address in x-forwarded-for", () => {
    const req = new Request("https://example.com", {
      headers: { "x-forwarded-for": "203.0.113.5, 10.0.0.1" },
    });
    expect(getClientIp(req)).toBe("203.0.113.5");
  });

  it("falls back to x-real-ip when x-forwarded-for is absent", () => {
    const req = new Request("https://example.com", {
      headers: { "x-real-ip": "203.0.113.9" },
    });
    expect(getClientIp(req)).toBe("203.0.113.9");
  });

  it("falls back to 'unknown' when neither header is present", () => {
    const req = new Request("https://example.com");
    expect(getClientIp(req)).toBe("unknown");
  });
});

'@
Write-PatchFile "src/lib/rate-limit.test.ts" $content

# --- [NEW] src/lib/password-policy.test.ts ---
$content = @'
import { describe, expect, it } from "vitest";
import { validatePassword, generateTemporaryPassword, PASSWORD_MIN_LENGTH } from "./password-policy";

describe("validatePassword", () => {
  it("accepts a password meeting every requirement", () => {
    expect(validatePassword("Str0ng!Password").valid).toBe(true);
  });

  it("rejects a password shorter than the minimum length", () => {
    const result = validatePassword("Ab1!");
    expect(result.valid).toBe(false);
    expect(result.errors.some(e => e.includes(String(PASSWORD_MIN_LENGTH)))).toBe(true);
  });

  it("rejects a password missing a lowercase letter", () => {
    const result = validatePassword("STRONG1!PASSWORD");
    expect(result.valid).toBe(false);
    expect(result.errors.some(e => e.includes("lowercase"))).toBe(true);
  });

  it("rejects a password missing an uppercase letter", () => {
    const result = validatePassword("str0ng!password");
    expect(result.valid).toBe(false);
    expect(result.errors.some(e => e.includes("uppercase"))).toBe(true);
  });

  it("rejects a password missing a number", () => {
    const result = validatePassword("Strong!Password");
    expect(result.valid).toBe(false);
    expect(result.errors.some(e => e.includes("number"))).toBe(true);
  });

  it("rejects a password missing a symbol", () => {
    const result = validatePassword("Str0ngPassword");
    expect(result.valid).toBe(false);
    expect(result.errors.some(e => e.includes("symbol"))).toBe(true);
  });

  it("reports every violated rule at once, not just the first", () => {
    const result = validatePassword("short");
    expect(result.errors.length).toBeGreaterThan(1);
  });
});

describe("generateTemporaryPassword", () => {
  it("always generates a password that satisfies the policy it enforces", () => {
    // Run many times since this involves randomness/shuffling.
    for (let i = 0; i < 50; i++) {
      expect(validatePassword(generateTemporaryPassword()).valid).toBe(true);
    }
  });

  it("generates a reasonably long password", () => {
    expect(generateTemporaryPassword().length).toBeGreaterThanOrEqual(14);
  });

  it("does not repeat the exact same password across calls", () => {
    const a = generateTemporaryPassword();
    const b = generateTemporaryPassword();
    expect(a).not.toBe(b);
  });
});

'@
Write-PatchFile "src/lib/password-policy.test.ts" $content

# --- [NEW] src/lib/file-picker-guard.test.ts ---
$content = @'
import { describe, expect, it, vi, beforeEach, afterEach } from "vitest";
import {
  notifyFilePickerOpening,
  isFilePickerOpen,
  consumeFilePickerReturn,
} from "./file-picker-guard";

// This module holds module-level singleton state (not per-instance), so
// each test resets it via consumeFilePickerReturn() to avoid leaking state
// between tests.
beforeEach(() => {
  consumeFilePickerReturn();
});

describe("file-picker-guard", () => {
  it("starts closed: no picker open, nothing to consume", () => {
    expect(isFilePickerOpen()).toBe(false);
    expect(consumeFilePickerReturn()).toBe(false);
  });

  it("marks the picker open when notified", () => {
    notifyFilePickerOpening();
    expect(isFilePickerOpen()).toBe(true);
  });

  it("consumes exactly once: the first focus-return clears the flag", () => {
    notifyFilePickerOpening();

    expect(consumeFilePickerReturn()).toBe(true);
    expect(isFilePickerOpen()).toBe(false);

    // A second focus event right after should NOT be treated as another
    // picker close -- this is what lets normal tab-switching refreshes
    // resume immediately afterward.
    expect(consumeFilePickerReturn()).toBe(false);
  });

  it("has no fixed cooldown -- stays open no matter how long the picker takes", () => {
    vi.useFakeTimers();
    try {
      notifyFilePickerOpening();

      // The old (buggy) v1 guard expired after a fixed 2 seconds. This
      // version has no such timer for normal use -- simulate someone
      // spending a full minute browsing to a file.
      vi.advanceTimersByTime(60_000);

      expect(isFilePickerOpen()).toBe(true);
      expect(consumeFilePickerReturn()).toBe(true);
    } finally {
      vi.useRealTimers();
    }
  });

  it("self-clears via the safety net if focus never returns (backstop only)", () => {
    vi.useFakeTimers();
    try {
      notifyFilePickerOpening();
      expect(isFilePickerOpen()).toBe(true);

      vi.advanceTimersByTime(5 * 60 * 1000 + 1);

      expect(isFilePickerOpen()).toBe(false);
    } finally {
      vi.useRealTimers();
    }
  });

  it("re-arms the safety net if a picker is opened again before the first one clears", () => {
    vi.useFakeTimers();
    try {
      notifyFilePickerOpening();
      vi.advanceTimersByTime(4 * 60 * 1000); // 4 minutes in, still within safety window

      notifyFilePickerOpening(); // opened again -- should extend, not expire early
      vi.advanceTimersByTime(4 * 60 * 1000); // another 4 minutes (8 total from first call)

      // Still open because the second call reset the 5-minute backstop.
      expect(isFilePickerOpen()).toBe(true);
    } finally {
      vi.useRealTimers();
    }
  });
});

'@
Write-PatchFile "src/lib/file-picker-guard.test.ts" $content

Write-Host ""
Write-Host "Patch 5 applied. Run:" -ForegroundColor Green
Write-Host "  npm test"
Write-Host "Expect: 4 test files, 33 tests, all passing."
