<#
  Architect Hub -- patch 15: fixes "UntrustedHost" -- nobody could have
  logged in in production without this.
  Generated by Claude -- 2026-08-22

  Auth.js rejects every request in production unless the host is
  explicitly trusted -- Vercel auto-trusts its own host, but any
  self-hosted deployment (Railway, Docker, your own npm run start test)
  needs trustHost: true set explicitly. Without it: every single
  session check, login, everything auth-related fails with
  UntrustedHost. Dev mode is permissive enough that this never surfaced
  until your actual production build test just now -- which is exactly
  why that test was worth doing before a real deploy.

  This is safe: middleware.ts already does its own Origin/Referer
  same-origin check on every mutating request (isCrossOriginMutation),
  which is the actual defense against host-header-style attacks,
  independent of this setting.

  Lint clean, 62/62 tests on your machine (confirmed from your last run).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-15.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 15 (fix UntrustedHost)..." -ForegroundColor Cyan

# --- [MOD] src/lib/auth.ts ---
$content = @'
import NextAuth, { CredentialsSignin } from "next-auth";
import Credentials from "next-auth/providers/credentials";
import bcrypt from "bcryptjs";
import { prisma } from "./prisma";
import type { AppRole } from "@/types/next-auth";

const MAX_FAILED_ATTEMPTS = 5;
const LOCKOUT_MINUTES = 15;

const DEFAULT_SESSION_SECONDS = 8 * 60 * 60; // 8 hours
const REMEMBER_ME_SESSION_SECONDS = 30 * 24 * 60 * 60; // 30 days

class MfaRequiredError extends CredentialsSignin {
  code = "MFA_REQUIRED";
}

class AccountLockedError extends CredentialsSignin {
  code = "ACCOUNT_LOCKED";
}

class AccountInactiveError extends CredentialsSignin {
  code = "ACCOUNT_INACTIVE";
}

/**
 * Records authentication events without ever allowing audit logging
 * to break the authentication flow.
 */
async function logLoginEvent(
  userId: string | null,
  success: boolean,
  reason: string
) {
  try {
    await prisma.loginEvent.create({
      data: {
        userId: userId ?? undefined,
        success,
        reason,
      },
    });
  } catch {
    // Never let audit logging break login.
  }
}

/**
 * Client Portal login.
 *
 * This remains deliberately separate from staff authentication:
 *
 * - no MFA
 * - no staff failed-attempt lockout
 * - no staff LoginEvent
 * - requires portalEnabled
 * - requires a client password
 */
async function authorizeClientPortal(
  email: string,
  password: string
) {
  const client = await prisma.client.findFirst({
    where: {
      email,
    },
  });

  if (
    !client ||
    !client.portalEnabled ||
    !client.passwordHash
  ) {
    return null;
  }

  const passwordValid = await bcrypt.compare(
    password,
    client.passwordHash
  );

  if (!passwordValid) {
    return null;
  }

  await prisma.client.update({
    where: {
      id: client.id,
    },
    data: {
      lastPortalLoginAt: new Date(),
    },
  });

  return {
    id: client.id,
    name: client.contactPerson,
    email: client.email,
    role: "CLIENT" as const,

    initials: client.contactPerson
      .split(" ")
      .map((part: string) => part[0])
      .slice(0, 2)
      .join("")
      .toUpperCase(),

    clientId: client.id,

    /*
     * Client accounts never use the staff first-login
     * password-reset mechanism.
     */
    mustResetPassword: false,
  };
}

export const {
  handlers,
  auth,
  signIn,
  signOut,
} = NextAuth({
  secret: process.env.AUTH_SECRET,

  /*
   * Required for any self-hosted deployment (Railway, Docker, or
   * anywhere that isn't Vercel, which auto-trusts its own host).
   * Without this, Auth.js rejects every request in production with
   * "UntrustedHost" -- meaning nobody can log in, check their session,
   * or do anything auth-related at all. Dev mode is permissive enough
   * that this never surfaces there, which is exactly why it slipped
   * through until an actual production build was run.
   *
   * This is safe here specifically because middleware.ts already does
   * its own Origin/Referer same-origin check on every mutating request
   * (see isCrossOriginMutation) -- that's the real defense against
   * host-header-style attacks, independent of this setting.
   */
  trustHost: true,

  session: {
    strategy: "jwt",
    maxAge: DEFAULT_SESSION_SECONDS,
  },

  pages: {
    signIn: "/login",
  },

  callbacks: {
    async jwt({
      token,
      user,
    }) {
      if (user) {
        token.id = user.id as string;

        token.role = user.role;

        token.initials = user.initials;

        token.clientId = (
          user as {
            clientId?: string;
          }
        ).clientId;

        /*
         * Keep mustResetPassword in the JWT so the application
         * can force a newly-created staff member to change the
         * temporary password before accessing the rest of the app.
         */
        token.mustResetPassword = (
          user as {
            mustResetPassword?: boolean;
          }
        ).mustResetPassword ?? false;

        const remember = (
          user as {
            remember?: boolean;
          }
        ).remember;

        if (remember) {
          token.exp =
            Math.floor(Date.now() / 1000) +
            REMEMBER_ME_SESSION_SECONDS;
        }
      }

      return token;
    },

    async session({
      session,
      token,
    }) {
      if (token) {
        session.user.id = token.id as string;

        session.user.role =
          token.role as AppRole;

        session.user.initials =
          token.initials as string;

        session.user.clientId =
          token.clientId as string | undefined;

        session.user.mustResetPassword =
          Boolean(token.mustResetPassword);
      }

      return session;
    },
  },

  providers: [
    Credentials({
      name: "credentials",

      credentials: {
        email: {
          label: "Email",
          type: "email",
        },

        password: {
          label: "Password",
          type: "password",
        },

        mfaCode: {
          label: "MFA Code",
          type: "text",
        },

        rememberMe: {
          label: "Remember me",
          type: "text",
        },
      },

      async authorize(credentials) {
        const email = (
          credentials?.email as
            | string
            | undefined
        )
          ?.trim()
          .toLowerCase();

        const password =
          credentials?.password as
            | string
            | undefined;

        if (!email || !password) {
          return null;
        }

        /*
         * ---------------------------------------------------------------
         * STAFF ACCOUNT
         * ---------------------------------------------------------------
         */

        const user =
          await prisma.user.findUnique({
            where: {
              email,
            },
          });

        /*
         * ---------------------------------------------------------------
         * CLIENT PORTAL FALLBACK
         * ---------------------------------------------------------------
         *
         * If there is no staff account with this email, check the
         * separate Client Portal authentication path.
         */

        if (!user) {
          return authorizeClientPortal(
            email,
            password
          );
        }

        /*
         * ---------------------------------------------------------------
         * ACCOUNT LOCKOUT
         * ---------------------------------------------------------------
         */

        if (
          user.lockedUntil &&
          user.lockedUntil.getTime() >
            Date.now()
        ) {
          await logLoginEvent(
            user.id,
            false,
            "locked"
          );

          throw new AccountLockedError();
        }

        /*
         * ---------------------------------------------------------------
         * ACCOUNT ACTIVE CHECK
         * ---------------------------------------------------------------
         */

        if (!user.isActive) {
          await logLoginEvent(
            user.id,
            false,
            "inactive"
          );

          throw new AccountInactiveError();
        }

        /*
         * ---------------------------------------------------------------
         * PASSWORD VERIFICATION
         * ---------------------------------------------------------------
         */

        const passwordValid =
          await bcrypt.compare(
            password,
            user.password
          );

        if (!passwordValid) {
          const attempts =
            user.failedLoginAttempts + 1;

          const shouldLock =
            attempts >=
            MAX_FAILED_ATTEMPTS;

          await prisma.user.update({
            where: {
              id: user.id,
            },

            data: {
              failedLoginAttempts:
                shouldLock
                  ? 0
                  : attempts,

              lockedUntil:
                shouldLock
                  ? new Date(
                      Date.now() +
                        LOCKOUT_MINUTES *
                          60 *
                          1000
                    )
                  : null,
            },
          });

          await logLoginEvent(
            user.id,
            false,
            shouldLock
              ? "locked_out"
              : "bad_password"
          );

          if (shouldLock) {
            throw new AccountLockedError();
          }

          return null;
        }

        /*
         * ---------------------------------------------------------------
         * MFA
         * ---------------------------------------------------------------
         */

        if (
          user.mfaEnabled &&
          user.mfaSecret
        ) {
          const code =
            (credentials?.mfaCode as string) ||
            "";

          if (!code) {
            throw new MfaRequiredError();
          }

          const {
            authenticator,
          } = await import(
            "otplib"
          );

          const valid =
            authenticator.verify({
              token: code,
              secret: user.mfaSecret,
            });

          if (!valid) {
            await logLoginEvent(
              user.id,
              false,
              "bad_mfa"
            );

            return null;
          }
        }

        /*
         * ---------------------------------------------------------------
         * SUCCESSFUL AUTHENTICATION
         * ---------------------------------------------------------------
         *
         * We deliberately allow the session to be created even when
         * mustResetPassword is true.
         *
         * The flag is included in the JWT/session and the application
         * forces the user through the password-change screen.
         */

        await prisma.user.update({
          where: {
            id: user.id,
          },

          data: {
            lastLoginAt: new Date(),
            failedLoginAttempts: 0,
            lockedUntil: null,
          },
        });

        await logLoginEvent(
          user.id,
          true,
          user.mustResetPassword
            ? "success_password_reset_required"
            : "success"
        );

        return {
          id: user.id,
          name: user.name,
          email: user.email,
          role: user.role,
          initials: user.initials,

          remember:
            (credentials?.rememberMe as string) ===
            "true",

          mustResetPassword:
            user.mustResetPassword,
        };
      },
    }),
  ],
});
'@
Write-PatchFile "src/lib/auth.ts" $content

Write-Host ""
Write-Host "Patch 15 applied. Run:" -ForegroundColor Green
Write-Host "  npm run build"
Write-Host "  npm run start"
Write-Host "Open http://localhost:3000 and actually log in this time -- that's the real proof this is fixed." -ForegroundColor Green
