<#
  Architect Hub -- patch 44: fixes invisible input text in dark mode
  across nearly the whole app.
  Generated by Claude -- 2026-08-28

  ROOT CAUSE: src/components/ui/form-field.tsx -- the shared base style
  every Input/Select/Textarea in the app uses -- hardcoded bg-white
  literally, bypassing the theme system entirely. Text inside correctly
  followed the theme (light-colored in dark mode via text-ink), but the
  background never did, so every form field in the app had light text
  on a permanently-white background in dark mode -- invisible.

  FIXED: the shared component (highest-leverage single fix, covers
  most forms in the app at once), plus 11 individual raw <input>/
  <textarea> elements across 5 pages that duplicate the same styling
  inline instead of using the shared component (login, reset-password,
  forgot-password, client-comms, project detail's payment form) -- all
  changed from bg-white to bg-surface (the theme-aware token) with an
  explicit text-ink alongside it.

  DELIBERATELY LEFT ALONE: three other bg-white uses that are correct
  as-is -- the sidebar's hover state (the sidebar is intentionally dark
  in both themes, an earlier design decision) and two toggle-switch
  knobs (MFA and notification preference toggles) -- a switch's white
  circular handle is meant to stay white against its colored track in
  both light and dark mode, changing those would make the switches look
  broken instead of fixing anything.

  Verified with a full search after fixing -- only those three
  intentional cases remain anywhere in the codebase.

  Lint clean, 62/62 tests on your machine (same 3 sandbox-only failures
  here, confirmed unrelated in every earlier patch).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-44.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 44 (dark mode input text fix)..." -ForegroundColor Cyan

# --- [MOD] src/components/ui/form-field.tsx ---
$content = @'
import { InputHTMLAttributes, SelectHTMLAttributes, TextareaHTMLAttributes } from "react";
import { cn } from "@/lib/utils";

const base = "w-full border border-line rounded-md px-3 py-2 text-[13px] bg-surface text-ink outline-none focus:border-blueprint focus:ring-1 focus:ring-blueprint transition-colors";

export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) {
  return <input className={cn(base, className)} {...props} />;
}

export function Select({ className, children, ...props }: SelectHTMLAttributes<HTMLSelectElement>) {
  return <select className={cn(base, className)} {...props}>{children}</select>;
}

export function Textarea({ className, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement>) {
  return <textarea className={cn(base, "resize-none", className)} {...props} />;
}

export function Field({ label, children, required }: { label: string; children: React.ReactNode; required?: boolean }) {
  return (
    <div>
      <label className="text-[12px] text-muted block mb-1.5">
        {label}{required && <span className="text-brick ml-0.5">*</span>}
      </label>
      {children}
    </div>
  );
}

export function FormRow({ children }: { children: React.ReactNode }) {
  return <div className="grid grid-cols-2 gap-3">{children}</div>;
}

'@
Write-PatchFile "src/components/ui/form-field.tsx" $content

# --- [MOD] src/components/layout/app-shell.tsx ---
$content = @'
"use client";
import { useState } from "react";
import { Menu } from "lucide-react";
import { Sidebar } from "@/components/layout/sidebar";
import { ProfileMenu } from "@/components/layout/profile-menu";
import { useStore } from "@/store/app-store";

export function AppShell({ children }: { children: React.ReactNode }) {
  const { loading, error } = useStore();
  const [mobileNavOpen, setMobileNavOpen] = useState(false);

  return (
    <div className="flex min-h-screen bg-vellum">
      <Sidebar open={mobileNavOpen} onClose={() => setMobileNavOpen(false)} />
      <main className="flex-1 p-4 sm:p-6 lg:p-7 overflow-x-hidden min-w-0">
        <div className="flex items-center justify-between mb-3">
          {/* Hamburger trigger, mobile only -- the sidebar is always
              visible at lg and up, so this has nothing to do there. */}
          <button
            type="button"
            onClick={() => setMobileNavOpen(true)}
            aria-label="Open menu"
            className="lg:hidden text-muted hover:text-ink p-1.5 -ml-1.5 rounded-md hover:bg-vellum"
          >
            <Menu size={20} />
          </button>
          <div className="flex-1" />
          <ProfileMenu />
        </div>
        {loading ? (
          <div className="flex items-center justify-center h-64">
            <div className="flex flex-col items-center gap-3">
              <div className="w-8 h-8 border-2 border-blueprint border-t-transparent rounded-full animate-spin" />
              <span className="text-muted text-[12.5px]">Loading data…</span>
            </div>
          </div>
        ) : error ? (
          <div className="bg-brick-bg border border-brick/20 rounded-card p-5 max-w-md">
            <div className="text-brick font-medium text-[13px] mb-1">Failed to load data</div>
            <p className="text-[12.5px] text-brick/80">{error}</p>
            <p className="text-[11.5px] text-muted mt-2">Make sure your DATABASE_URL is set in .env and the database is running.</p>
          </div>
        ) : (
          children
        )}
      </main>
    </div>
  );
}

'@
Write-PatchFile "src/components/layout/app-shell.tsx" $content

# --- [MOD] src/app/forgot-password/page.tsx ---
$content = @'
"use client";

import { useState } from "react";
import Link from "next/link";

export default function ForgotPasswordPage() {
  const [email, setEmail] = useState("");
  const [submitted, setSubmitted] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError("");
    try {
      const res = await fetch("/api/auth/forgot-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => ({}));
        throw new Error(data.error || "Something went wrong.");
      }
      setSubmitted(true);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-vellum flex items-center justify-center p-6">
      <div className="w-full max-w-[400px] flex flex-col gap-4">
        <div className="flex items-center gap-2 justify-center mb-2">
          <svg width="22" height="22" viewBox="0 0 18 18" aria-hidden="true">
            <path d="M2 16 L9 2 L16 16 Z" fill="none" stroke="#2451C4" strokeWidth="1.4" />
            <line x1="2" y1="16" x2="16" y2="16" stroke="#2451C4" strokeWidth="1.4" />
          </svg>
          <span className="font-display font-bold text-[19px] text-ink">Architect Hub</span>
        </div>

        <div className="bg-surface border border-line rounded-card p-5">
          {submitted ? (
            <div className="flex flex-col gap-3 text-center">
              <p className="text-ink text-[13px] font-medium">Check your email</p>
              <p className="text-muted text-[12px]">
                If an account exists for {email}, we&rsquo;ve sent a link to reset your password. It expires in 1 hour.
              </p>
              <Link href="/login" className="text-blueprint text-[12px] hover:underline">
                ← Back to login
              </Link>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="flex flex-col gap-3">
              <p className="text-muted text-[12px]">
                Enter the email associated with your account and we&rsquo;ll send a link to reset your password.
              </p>
              <div>
                <label className="text-[12px] text-muted block mb-1.5">Email</label>
                <input
                  type="email"
                  required
                  autoComplete="username"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full border border-line rounded-md px-3 py-2 text-[13px] outline-none focus:border-blueprint bg-surface text-ink"
                />
              </div>
              {error && <p className="text-brick text-[12px]">{error}</p>}
              <button
                type="submit"
                disabled={loading}
                className="bg-ink text-white rounded-md py-2 text-[13px] font-medium hover:bg-ink/90 disabled:opacity-60"
              >
                {loading ? "Sending…" : "Send reset link"}
              </button>
              <Link href="/login" className="text-muted text-[11.5px] text-center hover:underline">
                ← Back to login
              </Link>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}

'@
Write-PatchFile "src/app/forgot-password/page.tsx" $content

# --- [MOD] src/app/reset-password/page.tsx ---
$content = @'
"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense } from "react";

function ResetPasswordContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const token = searchParams.get("token") || "";

  const [password, setPassword] = useState("");
  const [confirm, setConfirm] = useState("");
  const [done, setDone] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");
    if (password !== confirm) {
      setError("Passwords do not match.");
      return;
    }
    setLoading(true);
    try {
      const res = await fetch("/api/auth/reset-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token, password }),
      });
      const data = await res.json().catch(() => ({}));
      if (!res.ok) throw new Error(data.error || "Something went wrong.");
      setDone(true);
      setTimeout(() => router.push("/login"), 2000);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  if (!token) {
    return (
      <div className="min-h-screen bg-vellum flex items-center justify-center p-6">
        <div className="w-full max-w-[400px] bg-surface border border-line rounded-card p-5 text-center">
          <p className="text-brick text-[13px]">This reset link is missing a token.</p>
          <Link href="/forgot-password" className="text-blueprint text-[12px] hover:underline">
            Request a new link
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-vellum flex items-center justify-center p-6">
      <div className="w-full max-w-[400px] flex flex-col gap-4">
        <div className="flex items-center gap-2 justify-center mb-2">
          <svg width="22" height="22" viewBox="0 0 18 18" aria-hidden="true">
            <path d="M2 16 L9 2 L16 16 Z" fill="none" stroke="#2451C4" strokeWidth="1.4" />
            <line x1="2" y1="16" x2="16" y2="16" stroke="#2451C4" strokeWidth="1.4" />
          </svg>
          <span className="font-display font-bold text-[19px] text-ink">Architect Hub</span>
        </div>

        <div className="bg-surface border border-line rounded-card p-5">
          {done ? (
            <p className="text-moss text-[13px] text-center">Password updated. Redirecting to login…</p>
          ) : (
            <form onSubmit={handleSubmit} className="flex flex-col gap-3">
              <p className="text-muted text-[12px]">
                Choose a new password (min 10 characters, with upper/lowercase, a number, and a symbol).
              </p>
              <div>
                <label className="text-[12px] text-muted block mb-1.5">New password</label>
                <input
                  type="password"
                  required
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full border border-line rounded-md px-3 py-2 text-[13px] outline-none focus:border-blueprint bg-surface text-ink"
                />
              </div>
              <div>
                <label className="text-[12px] text-muted block mb-1.5">Confirm new password</label>
                <input
                  type="password"
                  required
                  value={confirm}
                  onChange={(e) => setConfirm(e.target.value)}
                  className="w-full border border-line rounded-md px-3 py-2 text-[13px] outline-none focus:border-blueprint bg-surface text-ink"
                />
              </div>
              {error && <p className="text-brick text-[12px]">{error}</p>}
              <button
                type="submit"
                disabled={loading}
                className="bg-ink text-white rounded-md py-2 text-[13px] font-medium hover:bg-ink/90 disabled:opacity-60"
              >
                {loading ? "Updating…" : "Update password"}
              </button>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}

export default function ResetPasswordPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <ResetPasswordContent />
    </Suspense>
  );
}

'@
Write-PatchFile "src/app/reset-password/page.tsx" $content

# --- [MOD] src/app/login/page.tsx ---
$content = @'
"use client";

import { useState } from "react";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { useRouter, useSearchParams } from "next/navigation";
import { Suspense } from "react";
import { useFirmName } from "@/lib/use-firm-name";

function LoginContent() {
  const router = useRouter();
  const firmName = useFirmName();
  const searchParams = useSearchParams();
  const callbackUrl = searchParams.get("callbackUrl") || "/dashboard";

  const [step, setStep] = useState<"credentials" | "mfa">("credentials");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [rememberMe, setRememberMe] = useState(false);
  const [mfaCode, setMfaCode] = useState(["", "", "", "", "", ""]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function attemptSignIn(mfaToken = "") {
    setLoading(true);
    setError("");
    const result = await signIn("credentials", {
      email,
      password,
      mfaCode: mfaToken,
      rememberMe: rememberMe ? "true" : "false",
      redirect: false,
    });
    setLoading(false);

    if (!result?.error) {
      router.push(callbackUrl);
      router.refresh();
      return { ok: true as const };
    }

    return { ok: false as const, code: result.error };
  }

  async function handleCredentials(e: React.FormEvent) {
    e.preventDefault();
    const result = await attemptSignIn("");
    if (!result.ok) {
      if (result.code === "MFA_REQUIRED") {
        setStep("mfa");
        setError("");
      } else if (result.code === "ACCOUNT_LOCKED") {
        setError("This account is temporarily locked due to repeated failed attempts. Try again later or contact your administrator.");
      } else if (result.code === "ACCOUNT_INACTIVE") {
        setError("This account has been deactivated. Contact your administrator.");
      } else {
        setError("Invalid email or password.");
      }
    }
  }

  async function handleMfa(e: React.FormEvent) {
    e.preventDefault();
    const code = mfaCode.join("");
    const result = await attemptSignIn(code);
    if (!result.ok) setError("Invalid MFA code. Try again.");
  }

  function handleMfaInput(val: string, i: number) {
    const next = [...mfaCode];
    next[i] = val.replace(/[^0-9]/g, "").slice(-1);
    setMfaCode(next);
    if (val && i < 5) document.getElementById(`mfa-${i + 1}`)?.focus();
  }

  return (
    <div className="min-h-screen bg-vellum flex items-center justify-center p-6">
      <div className="w-full max-w-[400px] flex flex-col gap-4">
        {/* Logo */}
        <div className="flex items-center gap-2 justify-center mb-2">
          <svg width="22" height="22" viewBox="0 0 18 18" aria-hidden="true">
            <path d="M2 16 L9 2 L16 16 Z" fill="none" stroke="#2451C4" strokeWidth="1.4" />
            <line x1="2" y1="16" x2="16" y2="16" stroke="#2451C4" strokeWidth="1.4" />
          </svg>
          <span className="font-display font-bold text-[19px] text-ink">{firmName}</span>
        </div>

        <div className="bg-surface border border-line rounded-card p-5">
          {step === "credentials" ? (
            <form onSubmit={handleCredentials} className="flex flex-col gap-3">
              <div>
                <label className="text-[12px] text-muted block mb-1.5">Email</label>
                <input
                  type="email"
                  required
                  autoComplete="username"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full border border-line rounded-md px-3 py-2 text-[13px] outline-none focus:border-blueprint bg-surface text-ink"
                />
              </div>
              <div>
                <label className="text-[12px] text-muted block mb-1.5">Password</label>
                <input
                  type="password"
                  required
                  autoComplete="current-password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full border border-line rounded-md px-3 py-2 text-[13px] outline-none focus:border-blueprint bg-surface text-ink"
                />
              </div>
              <div className="flex items-center justify-between">
                <label className="flex items-center gap-2 text-[12px] text-muted cursor-pointer select-none">
                  <input
                    type="checkbox"
                    checked={rememberMe}
                    onChange={(e) => setRememberMe(e.target.checked)}
                    className="rounded border-line"
                  />
                  Remember me
                </label>
                <Link href="/forgot-password" className="text-[12px] text-blueprint hover:underline">
                  Forgot password?
                </Link>
              </div>
              {error && <p className="text-brick text-[12px]">{error}</p>}
              <button
                type="submit"
                disabled={loading}
                className="bg-ink text-white rounded-md py-2 text-[13px] font-medium hover:bg-ink/90 disabled:opacity-60"
              >
                {loading ? "Signing in…" : "Login"}
              </button>
            </form>
          ) : (
            <form onSubmit={handleMfa} className="flex flex-col gap-3">
              <p className="text-muted text-[12px]">Enter your 6-digit authenticator code.</p>
              <div className="flex gap-2">
                {mfaCode.map((digit, i) => (
                  <input
                    key={i}
                    id={`mfa-${i}`}
                    maxLength={1}
                    value={digit}
                    onChange={(e) => handleMfaInput(e.target.value, i)}
                    className="w-full aspect-square text-center border border-line rounded-md text-[16px] font-mono outline-none focus:border-blueprint bg-surface text-ink"
                  />
                ))}
              </div>
              {error && <p className="text-brick text-[12px]">{error}</p>}
              <button
                type="submit"
                disabled={loading}
                className="bg-ink text-white rounded-md py-2 text-[13px] font-medium hover:bg-ink/90 disabled:opacity-60"
              >
                {loading ? "Verifying…" : "Verify and sign in"}
              </button>
              <button
                type="button"
                onClick={() => {
                  setStep("credentials");
                  setError("");
                  setMfaCode(["", "", "", "", "", ""]);
                }}
                className="text-muted text-[11.5px] text-center"
              >
                ← Back
              </button>
            </form>
          )}
        </div>
      </div>
    </div>
  );
}

export default function LoginPage() {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <LoginContent />
    </Suspense>
  );
}

'@
Write-PatchFile "src/app/login/page.tsx" $content

# --- [MOD] src/app/client-comms/page.tsx ---
$content = @'
"use client";
import { useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Card } from "@/components/ui/card";
import { Modal } from "@/components/ui/modal";
import { Select, Textarea, Field } from "@/components/ui/form-field";
import { useStore, commentTypeLabel, CommentType } from "@/store/app-store";
import { CheckCircle, MessageCircle, Filter } from "lucide-react";

const typeColors: Record<CommentType, string> = {
  CHANGE_REQUEST: "bg-brick-bg text-brick",
  APPROVAL: "bg-moss-bg text-moss",
  QUERY: "bg-blueprint-bg text-blueprint",
  FEEDBACK: "bg-ochre-bg text-ochre",
};

export default function ClientCommsPage() {
  const { comments, projects, clients, addComment, resolveComment } = useStore();
  const [filterProject, setFilterProject] = useState("all");
  const [filterType, setFilterType] = useState("all");
  const [replyOpen, setReplyOpen] = useState<string | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  const [form, setForm] = useState({ projectId: "", clientId: "", author: "", content: "", type: "FEEDBACK" as CommentType });

  const visible = comments
    .filter(c => filterProject === "all" || c.projectId === filterProject)
    .filter(c => filterType === "all" || c.type === filterType)
    .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  function handleAdd(e: React.FormEvent) {
    e.preventDefault();
    const client = clients.find(c => c.id === form.clientId);
    addComment({ ...form, author: form.author || client?.contactPerson || "Client" });
    setAddOpen(false);
    setForm({ projectId: "", clientId: "", author: "", content: "", type: "FEEDBACK" });
  }

  return (
    <AppShell>
      <div>
        <div className="flex items-center justify-between mb-5">
          <div>
            <h1 className="font-display font-bold text-[20px] text-ink">Client communications</h1>
            <p className="text-muted text-[12px] mt-0.5">{comments.filter(c=>!c.resolvedAt).length} unresolved · {comments.length} total</p>
          </div>
          <button onClick={() => setAddOpen(true)} className="flex items-center gap-1.5 bg-ink text-white rounded-md px-3.5 py-2 text-[12.5px] font-medium hover:bg-ink/90">
            <MessageCircle size={15} />Log comment
          </button>
        </div>

        {/* Filters */}
        <div className="flex items-center gap-2 mb-4 flex-wrap">
          <Filter size={14} className="text-muted" />
          <select value={filterProject} onChange={e => setFilterProject(e.target.value)} className="border border-line rounded-md px-2.5 py-1.5 text-[12px] bg-surface outline-none">
            <option value="all">All projects</option>
            {projects.map(p => <option key={p.id} value={p.id}>{p.sheetNo} — {p.name}</option>)}
          </select>
          <select value={filterType} onChange={e => setFilterType(e.target.value)} className="border border-line rounded-md px-2.5 py-1.5 text-[12px] bg-surface outline-none">
            <option value="all">All types</option>
            <option value="CHANGE_REQUEST">Change requests</option>
            <option value="APPROVAL">Approvals</option>
            <option value="QUERY">Queries</option>
            <option value="FEEDBACK">Feedback</option>
          </select>
          <label className="flex items-center gap-1.5 text-[12px] text-muted cursor-pointer ml-auto">
            <input type="checkbox" onChange={e => setFilterType(e.target.checked ? "__unresolved__" : "all")} className="accent-blueprint" />
            Unresolved only
          </label>
        </div>

        <div className="flex flex-col gap-3">
          {visible.length === 0 && (
            <Card className="p-8 text-center text-muted text-[12.5px]">No comments match your filters.</Card>
          )}
          {visible.map(comment => {
            const project = projects.find(p => p.id === comment.projectId);
            const isResolved = !!comment.resolvedAt;
            return (
              <Card key={comment.id} className={`p-4 transition-opacity ${isResolved ? "opacity-60" : ""}`}>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1.5 flex-wrap">
                      <div className="w-6 h-6 rounded-full bg-ochre-bg text-ochre text-[10px] font-semibold flex items-center justify-center shrink-0">
                        {comment.author.split(" ").map(w=>w[0]).join("").slice(0,2)}
                      </div>
                      <span className="text-ink font-medium text-[13px]">{comment.author}</span>
                      <span className="text-muted text-[11.5px]">on</span>
                      <span className="text-ink text-[11.5px] font-mono">{project?.sheetNo}</span>
                      <span className="text-muted text-[11.5px]">— {project?.name}</span>
                      <span className={`ml-auto text-[10px] px-2 py-0.5 rounded-[3px] font-medium ${typeColors[comment.type]}`}>
                        {commentTypeLabel(comment.type)}
                      </span>
                    </div>
                    <p className="text-[12.5px] text-ink leading-relaxed">{comment.content}</p>
                    <div className="text-[11px] text-muted mt-2 font-mono">
                      {new Date(comment.createdAt).toLocaleString("en-KE", { dateStyle: "medium", timeStyle: "short" })}
                      {isResolved && <span className="ml-3 text-moss">✓ Resolved</span>}
                    </div>
                  </div>
                  <div className="flex flex-col gap-1.5 shrink-0">
                    {!isResolved && (
                      <button onClick={() => resolveComment(comment.id)} className="flex items-center gap-1 text-[11px] text-moss border border-moss/30 rounded px-2 py-1 hover:bg-moss-bg transition-colors">
                        <CheckCircle size={12} />Resolve
                      </button>
                    )}
                  </div>
                </div>
              </Card>
            );
          })}
        </div>

        {/* Log comment modal */}
        <Modal open={addOpen} onClose={() => setAddOpen(false)} title="Log client comment" subtitle="Record a comment, change request, approval, or query from a client">
          <form onSubmit={handleAdd} className="flex flex-col gap-3.5">
            <Field label="Project" required>
              <Select required value={form.projectId} onChange={e => { const p = projects.find(pr=>pr.id===e.target.value); setForm(f=>({...f,projectId:e.target.value,clientId:p?.clientId||""})); }}>
                <option value="">Select project</option>
                {projects.map(p=><option key={p.id} value={p.id}>{p.sheetNo} — {p.name}</option>)}
              </Select>
            </Field>
            <Field label="Comment type" required>
              <Select required value={form.type} onChange={e => setForm(f=>({...f,type:e.target.value as typeof form.type}))}>
                <option value="FEEDBACK">Feedback</option>
                <option value="CHANGE_REQUEST">Change request</option>
                <option value="APPROVAL">Approval</option>
                <option value="QUERY">Query</option>
              </Select>
            </Field>
            <Field label="Client / author name">
              <input className="w-full border border-line rounded-md px-3 py-2 text-[13px] bg-surface text-ink outline-none focus:border-blueprint" value={form.author} onChange={e => setForm(f=>({...f,author:e.target.value}))} placeholder="e.g. James Mwangi" />
            </Field>
            <Field label="Comment" required>
              <Textarea required rows={4} value={form.content} onChange={e => setForm(f=>({...f,content:e.target.value}))} placeholder="Enter the client's comment, instruction, or feedback…" />
            </Field>
            <div className="flex justify-end gap-2 pt-1 border-t border-line mt-1">
              <button type="button" onClick={() => setAddOpen(false)} className="px-4 py-2 rounded-md text-[12.5px] border border-line text-muted">Cancel</button>
              <button type="submit" className="px-4 py-2 rounded-md text-[12.5px] bg-ink text-white font-medium">Log comment</button>
            </div>
          </form>
        </Modal>
      </div>
    </AppShell>
  );
}

'@
Write-PatchFile "src/app/client-comms/page.tsx" $content

# --- [MOD] src/app/projects/[id]/page.tsx ---
$content = @'
"use client";
import { use, useState, useRef } from "react";
import { notFound, useRouter } from "next/navigation";
import { useSession } from "next-auth/react";
import { AppShell } from "@/components/layout/app-shell";
import { Card } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { Modal } from "@/components/ui/modal";
import { Input, Select, Textarea, Field, FormRow } from "@/components/ui/form-field";
import { useStore, formatKsh, formatFileSize, commentTypeLabel, priorityLabel, ProjectStatus, Priority } from "@/store/app-store";
import Link from "next/link";
import { Repeat, Upload, FileText, MessageSquare, Wallet, History, CheckCircle, Pencil, Trash2, Download, File as FileIcon, ArrowRightLeft, Eye, EyeOff, Archive } from "lucide-react";
import { Avatar } from "@/components/ui/avatar";
import { calculateFinancialProgress } from "@/lib/project-progress";

const tabs = [
  { key: "overview", label: "Overview", icon: FileText },
  { key: "logs", label: "Daily logs", icon: History },
  { key: "documents", label: "Documents", icon: Upload },
  { key: "comms", label: "Client comms", icon: MessageSquare },
  { key: "finance", label: "Finance", icon: Wallet },
] as const;
type TabKey = (typeof tabs)[number]["key"];

export default function ProjectDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const { data: session } = useSession();
  const {
    projects, staff, clients, logs, comments, payments, documents,
    addPayment, reassignProject, resolveComment, updateProject, removeProject,
    uploadDocument, removeDocument, toggleDocumentVisibility,
  } = useStore();

  const projectData = projects.find(p => p.id === id);
  if (!projectData) notFound();
  const project = projectData;

  const role = session?.user?.role;
  const isAdmin = role === "ADMIN";
  const canEdit = isAdmin || project.architectId === session?.user?.id || project.supervisorId === session?.user?.id;
  const canReassign = isAdmin;

  const [tab, setTab] = useState<TabKey>("overview");
  const [reassignOpen, setReassignOpen] = useState(false);
  const [reassignTo, setReassignTo] = useState("");
  const [reassignReason, setReassignReason] = useState("");
  const [payForm, setPayForm] = useState({ amount: "", date: "", reference: "", note: "" });
  const [payOpen, setPayOpen] = useState(false);
  const [editOpen, setEditOpen] = useState(false);
  const [editForm, setEditForm] = useState({
  name: project.name,
  description: project.description ?? "",
  status: project.status as ProjectStatus,
  priority: project.priority as Priority,
  dueDate: project.dueDate,
});
  const [dragging, setDragging] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const client = clients.find(c => c.id === project.clientId);
  const architect = staff.find(s => s.id === project.architectId);
  const supervisor = staff.find(s => s.id === project.supervisorId);
  const architects = staff.filter(s => s.role === "ARCHITECT");
  const projectLogs = logs.filter(l => l.projectId === project.id).sort((a,b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const projectComments = comments.filter(c => c.projectId === project.id);
  const projectPayments = payments.filter(p => p.projectId === project.id);
  const projectDocuments = documents.filter(d => d.projectId === project.id);

  function handleReassign() {
    if (!reassignTo) return;
    reassignProject(project.id, reassignTo, reassignReason);
    setReassignOpen(false); setReassignTo(""); setReassignReason("");
  }

  function handlePayment(e: React.FormEvent) {
  e.preventDefault();

  const amount = Number(payForm.amount);

  if (!amount || amount <= 0) {
    alert("Please enter a valid payment amount.");
    return;
  }

  if (!payForm.date) {
    alert("Please select the payment date.");
    return;
  }

  const currentOutstanding = Math.max(
    Number(project.budget || 0) -
      Number(project.paid || 0),
    0
  );

  if (currentOutstanding <= 0) {
    alert("This project has no outstanding balance.");
    return;
  }

  if (amount > currentOutstanding) {
    alert(
      `Payment cannot exceed the outstanding contract balance of ${formatKsh(
        currentOutstanding
      )}.`
    );
    return;
  }

  addPayment({
    projectId: project.id,
    amount,
    date: payForm.date,
    reference: payForm.reference,
    note: payForm.note,
  });

  setPayOpen(false);

  setPayForm({
    amount: "",
    date: "",
    reference: "",
    note: "",
  });
}

  function handleEdit(e: React.FormEvent) {
    e.preventDefault();
    updateProject(project.id, editForm);
    setEditOpen(false);
  }

  async function handleArchiveProject() {
    if (!confirm(`Archive project "${project.name}"? It'll be hidden from the active projects list, but its logs, documents, comments and payments are kept and can be restored later.`)) return;
    await removeProject(project.id);
    router.push("/projects");
  }

  async function handleFiles(list: FileList | null) {
    if (!list || list.length === 0) return;
    setUploadError("");
    setUploading(true);
    try {
      for (const file of Array.from(list)) {
        await uploadDocument(project.id, file);
      }
    } catch (e) {
      setUploadError((e as Error).message || "Upload failed");
    } finally {
      setUploading(false);
    }
  }

  async function handleDeleteDoc(docId: string, name: string) {
    if (!confirm(`Delete "${name}"?`)) return;
    await removeDocument(docId);
  }

  const contractValue = Number(project.budget || 0);
const invoiced = Number(project.invoiced || 0);
const paid = Number(project.paid || 0);

const financialProgress =
  calculateFinancialProgress({
    contractValue: project.budget,
    invoiced: project.invoiced,
    paid: project.paid,
  });

const outstanding =
  financialProgress.outstanding;

const collectedPercentage =
  financialProgress.collectedPercentage;

const invoicedPercentage =
  contractValue > 0
    ? Math.min(Math.round((invoiced / contractValue) * 100), 100)
    : 0;

const paidPercentage =
  contractValue > 0
    ? Math.min(Math.round((paid / contractValue) * 100), 100)
    : 0;

const outstandingPercentage =
  contractValue > 0
    ? Math.min(Math.round((outstanding / contractValue) * 100), 100)
    : 0;
  const statusColor = project.status === "ON_TRACK" ? "#2F7A5E" : project.status === "AT_RISK" ? "#B07F1F" : "#B5502E";

  return (
    <AppShell>
      <div>
        {/* Header */}
        <div className="flex items-start justify-between mb-4 gap-4">
          <div>
            <div className="font-mono text-[11.5px] text-muted">{project.sheetNo} · {project.location}</div>
            <h1 className="font-display font-bold text-[21px] text-ink mt-0.5">{project.name}</h1>
            <p className="text-muted text-[12.5px] mt-1">{client?.name} — {client?.contactPerson}</p>
          </div>
          <div className="flex items-center gap-2 shrink-0 flex-wrap justify-end">
            <StatusPill status={project.status} className="px-2.5 py-1" />
            {canEdit && (
              <Link href={`/projects/${project.id}/takeover`} className="flex items-center gap-1.5 border border-blueprint text-blueprint rounded-md px-3 py-1.5 text-[12px] font-medium hover:bg-blueprint-bg">
                <ArrowRightLeft size={14} />Take over
              </Link>
            )}
            {canEdit && (
              <button onClick={() => setEditOpen(true)} className="flex items-center gap-1.5 border border-line text-ink rounded-md px-3 py-1.5 text-[12px] font-medium hover:bg-vellum">
                <Pencil size={14} />Edit
              </button>
            )}
            {canReassign && (
              <button onClick={() => setReassignOpen(true)} className="flex items-center gap-1.5 bg-brick text-white rounded-md px-3 py-1.5 text-[12px] font-medium hover:bg-brick/90">
                <Repeat size={14} />Reassign
              </button>
            )}
            {isAdmin && (
              <button onClick={handleArchiveProject} className="flex items-center gap-1.5 border border-line text-brick rounded-md px-3 py-1.5 text-[12px] font-medium hover:bg-brick-bg">
                <Archive size={14} />Archive
              </button>
            )}
          </div>
        </div>

        {/* Project meta */}
        <Card className="p-4 mb-4">
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4 text-[12px]">
            <div><div className="text-muted mb-1">Architect</div><div className="text-ink font-medium">{architect?.name ?? <span className="text-brick">Unassigned</span>}</div></div>
            <div><div className="text-muted mb-1">Supervisor</div><div className="text-ink font-medium">{supervisor?.name ?? "—"}</div></div>
            <div><div className="text-muted mb-1">Start date</div><div className="text-ink font-mono">{project.startDate}</div></div>
            <div><div className="text-muted mb-1">Due date</div><div className="text-ink font-mono">{project.dueDate}</div></div>
            <div><div className="text-muted mb-1">Priority</div><div className={`font-medium ${project.priority === "HIGH" ? "text-brick" : project.priority === "MEDIUM" ? "text-ochre" : "text-muted"}`}>{priorityLabel(project.priority)}</div></div>
          </div>
          <div className="mt-4 pt-3 border-t border-line">
            <div className="flex items-center justify-between mb-1.5">
  <div>
    <div className="text-muted text-[12px]">
      Overall project progress
    </div>

    <div className="text-[10px] text-muted mt-0.5">
      Based on tasks and milestones
    </div>
  </div>

  <div
    className="font-mono text-[12px]"
    style={{ color: statusColor }}
  >
    {project.progress}%
  </div>
</div>

<div className="w-full h-2 bg-line rounded-full overflow-hidden">
  <div
    className="h-full rounded-full transition-all"
    style={{
      width: `${project.progress}%`,
      background: statusColor,
    }}
  />
</div>
          </div>
        </Card>

        {/* Tabs */}
        <div className="flex items-center gap-0 mb-4 border-b border-line overflow-x-auto">
          {tabs.map(t => {
            const Icon = t.icon;
            return (
              <button key={t.key} onClick={() => setTab(t.key)} className={`flex items-center gap-1.5 px-3.5 py-2.5 text-[12.5px] border-b-2 -mb-px whitespace-nowrap transition-colors ${tab === t.key ? "border-blueprint text-ink font-medium" : "border-transparent text-muted hover:text-ink"}`}>
                <Icon size={14} />{t.label}
                {t.key === "logs" && projectLogs.length > 0 && <span className="ml-1 bg-blueprint-bg text-blueprint text-[10px] rounded-full px-1.5 font-medium">{projectLogs.length}</span>}
                {t.key === "documents" && projectDocuments.length > 0 && <span className="ml-1 bg-blueprint-bg text-blueprint text-[10px] rounded-full px-1.5 font-medium">{projectDocuments.length}</span>}
                {t.key === "comms" && projectComments.filter(c=>!c.resolvedAt).length > 0 && <span className="ml-1 bg-brick-bg text-brick text-[10px] rounded-full px-1.5 font-medium">{projectComments.filter(c=>!c.resolvedAt).length}</span>}
              </button>
            );
          })}
        </div>

        {/* Overview */}
        {tab === "overview" && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
            <Card className="p-4">
              <div className="font-medium text-ink text-[13px] mb-2">Project description</div>
              <p className="text-[12.5px] text-muted leading-relaxed">{project.description}</p>
              {(project.assignmentHistory?.length ?? 0) > 0 && (
                <div className="mt-4 pt-4 border-t border-line">
                  <div className="font-medium text-ink text-[12px] mb-2">Reassignment history</div>
                  {(project.assignmentHistory ?? []).map(r => (
                    <div key={r.id} className="text-[11.5px] mb-2">
                      <span className="text-muted">{r.date}</span> · Reassigned from <span className="text-ink">{r.fromArchitect?.name ?? "Unassigned"}</span> to <span className="text-ink">{r.toArchitect?.name}</span>
                      {r.performedBy && <span className="text-muted"> (by {r.performedBy.name})</span>}
                      {r.reason && <div className="text-muted mt-0.5 italic">{r.reason}</div>}
                    </div>
                  ))}
                </div>
              )}
            </Card>
            <Card className="p-4">
  <div className="font-medium text-ink text-[13px] mb-2">
    Financial snapshot
  </div>

  <div className="grid grid-cols-2 gap-3 text-[12px]">
    <div>
      <div className="text-muted mb-0.5">
        Contract value
      </div>

      <div className="font-mono text-ink">
        {formatKsh(financialProgress.contractValue)}
      </div>
    </div>

    <div>
      <div className="text-muted mb-0.5">
        Invoiced
      </div>

      <div className="font-mono text-ink">
        {formatKsh(financialProgress.invoiced)}
      </div>

      <div className="text-[10px] text-muted mt-0.5">
        {invoicedPercentage.toFixed(2)}% of contract
      </div>
    </div>

    <div>
      <div className="text-muted mb-0.5">
        Paid
      </div>

      <div className="font-mono text-moss">
        {formatKsh(financialProgress.paid)}
      </div>

      <div className="text-[10px] text-moss mt-0.5">
        {collectedPercentage.toFixed(2)}% collected
      </div>
    </div>

    <div>
      <div className="text-muted mb-0.5">
        Outstanding
      </div>

      <div className="font-mono text-brick">
        {formatKsh(financialProgress.outstanding)}
      </div>

      <div className="text-[10px] text-brick mt-0.5">
        {(100 - collectedPercentage).toFixed(2)}% remaining
      </div>
    </div>
  </div>

  <div className="mt-3 pt-3 border-t border-line">
    <div className="flex items-center justify-between mb-1">
      <span className="text-[11px] text-muted">
        Payment collection
      </span>

      <span className="text-[11px] font-mono text-moss">
        {collectedPercentage.toFixed(2)}%
      </span>
    </div>

    <div className="w-full h-2 bg-line rounded-full overflow-hidden">
      <div
        className="h-full bg-moss rounded-full transition-all"
        style={{
          width: `${collectedPercentage}%`,
        }}
      />
    </div>

    <div className="flex items-center justify-between text-[10.5px] mt-1">
      <span className="text-muted">
        {formatKsh(financialProgress.paid)} received
      </span>

      <span className="text-brick">
        {formatKsh(financialProgress.outstanding)} remaining
      </span>
    </div>
  </div>
</Card>
          </div>
        )}

        {/* Daily logs */}
        {tab === "logs" && (
          <div className="flex flex-col gap-3">
            {projectLogs.length === 0 && <Card className="p-8 text-center text-muted text-[12.5px]">No daily logs submitted for this project yet.</Card>}
            {projectLogs.map(log => {
              const author = staff.find(s => s.id === log.authorId);
              return (
                <Card key={log.id} className="p-4">
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <Avatar avatarUrl={author?.avatarUrl} initials={author?.initials} name={author?.name} size={28} fontSize={10} />
                      <div>
                        <div className="text-ink font-medium text-[12.5px]">{author?.name}</div>
                        <div className="text-muted text-[11px]">{log.date}</div>
                      </div>
                    </div>
                    <div className="font-mono text-[12px]" style={{color:"#2451C4"}}>{log.progress}% complete</div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-[12px]">
                    <div><div className="text-muted mb-1 text-[11px] uppercase tracking-wide">Work completed</div><p className="text-ink leading-relaxed">{log.workCompleted}</p></div>
                    <div><div className="text-muted mb-1 text-[11px] uppercase tracking-wide">Challenges</div><p className="text-ink leading-relaxed">{log.challenges}</p></div>
                    <div><div className="text-muted mb-1 text-[11px] uppercase tracking-wide">Pending</div><p className="text-ink leading-relaxed">{log.pendingWork}</p></div>
                    <div><div className="text-muted mb-1 text-[11px] uppercase tracking-wide">Next actions</div><p className="text-ink leading-relaxed">{log.nextActions}</p></div>
                  </div>
                </Card>
              );
            })}
          </div>
        )}

        {/* Documents */}
        {tab === "documents" && (
          <div className="flex flex-col gap-3">
            <input ref={fileInputRef} type="file" multiple className="hidden" onChange={e => { handleFiles(e.target.files); e.target.value = ""; }} />
            <Card
              className={`p-8 text-center cursor-pointer transition-colors ${dragging ? "border-blueprint bg-blueprint-bg" : ""}`}
              onClick={() => fileInputRef.current?.click()}
              onDragOver={e => { e.preventDefault(); setDragging(true); }}
              onDragLeave={() => setDragging(false)}
              onDrop={e => { e.preventDefault(); setDragging(false); handleFiles(e.dataTransfer.files); }}
            >
              <Upload size={24} className="mx-auto text-muted mb-3" />
              <div className="text-ink font-medium text-[13px]">{uploading ? "Uploading…" : dragging ? "Drop files here" : "Drag and drop drawings or documents"}</div>
              <p className="text-muted text-[12px] mt-1">Supports DWG, DXF, Revit, PDF, images, BOQs, contracts and reports (up to 50MB).</p>
              <button type="button" onClick={e => { e.stopPropagation(); fileInputRef.current?.click(); }} className="mt-3 bg-ink text-white rounded-md px-4 py-2 text-[12px] font-medium">Browse files</button>
            </Card>
            {uploadError && <p className="text-brick text-[12px]">{uploadError}</p>}

            {projectDocuments.length === 0 ? (
              <Card className="p-6 text-center text-muted text-[12.5px]">No documents uploaded for this project yet.</Card>
            ) : (
              <Card className="divide-y divide-line overflow-hidden">
                {projectDocuments.map(d => (
                  <div key={d.id} className="flex items-center justify-between px-4 py-3">
                    <div className="flex items-center gap-2.5 min-w-0">
                      <FileIcon size={16} className="text-muted shrink-0" />
                      <div className="min-w-0">
                        <div className="text-ink font-medium text-[12.5px] truncate">{d.name}</div>
                        <div className="text-muted text-[11px] font-mono">{formatFileSize(d.fileSize)} · {new Date(d.uploadedAt).toLocaleDateString()}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-3 shrink-0">
                      <button
                        onClick={() => toggleDocumentVisibility(d.id, !d.clientVisible)}
                        className={`flex items-center gap-1 text-[11px] px-1.5 py-0.5 rounded-[3px] font-medium ${d.clientVisible ? "bg-moss-bg text-moss" : "text-muted hover:text-ink"}`}
                        title={d.clientVisible ? "Visible to client in the Client Portal — click to hide" : "Not visible to client — click to share via Client Portal"}
                      >
                        {d.clientVisible ? <Eye size={13} /> : <EyeOff size={13} />}
                        {d.clientVisible ? "Client can see" : "Not shared"}
                      </button>
                      <a href={d.fileUrl} download={d.name} className="text-blueprint hover:text-blueprint/70" title="Download"><Download size={15} /></a>
                      <button onClick={() => handleDeleteDoc(d.id, d.name)} className="text-muted hover:text-brick" title="Delete"><Trash2 size={15} /></button>
                    </div>
                  </div>
                ))}
              </Card>
            )}
          </div>
        )}

        {/* Client comms */}
        {tab === "comms" && (
          <div className="flex flex-col gap-3">
            {projectComments.length === 0 && <Card className="p-8 text-center text-muted text-[12.5px]">No client communications recorded for this project.</Card>}
            {projectComments.map(c => (
              <Card key={c.id} className={`p-4 ${c.resolvedAt ? "opacity-60" : ""}`}>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1.5">
                      <span className="text-ink font-medium text-[13px]">{c.author}</span>
                      <span className={`text-[10px] px-1.5 py-0.5 rounded-[3px] font-medium ${c.type === "CHANGE_REQUEST" ? "bg-brick-bg text-brick" : c.type === "APPROVAL" ? "bg-moss-bg text-moss" : c.type === "QUERY" ? "bg-blueprint-bg text-blueprint" : "bg-ochre-bg text-ochre"}`}>{commentTypeLabel(c.type)}</span>
                    </div>
                    <p className="text-[12.5px] text-ink leading-relaxed">{c.content}</p>
                    <div className="text-[11px] text-muted mt-2 font-mono">
                      {new Date(c.createdAt).toLocaleString("en-KE", { dateStyle: "medium", timeStyle: "short" })}
                      {c.resolvedAt && <span className="ml-3 text-moss">✓ Resolved</span>}
                    </div>
                  </div>
                  {!c.resolvedAt && (
                    <button onClick={() => resolveComment(c.id)} className="flex items-center gap-1 text-[11px] text-moss border border-moss/30 rounded px-2 py-1 hover:bg-moss-bg shrink-0">
                      <CheckCircle size={12} />Resolve
                    </button>
                  )}
                </div>
              </Card>
            ))}
          </div>
        )}

        {/* Finance */}
        {tab === "finance" && (
  <div className="flex flex-col gap-3">

    {/* FINANCIAL SUMMARY */}
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3">

      {/* CONTRACT */}
      <Card className="p-3.5">
        <div className="text-muted text-[11px]">
          Contract value
        </div>

        <div className="font-mono font-medium text-[16px] text-ink mt-1">
          {formatKsh(contractValue)}
        </div>

        <div className="text-[10.5px] text-muted mt-1">
          100% contract value
        </div>
      </Card>

      {/* INVOICED */}
      <Card className="p-3.5">
        <div className="text-muted text-[11px]">
          Invoiced
        </div>

        <div className="font-mono font-medium text-[16px] text-ink mt-1">
          {formatKsh(invoiced)}
        </div>

        <div className="text-[10.5px] text-blueprint mt-1">
          {invoicedPercentage}% of contract
        </div>
      </Card>

      {/* PAID */}
      <Card className="p-3.5">
        <div className="text-muted text-[11px]">
          Paid
        </div>

        <div className="font-mono font-medium text-[16px] text-moss mt-1">
          {formatKsh(paid)}
        </div>

        <div className="text-[10.5px] text-moss mt-1">
          {paidPercentage}% collected
        </div>
      </Card>

      {/* OUTSTANDING */}
      <Card
        className="p-3.5 cursor-pointer hover:border-moss transition-colors"
        onClick={() => setPayOpen(true)}
      >
        <div className="text-muted text-[11px]">
          Outstanding
        </div>

        <div className="font-mono font-medium text-[16px] text-brick mt-1">
          {formatKsh(outstanding)}
        </div>

        <div className="text-[10.5px] text-brick mt-1">
          {outstandingPercentage}% outstanding
        </div>
      </Card>

    </div>

    {/* PAYMENT PROGRESS */}
    <Card className="p-4">

      <div className="flex items-center justify-between mb-2">
        <div className="font-medium text-ink text-[12.5px]">
          Payment progress
        </div>

        <div className="font-mono text-[11px] text-moss">
          {paidPercentage}% collected
        </div>
      </div>

      <div className="w-full h-2.5 bg-line rounded-full overflow-hidden">
        <div
          className="h-full bg-moss rounded-full transition-all"
          style={{
            width: `${paidPercentage}%`,
          }}
        />
      </div>

      <div className="flex items-center justify-between mt-2">
        <div className="text-[10.5px] text-muted">
          Received: {formatKsh(paid)}
        </div>

        <div className="text-[10.5px] text-brick">
          Outstanding: {formatKsh(outstanding)}
        </div>
      </div>

    </Card>

    {/* PAYMENT HISTORY */}
    <Card className="overflow-hidden">

      <div className="px-4 py-3 border-b border-line flex items-center justify-between">

        <div className="font-medium text-ink text-[12.5px]">
          Payment history
        </div>

        <button
          onClick={() => setPayOpen(true)}
          className="text-[11.5px] text-moss font-medium"
        >
          + Record payment
        </button>

      </div>

      {projectPayments.length === 0 ? (
        <div className="p-6 text-center text-muted text-[12.5px]">
          No payments recorded yet.
        </div>
      ) : (
        projectPayments.map(pay => (
          <div
            key={pay.id}
            className="px-4 py-3 border-t border-line flex items-center justify-between"
          >
            <div>
              <div className="text-ink text-[12.5px] font-medium">
                {pay.note || "Payment"}
              </div>

              <div className="text-muted text-[11.5px] font-mono mt-0.5">
                {pay.reference || "No reference"} · {pay.date}
                {pay.recordedBy &&
                  ` · recorded by ${pay.recordedBy.name}`}
              </div>
            </div>

            <div className="font-mono text-moss font-medium">
              {formatKsh(pay.amount)}
            </div>
          </div>
        ))
      )}

    </Card>

  </div>
)}

        {/* Reassign Modal */}
        <Modal open={reassignOpen} onClose={() => setReassignOpen(false)} title="Reassign project" subtitle="New architect gets instant access to all project history">
          <div className="flex flex-col gap-3.5">
            <div className="bg-vellum rounded-md p-3 text-[12.5px]">
              <div className="text-muted">Currently assigned to</div>
              <div className="text-ink font-medium mt-0.5">{architect?.name ?? <span className="text-brick">Unassigned</span>}</div>
            </div>
            <Field label="Reassign to" required>
              <Select value={reassignTo} onChange={e => setReassignTo(e.target.value)}>
                <option value="">Select architect</option>
                {architects.filter(a => a.id !== project.architectId).map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
              </Select>
            </Field>
            <Field label="Reason">
              <Textarea rows={2} value={reassignReason} onChange={e => setReassignReason(e.target.value)} placeholder="Reason for reassignment…" />
            </Field>
            <div className="flex justify-end gap-2 pt-1 border-t border-line">
              <button onClick={() => setReassignOpen(false)} className="px-4 py-2 rounded-md text-[12.5px] border border-line text-muted">Cancel</button>
              <button onClick={handleReassign} disabled={!reassignTo} className="px-4 py-2 rounded-md text-[12.5px] bg-brick text-white font-medium disabled:opacity-50">Confirm</button>
            </div>
          </div>
        </Modal>

        {/* Edit Project Modal */}
        <Modal open={editOpen} onClose={() => setEditOpen(false)} title="Edit project" maxWidth="max-w-xl">
          <form onSubmit={handleEdit} className="flex flex-col gap-3.5">
            <Field label="Project name" required><Input required value={editForm.name} onChange={e => setEditForm(f=>({...f,name:e.target.value}))} /></Field>
            <Field label="Description"><Textarea rows={3} value={editForm.description} onChange={e => setEditForm(f=>({...f,description:e.target.value}))} /></Field>
            <FormRow>
              <Field label="Status">
                <Select value={editForm.status} onChange={e => setEditForm(f=>({...f,status:e.target.value as ProjectStatus}))}>
                  <option value="ON_TRACK">On track</option>
                  <option value="AT_RISK">At risk</option>
                  <option value="DELAYED">Delayed</option>
                  <option value="COMPLETED">Completed</option>
                </Select>
              </Field>
              <Field label="Priority">
                <Select value={editForm.priority} onChange={e => setEditForm(f=>({...f,priority:e.target.value as Priority}))}>
                  <option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option>
                </Select>
              </Field>
            </FormRow>
            <div className="grid grid-cols-1 gap-3">
  <div className="rounded-md border border-line bg-vellum px-3 py-2.5">
    <div className="text-[11px] text-muted">
      Project progress
    </div>

    <div className="text-[12.5px] text-ink font-medium mt-0.5">
      Automatically calculated from tasks and milestones
    </div>

    <div className="text-[10.5px] text-muted mt-0.5">
      Update task completion or milestone status to change the
      overall project progress.
    </div>
  </div>

  <Field label="Due date">
    <Input
      type="date"
      value={editForm.dueDate}
      onChange={e =>
        setEditForm(f => ({
          ...f,
          dueDate: e.target.value
        }))
      }
    />
  </Field>
</div>
            <div className="flex justify-end gap-2 pt-1 border-t border-line mt-1">
              <button type="button" onClick={() => setEditOpen(false)} className="px-4 py-2 rounded-md text-[12.5px] border border-line text-muted">Cancel</button>
              <button type="submit" className="px-4 py-2 rounded-md text-[12.5px] bg-ink text-white font-medium">Save changes</button>
            </div>
          </form>
        </Modal>

        {/* Payment Modal */}
        <Modal open={payOpen} onClose={() => setPayOpen(false)} title="Record payment">
          <form onSubmit={handlePayment} className="flex flex-col gap-3.5">
            <Field label="Amount (KSh)" required><input required type="number" value={payForm.amount} onChange={e=>setPayForm(f=>({...f,amount:e.target.value}))} className="w-full border border-line rounded-md px-3 py-2 text-[13px] bg-surface text-ink outline-none focus:border-blueprint" placeholder="e.g. 2500000" /></Field>
            <Field label="Payment date" required><input required type="date" value={payForm.date} onChange={e=>setPayForm(f=>({...f,date:e.target.value}))} className="w-full border border-line rounded-md px-3 py-2 text-[13px] bg-surface text-ink outline-none focus:border-blueprint" /></Field>
            <Field label="Reference"><input value={payForm.reference} onChange={e=>setPayForm(f=>({...f,reference:e.target.value}))} className="w-full border border-line rounded-md px-3 py-2 text-[13px] bg-surface text-ink outline-none focus:border-blueprint" placeholder="e.g. INV-A101-003" /></Field>
            <Field label="Note"><textarea rows={2} value={payForm.note} onChange={e=>setPayForm(f=>({...f,note:e.target.value}))} className="w-full border border-line rounded-md px-3 py-2 text-[13px] bg-surface text-ink outline-none focus:border-blueprint resize-none" placeholder="e.g. Second stage payment" /></Field>
            <div className="flex justify-end gap-2 pt-1 border-t border-line">
              <button type="button" onClick={() => setPayOpen(false)} className="px-4 py-2 rounded-md text-[12.5px] border border-line text-muted">Cancel</button>
              <button type="submit" className="px-4 py-2 rounded-md text-[12.5px] bg-moss text-white font-medium">Record payment</button>
            </div>
          </form>
        </Modal>
      </div>
    </AppShell>
  );
}

'@
Write-PatchFile "src/app/projects/[id]/page.tsx" $content

Write-Host ""
Write-Host "Patch 44 applied. Run:" -ForegroundColor Green
Write-Host "  npm run build"
Write-Host "Toggle to dark mode and check any form -- input text should be clearly visible now." -ForegroundColor Green
