<#
  Architect Hub -- patch 55: likely the ACTUAL root cause of
  "Connection terminated unexpectedly" across the whole app -- webpack
  was corrupting the ws package during bundling.
  Generated by Claude -- 2026-08-29

  Your server log for the notifications failure contained a second,
  completely different error I hadn't seen before:
  "TypeError: b.mask is not a function". This isn't from your app code
  at all -- it's from inside the ws (WebSocket) library itself, and
  it's a known, documented consequence of webpack bundling low-level
  binary-protocol libraries like ws: webpack's module wrapping breaks
  how the library references its own internal frame-masking function
  (a required part of the WebSocket protocol for every message sent).

  This likely explains far more than just notifications: ws's masking
  runs on every WebSocket frame the Neon adapter's Pool connection
  sends. A broken mask function would intermittently break ANY query
  still going through that path -- which is most of them, since
  poolQueryViaFetch only ever covered the simplest ones. The
  transaction removals and query-flattening from earlier patches were
  real, necessary fixes for their own specific causes, but this may
  well have been an additional, separate problem compounding all of it
  the whole time.

  Timeline that fits exactly: this surfaced only after patch 35 forced
  the `--webpack` build flag to fix the earlier EAGAIN crash --
  Turbopack apparently handled the ws package differently, which is
  why this specific failure mode never showed up before that switch.

  FIX: added serverExternalPackages to next.config.js, telling
  Next.js's webpack build to leave ws (and the two Neon packages built
  on it) completely unbundled -- loaded as genuine Node.js require()
  calls against the real files in node_modules at runtime, instead of
  webpack's mangled bundle. Confirmed this is a real, current,
  top-level Next.js config option by checking the actual type
  definitions in your installed Next.js package (not just
  documentation) -- not guessed or copied from an older version's API.

  Config verified to actually load with the correct value (not just
  "no syntax error"), lint clean, 62/62 tests on your machine (same 3
  sandbox-only failures here, confirmed unrelated in every earlier
  patch).

  WHAT TO TEST after this deploys: everything, honestly -- but
  especially anything that felt flaky/intermittent before rather than
  consistently broken, since a slow-then-fail WebSocket issue would
  show up that way. Notifications specifically should now work.

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-55.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$content = @'
/** @type {import('next').NextConfig} */
const isProd = process.env.NODE_ENV === "production";

// Derived from the same env vars src/lib/s3.ts actually uses, so this
// always matches whatever bucket/region is really configured at deploy
// time -- a hardcoded guess here would silently break every document
// thumbnail and avatar in production the moment it didn't match the
// real bucket, and (like the CSP itself) nothing in dev would ever
// reveal that mismatch since this header is skipped in dev entirely.
const s3ImgSrc =
  process.env.AWS_S3_BUCKET && process.env.AWS_REGION
    ? `https://${process.env.AWS_S3_BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com`
    : ""; // S3 not configured -- falls back to local disk storage, nothing to allowlist

const nextConfig = {
  reactStrictMode: true,
  // Prevents webpack from bundling ws (and the Neon packages built on
  // it) into the server bundle at all -- keeps them as genuine Node.js
  // require() calls against the real node_modules files instead.
  // Fixes a confirmed, specific error seen in production:
  // "TypeError: b.mask is not a function", a known consequence of
  // webpack mangling ws's internal WebSocket frame-masking code when
  // it gets bundled -- documented as a real issue with this exact
  // symptom for low-level binary/protocol libraries like this one.
  // This almost certainly explains the broader "Connection terminated
  // unexpectedly" pattern seen across many routes, not just
  // notifications -- ws's masking is required for every WebSocket
  // frame the Neon adapter's Pool connection sends, so a broken mask
  // function would intermittently break any query still going through
  // that path (which is most of them; poolQueryViaFetch only covers
  // the simplest ones). Only relevant on the `--webpack` build path
  // (see the build script in package.json) -- Turbopack apparently
  // handled this package differently, which is why this didn't
  // surface until the EAGAIN fix forced webpack specifically.
  serverExternalPackages: ["ws", "@neondatabase/serverless", "@prisma/adapter-neon"],
  // Type errors are already caught by CI (.github/workflows/ci.yml
  // runs `npx tsc --noEmit` as a dedicated step on every push) before
  // this code is ever deployed -- redoing it during the production
  // build here is genuinely redundant, and it spawns its own
  // jest-worker child process (see the cpus/workerThreads comment
  // below for why that matters specifically on resource-constrained
  // shared hosting). This is the standard, documented way to skip it
  // -- NOT a way to let real type errors slip through, since CI still
  // blocks on them.
  //
  // NOTE: there was also an `eslint: { ignoreDuringBuilds: true }` key
  // here -- removed. Next.js 16 no longer supports ESLint
  // configuration inside next.config.js at all (confirmed by an
  // "Unrecognized key(s): 'eslint'" warning in an actual build on this
  // version) -- it was being silently ignored, not doing anything.
  // Next.js's production build doesn't run ESLint at all in this
  // version regardless, so there's nothing to disable here; CI's
  // `npm run lint` step remains the real lint gate either way.
  typescript: { ignoreBuildErrors: true },
  // "standalone" output is what the Dockerfile (Railway/self-hosted
  // path) needs -- it produces a self-contained server.js with only the
  // dependencies each route actually uses. Vercel has its own packaging
  // system for serverless functions and doesn't want this: combined
  // with Vercel's build, it causes exactly the "Failed to collect page
  // data" error on API routes that touch Prisma. process.env.VERCEL is
  // set automatically by Vercel's build environment, so this correctly
  // targets each platform's own expectations without needing a manual
  // toggle.
  // "standalone" output is what the Dockerfile (Railway/self-hosted
  // path) needs. Vercel doesn't want it (see comment above). Shared
  // hosting environments with a managed Node.js app runner (e.g.
  // HostAfrica's DirectAdmin Node.js Selector) generally expect a plain
  // `next start` too -- standalone mode's server.js needs the static
  // assets and public folder manually copied alongside it (that's what
  // the Dockerfile's explicit COPY steps do), which most managed
  // Node.js hosting panels have no built-in way to do. Set
  // DISABLE_STANDALONE_BUILD=true on that kind of host to get a normal
  // build instead.
  ...(process.env.VERCEL || process.env.DISABLE_STANDALONE_BUILD === "true"
    ? {}
    : { output: "standalone" }),
  experimental: {
    serverActions: { allowedOrigins: ["localhost:3000"] },
    // Fixes "Error: EAGAIN ... ERR_WORKER_INIT_FAILED" during the build
    // step specifically on resource-constrained shared hosting (cPanel/
    // CloudLinux CageFS, like HostPinnacle) -- Next.js spawns many
    // parallel worker threads by default to speed up builds, which
    // exceeds the process/thread limit CageFS enforces per account.
    // Forces a single-threaded build instead. Applied everywhere, not
    // just conditionally for that host -- costs a little build time on
    // platforms with ample resources (Vercel/Railway), in exchange for
    // one fewer thing that can silently differ between environments.
    workerThreads: false,
    cpus: 1,
  },
  async headers() {
    if (!isProd) return []; // don't apply CSP/HSTS in dev — breaks HMR/Fast Refresh

    const csp = [
      "default-src 'self'",
      // 'unsafe-inline' is required here -- Next.js's App Router injects
      // inline hydration scripts (self.__next_f.push(...)) into every
      // page. Without this, a browser enforcing this CSP blocks those
      // scripts and the app fails to hydrate at all -- blank page,
      // nothing interactive. This CSP header only activates in
      // production (see isProd above), so this had never actually been
      // exercised until now; dev mode always skips it.
      //
      // The "correct" alternative is a per-request nonce generated in
      // middleware instead of 'unsafe-inline'. That's deliberately NOT
      // done here: as of this Next.js version, nonce-based CSP is
      // broken specifically for the Turbopack + output:"standalone"
      // combination this app uses -- Next's own injected scripts don't
      // receive the nonce at all, so the app breaks the same way either
      // way. 'unsafe-inline' is also Next.js's own documented
      // recommendation for apps not implementing per-request nonces.
      // Revisit once that upstream bug is fixed.
      "script-src 'self' 'unsafe-inline'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data:" + (s3ImgSrc ? ` ${s3ImgSrc}` : ""),
      "font-src 'self' data:",
      "connect-src 'self'",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "object-src 'none'",
    ].join("; ");

    return [
      {
        source: "/(.*)",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
        ],
      },
    ];
  },
};
module.exports = nextConfig;
'@
[System.IO.File]::WriteAllText((Join-Path (Get-Location) "next.config.js"), $content, $utf8NoBom)
Write-Host "wrote next.config.js" -ForegroundColor Green
Write-Host ""
Write-Host "Patch 55 applied. Now:" -ForegroundColor Cyan
Write-Host "  git add ."
Write-Host "  git commit -m ""Fix ws library corruption from webpack bundling (likely root cause)"""
Write-Host "  git push origin main"
Write-Host ""
Write-Host "This could be the single biggest fix yet -- test everything once it's live." -ForegroundColor Yellow
