<#
  Architect Hub -- patch 50: fixes the CI variable-collision crash, AND
  extends the nested-select fix to payments and invoices -- WITHOUT
  touching the interactive transaction logic itself.
  Generated by Claude -- 2026-08-28

  1. THE CI CRASH: my new response-fetching variables in
     src/app/api/projects/route.ts (client/architect/supervisor) had
     the exact same names as EXISTING validation variables earlier in
     the same function -- a genuine redeclaration bug TypeScript
     correctly caught. Renamed the new ones (responseClient,
     responseArchitect, responseSupervisor).

  2. PAYMENTS AND INVOICES: applied the same flat-query fix as
     projects, but IMPORTANT -- the $transaction() wrapper itself is
     completely untouched in both files. Only the QUERIES INSIDE it
     were flattened:
       - tx.payment.create()'s select had a nested project/recordedBy
         -- now flat; the notification message and final response
         reconstruct the same data from updatedProject (already
         fetched, just added two scalar fields: name, sheetNo) and
         session.user -- no extra queries needed at all.
       - Both GET handlers (payment/invoice history) had a relational
         `where: { project: projectWhere }` filter (a join) AND nested
         selects. Converted to: first resolve accessible project IDs
         via a flat query, then filter with `projectId: { in: [...] }`
         (no join), then batch-fetch related projects/users separately
         and stitch into the same response shape.

  WHY THIS IS SAFE: the actual overpayment-prevention logic (re-reading
  current state fresh inside the transaction, checking against it,
  throwing if it would exceed budget) is character-for-character
  unchanged. Only the SHAPE of unrelated queries changed -- what data
  they select, not the transaction boundary or the business logic
  inside it. This sidesteps the whole "does HTTP mode support
  interactive transactions" question entirely, since nothing about how
  the transaction runs was touched.

  Caught and fixed a typo I introduced while writing this (a stray
  non-ASCII character in a variable name) via lint, before it ever
  reached you.

  Lint clean on all three files, grepped for any remaining nested
  relation selects in either payments or invoices (only found the
  correct, expected plain-object response construction, not a query),
  62/62 tests on your machine (same 3 sandbox-only failures here,
  confirmed unrelated in every earlier patch).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-50.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 50 (payments/invoices fix + CI crash fix)..." -ForegroundColor Cyan

# --- [MOD] src/app/api/projects/route.ts ---
$content = @'
import { notifyProjectAssignment } from "@/lib/notifications";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { Priority } from "@prisma/client";
import { z } from "zod";
import {
  projectAccessWhere,
  canCreateProjects,
  isAdmin,
} from "@/lib/rbac";
import { generateProjectSheetNo } from "@/lib/project-number";
import { logActivity } from "@/lib/activity-log";
import { calculateProjectProgress } from "@/lib/project-progress";

const CreateProjectSchema = z.object({
  name: z.string().min(2),
  clientId: z.string().min(1),
  location: z.string().min(2),
  description: z.string().optional(),

  // Assignment is optional at creation -- lets an admin/senior architect
  // stand up a project and assign staff to it later, rather than being
  // forced to pick someone before the project can even exist.
  architectId: z.string().min(1).optional(),
  supervisorId: z.string().min(1).optional(),

  startDate: z.string(),
  dueDate: z.string(),

  budget: z.number().min(0),

  priority: z.enum(["LOW", "MEDIUM", "HIGH"]),
});

/**
 * GET /api/projects
 *
 * Returns projects accessible to the authenticated user.
 *
 * IMPORTANT SECURITY RULES:
 *
 * ADMIN:
 * - Can access financial project information.
 * - Can view archived projects.
 *
 * ARCHITECT:
 * - Can only access projects allowed by projectAccessWhere().
 * - NEVER receives budget, invoiced, or paid.
 * - NEVER receives client passwordHash.
 *
 * FINANCIAL SOURCE OF TRUTH:
 *
 * - budget    = Project.budget
 * - invoiced  = Project.invoiced
 * - paid      = SUM(Payment.amount)
 *
 * We deliberately calculate `paid` from Payment records instead
 * of trusting Project.paid because individual payment records are
 * the authoritative transaction history.
 */
export async function GET(req: NextRequest) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const admin = isAdmin(session);

  // Admin-only archived project mode.
  const wantsArchived =
    req.nextUrl.searchParams.get("archived") === "true";

  if (wantsArchived && !admin) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  try {
    const projects = await prisma.project.findMany({
      where: {
        AND: [
          projectAccessWhere(session),
          {
            archivedAt: wantsArchived
              ? { not: null }
              : null,
          },
        ],
      },

      /*
       * SECURITY:
       *
       * We deliberately use `select` instead of unrestricted
       * `include` so sensitive fields cannot accidentally leak.
       *
       * Deliberately FLAT here -- no nested relation selects
       * (client, architect, supervisor, payments, tasks, milestones,
       * _count) like this used to have. On HostPinnacle specifically,
       * queries with nested relation selects were failing with
       * "Connection terminated unexpectedly" even with
       * neonConfig.poolQueryViaFetch enabled -- that setting only
       * reliably covers genuinely simple, flat, single-table queries.
       * Every one of those is fetched separately below instead, as
       * batched flat queries (one findMany with an `in` filter per
       * relation, not one query per project), then stitched back
       * together into the exact same response shape as before.
       */
      select: {
        id: true,
        name: true,
        sheetNo: true,
        location: true,
        description: true,

        status: true,
        priority: true,

        startDate: true,
        dueDate: true,
        completionDate: true,

        clientId: true,
        architectId: true,
        supervisorId: true,

        archivedAt: true,
        archiveReason: true,
        archivedById: true,
        restoredAt: true,
        restoredById: true,

        createdAt: true,
        updatedAt: true,

        /*
         * FINANCIAL DATA
         *
         * Only ADMIN receives financial information.
         *
         * `paid` is intentionally NOT selected from Project.
         * Instead, actual paid amount is calculated below from
         * the separately-fetched Payment records.
         */
        ...(admin
          ? {
              budget: true,
              invoiced: true,
            }
          : {}),
      },

      orderBy: {
        createdAt: "desc",
      },
    });

    const projectIds = projects.map((p) => p.id);

    const clientIds = [...new Set(projects.map((p) => p.clientId))];
    const userIds = [
      ...new Set(
        projects
          .flatMap((p) => [p.architectId, p.supervisorId])
          .filter((id): id is string => Boolean(id))
      ),
    ];

    const [clients, users, payments, tasks, milestones, dailyLogCounts, documentCounts, commentCounts] =
      await Promise.all([
        prisma.client.findMany({
          where: { id: { in: clientIds } },
          select: {
            id: true,
            name: true,
            contactPerson: true,
            email: true,
            phone: true,
            address: true,
            portalEnabled: true,
            createdAt: true,
            updatedAt: true,
            lastPortalLoginAt: true,
          },
        }),
        prisma.user.findMany({
          where: { id: { in: userIds } },
          select: { id: true, name: true, initials: true, email: true, avatarUrl: true },
        }),
        admin
          ? prisma.payment.findMany({
              where: { projectId: { in: projectIds } },
              select: { projectId: true, amount: true },
            })
          : Promise.resolve([]),
        prisma.projectTask.findMany({
          where: { projectId: { in: projectIds } },
          select: { projectId: true, weight: true, completion: true, status: true },
        }),
        prisma.projectMilestone.findMany({
          where: { projectId: { in: projectIds } },
          select: { projectId: true, weight: true, status: true },
        }),
        prisma.dailyLog.findMany({
          where: { projectId: { in: projectIds } },
          select: { projectId: true },
        }),
        prisma.document.findMany({
          where: { projectId: { in: projectIds } },
          select: { projectId: true },
        }),
        prisma.clientComment.findMany({
          where: { projectId: { in: projectIds } },
          select: { projectId: true },
        }),
      ]);

    const clientById = new Map(clients.map((c) => [c.id, c]));
    const userById = new Map(users.map((u) => [u.id, u]));

    function groupByProjectId<T extends { projectId: string }>(rows: T[]) {
      const map = new Map<string, T[]>();
      for (const row of rows) {
        const list = map.get(row.projectId) ?? [];
        list.push(row);
        map.set(row.projectId, list);
      }
      return map;
    }

    const paymentsByProject = groupByProjectId(payments);
    const tasksByProject = groupByProjectId(tasks);
    const milestonesByProject = groupByProjectId(milestones);
    const dailyLogCountByProject = groupByProjectId(dailyLogCounts);
    const documentCountByProject = groupByProjectId(documentCounts);
    const commentCountByProject = groupByProjectId(commentCounts);

    /*
     * Calculate project progress and financial totals.
     *
     * IMPORTANT:
     *
     * We do NOT use Project.paid here.
     *
     * Actual paid amount is calculated from:
     *
     *     SUM(Payment.amount)
     *
     * for the project.
     */
    const projectsWithCalculatedData = projects.map(
      (project) => {
        const projectTasks = tasksByProject.get(project.id) ?? [];
        const projectMilestones = milestonesByProject.get(project.id) ?? [];

        const calculatedProgress =
          calculateProjectProgress({
            tasks: projectTasks,
            milestones: projectMilestones,
          });

        /*
         * Calculate actual payments received.
         *
         * Number(...) protects against Prisma Decimal values
         * being returned as Decimal/string-like values.
         */
        const actualPaid = admin
          ? (paymentsByProject.get(project.id) ?? []).reduce(
              (total, payment) =>
                total + Number(payment.amount || 0),
              0
            )
          : undefined;

        /*
         * Financial calculations.
         *
         * Outstanding is based on INVOICED amount,
         * not the total project budget.
         *
         * Example:
         *
         * Budget   = 5,000,000
         * Invoiced = 2,000,000
         * Paid     = 1,200,000
         *
         * Outstanding = 800,000
         * Unbilled    = 3,000,000
         */
        const financialData = admin
          ? {
              paid: actualPaid ?? 0,

              outstanding: Math.max(
                Number(project.invoiced || 0) -
                  (actualPaid ?? 0),
                0
              ),

              unbilled: Math.max(
                Number(project.budget || 0) -
                  Number(project.invoiced || 0),
                0
              ),

              remaining: Math.max(
                Number(project.budget || 0) -
                  (actualPaid ?? 0),
                0
              ),
            }
          : {};

        return {
          ...project,

          client: clientById.get(project.clientId) ?? null,
          architect: project.architectId ? (userById.get(project.architectId) ?? null) : null,
          supervisor: project.supervisorId ? (userById.get(project.supervisorId) ?? null) : null,

          _count: {
            dailyLogs: (dailyLogCountByProject.get(project.id) ?? []).length,
            documents: (documentCountByProject.get(project.id) ?? []).length,
            comments: (commentCountByProject.get(project.id) ?? []).length,
          },

          progress: calculatedProgress,

          ...financialData,
        };
      }
    );

    return NextResponse.json(
      projectsWithCalculatedData
    );
  } catch (error) {
    console.error(
      "Failed to fetch projects:",
      error
    );

    return NextResponse.json(
      {
        error:
          "Failed to load projects. Please try again.",
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/projects
 *
 * Project creation remains restricted to users allowed by
 * canCreateProjects().
 */
export async function POST(req: NextRequest) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  // Check whether the current user is allowed
  // to create projects.
  if (!canCreateProjects(session)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  // ---------------------------------------------------------
  // Read request body
  // ---------------------------------------------------------

  let body: unknown;

  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      {
        error:
          "Invalid JSON request body",
      },
      { status: 400 }
    );
  }

  // ---------------------------------------------------------
  // Validate request body
  // ---------------------------------------------------------

  const parsed =
    CreateProjectSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      {
        error:
          parsed.error.flatten(),
      },
      { status: 400 }
    );
  }

  // ---------------------------------------------------------
  // Validate assigned architect and supervisor (if provided)
  // BEFORE creating the project
  // ---------------------------------------------------------

  const [architect, supervisor] =
    await Promise.all([
      parsed.data.architectId
        ? prisma.user.findUnique({
            where: {
              id: parsed.data.architectId,
            },

            select: {
              id: true,
              role: true,
              isActive: true,
            },
          })
        : Promise.resolve(null),

      parsed.data.supervisorId
        ? prisma.user.findUnique({
            where: {
              id: parsed.data.supervisorId,
            },

            select: {
              id: true,
              role: true,
              isActive: true,
            },
          })
        : Promise.resolve(null),
    ]);

  // ---------------------------------------------------------
  // Validate architect (only if one was actually selected --
  // unassigned is allowed, invalid/inactive is not)
  // ---------------------------------------------------------

  if (
    parsed.data.architectId &&
    (!architect ||
      architect.role !== "ARCHITECT" ||
      !architect.isActive)
  ) {
    return NextResponse.json(
      {
        error:
          "Selected architect is invalid or inactive",
      },
      { status: 400 }
    );
  }

  // ---------------------------------------------------------
  // Validate supervisor (only if one was actually selected)
  // ---------------------------------------------------------

  if (
    parsed.data.supervisorId &&
    (!supervisor || !supervisor.isActive)
  ) {
    return NextResponse.json(
      {
        error:
          "Selected supervisor is invalid or inactive",
      },
      { status: 400 }
    );
  }

  // ---------------------------------------------------------
  // Verify client exists
  // ---------------------------------------------------------

  const client =
    await prisma.client.findUnique({
      where: {
        id: parsed.data.clientId,
      },

      select: {
        id: true,
      },
    });

  if (!client) {
    return NextResponse.json(
      {
        error:
          "Selected client does not exist",
      },
      { status: 400 }
    );
  }

  // ---------------------------------------------------------
  // Validate dates
  // ---------------------------------------------------------

  const startDate =
    new Date(parsed.data.startDate);

  const dueDate =
    new Date(parsed.data.dueDate);

  if (
    Number.isNaN(startDate.getTime()) ||
    Number.isNaN(dueDate.getTime())
  ) {
    return NextResponse.json(
      {
        error:
          "Invalid project date",
      },
      { status: 400 }
    );
  }

  if (dueDate < startDate) {
    return NextResponse.json(
      {
        error:
          "Project due date cannot be before the start date",
      },
      { status: 400 }
    );
  }

  // ---------------------------------------------------------
  // Generate project sheet number
  // ---------------------------------------------------------

  const sheetNo =
    await generateProjectSheetNo();

  // ---------------------------------------------------------
  // Create project
  // ---------------------------------------------------------
  //
  // Deliberately a FLAT create + select here -- no nested relation
  // selects (client:{select:{...}}, architect:{...}, supervisor:{...})
  // like this used to have. On HostPinnacle specifically, queries with
  // nested relation selects were failing with "Connection terminated
  // unexpectedly" even with neonConfig.poolQueryViaFetch enabled --
  // that setting only reliably covers genuinely simple, flat,
  // single-table queries. The nested client/architect/supervisor data
  // is fetched separately below instead, as three more flat queries,
  // then assembled into the exact same response shape the frontend
  // already expects. Slightly more round trips, but every one of them
  // is simple enough to actually succeed on this host.

  let project;

  try {
    project =
      await prisma.project.create({
        data: {
          name:
            parsed.data.name,

          clientId:
            parsed.data.clientId,

          location:
            parsed.data.location,

          description:
            parsed.data.description,

          architectId:
            parsed.data.architectId,

          supervisorId:
            parsed.data.supervisorId,

          startDate,

          dueDate,

          budget:
            parsed.data.budget,

          priority:
            parsed.data.priority as Priority,

          sheetNo,
        },

        /*
         * Explicitly select safe fields from the created
         * project instead of using client: true.
         */
        select: {
          id: true,
          name: true,
          sheetNo: true,
          location: true,
          description: true,

          status: true,
          priority: true,

          startDate: true,
          dueDate: true,
          completionDate: true,

          clientId: true,
          architectId: true,
          supervisorId: true,

          createdAt: true,
          updatedAt: true,
        },
      });
  } catch (error) {
    console.error(
      "Project creation failed:",
      error
    );

    return NextResponse.json(
      {
        error:
          "Failed to create project. Please try again.",
      },
      { status: 500 }
    );
  }

  // ---------------------------------------------------------
  // Record project creation activity
  // ---------------------------------------------------------

  try {
    await logActivity({
      action: "PROJECT_CREATED",
      entityType: "PROJECT",
      entityId: project.id,
      actorId: session.user.id,
      projectId: project.id,

      metadata: {
        projectName:
          project.name,

        sheetNo:
          project.sheetNo,

        architectId:
          project.architectId,

        supervisorId:
          project.supervisorId,

        clientId:
          project.clientId,
      },
    });
  } catch (error) {
    /*
     * Activity logging failure should not make an already
     * created project fail.
     */
    console.error(
      "Project activity logging failed:",
      error
    );
  }

  // ---------------------------------------------------------
  // Notify project creator
  // ---------------------------------------------------------

  try {
    await prisma.notification.create({
      data: {
        userId:
          session.user.id,

        message:
          `Project "${project.name}" (${sheetNo}) created successfully`,

        type:
          "SUCCESS",
      },
    });
  } catch (error) {
    /*
     * Notification failure should not make an already
     * created project fail.
     */
    console.error(
      "Project creation notification failed:",
      error
    );
  }

  // ---------------------------------------------------------
  // Prepare assignment notifications
  // ---------------------------------------------------------

  const assignees: {
    userId: string;
    role:
      | "ARCHITECT"
      | "SUPERVISOR";
  }[] = [];

  if (project.architectId) {
    assignees.push({
      userId:
        project.architectId,

      role:
        "ARCHITECT",
    });
  }

  if (project.supervisorId) {
    assignees.push({
      userId:
        project.supervisorId,

      role:
        "SUPERVISOR",
    });
  }

  // ---------------------------------------------------------
  // Notify assigned architect and supervisor
  // ---------------------------------------------------------

  await Promise.all(
    assignees
      .filter(
        (assignee) =>
          assignee.userId !==
          session.user.id
      )
      .map(async (assignee) => {
        try {
          await notifyProjectAssignment({
            userId:
              assignee.userId,

            projectId:
              project.id,

            projectName:
              `${project.name} (${sheetNo})`,

            assignedRole:
              assignee.role,

            assignedByName:
              session.user.name ??
              "A team member",
          });
        } catch (error) {
          console.error(
            `Failed to notify ${assignee.role}:`,
            error
          );
        }
      })
  );

  // ---------------------------------------------------------
  // Return created project
  // ---------------------------------------------------------
  //
  // Same three flat, single-table lookups pattern as the create call
  // above avoided doing as one nested-select query. Run in parallel
  // since they're independent of each other.

  const [responseClient, responseArchitect, responseSupervisor] = await Promise.all([
    prisma.client.findUnique({
      where: { id: project.clientId },
      select: {
        id: true,
        name: true,
        contactPerson: true,
        email: true,
        phone: true,
        address: true,
        portalEnabled: true,
        createdAt: true,
        updatedAt: true,
        lastPortalLoginAt: true,
      },
    }),
    project.architectId
      ? prisma.user.findUnique({
          where: { id: project.architectId },
          select: { id: true, name: true, initials: true, avatarUrl: true },
        })
      : Promise.resolve(null),
    project.supervisorId
      ? prisma.user.findUnique({
          where: { id: project.supervisorId },
          select: { id: true, name: true, initials: true, avatarUrl: true },
        })
      : Promise.resolve(null),
  ]);

  return NextResponse.json(
    { ...project, client: responseClient, architect: responseArchitect, supervisor: responseSupervisor },
    {
      status: 201,
    }
  );
}
'@
Write-PatchFile "src/app/api/projects/route.ts" $content

# --- [MOD] src/app/api/payments/route.ts ---
$content = @'
import { notifyPaymentUpdate } from "@/lib/notifications";
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import {
  canRecordPayments,
  canViewPayments,
  isAdmin,
  relatedProjectAccessWhere,
} from "@/lib/rbac";
import { z } from "zod";

/*
|--------------------------------------------------------------------------
| Validation
|--------------------------------------------------------------------------
*/

const Schema = z.object({
  projectId: z.string().min(1),

  /**
   * Payment amounts must always be positive.
   */
  amount: z.number().positive(),

  /**
   * Date received from frontend.
   */
  date: z.string().min(1),

  reference: z
    .string()
    .max(200)
    .optional(),

  note: z
    .string()
    .max(2000)
    .optional(),
});

/*
|--------------------------------------------------------------------------
| GET /api/payments
|--------------------------------------------------------------------------
|
| ADMIN:
|   Can retrieve all payment records.
|
| ARCHITECT:
|   Can retrieve payments only for projects where they are:
|
|       architect OR supervisor
|
| IMPORTANT:
|
| This is READ authorization.
|
| Recording payments remains ADMIN-only and is handled by POST.
|
|--------------------------------------------------------------------------
*/

export async function GET(
  req: NextRequest
) {
  const session = await auth();

  /*
   * ---------------------------------------------------------------
   * Authentication
   * ---------------------------------------------------------------
   */

  if (!session) {
    return NextResponse.json(
      {
        error: "Unauthorized",
      },
      {
        status: 401,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Financial read permission
   * ---------------------------------------------------------------
   */

  if (!canViewPayments(session)) {
    return NextResponse.json(
      {
        error: "Forbidden",
      },
      {
        status: 403,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Optional project filter
   * ---------------------------------------------------------------
   */

  const { searchParams } =
    new URL(req.url);

  const projectId =
    searchParams.get("projectId");

  /*
   * ---------------------------------------------------------------
   * Build secure project scope
   * ---------------------------------------------------------------
   *
   * ADMIN:
   *
   *     all projects
   *
   * ARCHITECT:
   *
   *     only projects where:
   *
   *       architectId = current user
   *       OR
   *       supervisorId = current user
   *
   * When a specific projectId is supplied, BOTH conditions must be
   * satisfied.
   */

  const relatedWhere = relatedProjectAccessWhere(session);

  const projectWhere =
    relatedWhere === undefined
      ? projectId
        ? {
            id: projectId,
          }
        : undefined
      : {
          AND: [
            relatedWhere,

            ...(projectId
              ? [
                  {
                    id: projectId,
                  },
                ]
              : []),
          ],
        };

  /*
   * ---------------------------------------------------------------
   * Retrieve payments
   * ---------------------------------------------------------------
   */

  try {
    /*
     * Converts the relational project-access filter into a flat list
     * of allowed project IDs first, instead of filtering payments via
     * `where: { project: projectWhere }` directly (a join). On
     * HostPinnacle, queries involving relation joins -- whether in a
     * select OR a where clause -- fail with "Connection terminated
     * unexpectedly"; a plain `projectId: { in: [...] }` filter avoids
     * the join entirely. When projectWhere is undefined (admin, no
     * specific project requested), there's nothing to restrict, so
     * this step is skipped.
     */
    let projectIdFilter: string[] | undefined;

    if (projectWhere !== undefined) {
      const accessibleProjects = await prisma.project.findMany({
        where: projectWhere,
        select: { id: true },
      });
      projectIdFilter = accessibleProjects.map((p) => p.id);
    }

    const payments =
      await prisma.payment.findMany({
        where: {
          ...(projectIdFilter ? { projectId: { in: projectIdFilter } } : {}),
        },

        select: {
          id: true,

          amount: true,

          date: true,

          reference: true,

          note: true,

          createdAt: true,

          projectId: true,

          recordedById: true,
        },

        orderBy: [
          {
            date: "desc",
          },
          {
            createdAt: "desc",
          },
        ],
      });

    /*
     * Same batched-flat-lookup pattern as /api/projects: fetch the
     * related projects and users as separate flat queries instead of
     * nested relation selects, then stitch back into the exact same
     * response shape as before.
     */
    const paymentProjectIds = [...new Set(payments.map((p) => p.projectId))];
    const recorderIds = [...new Set(payments.map((p) => p.recordedById))];

    const [relatedProjects, recorders] = await Promise.all([
      prisma.project.findMany({
        where: { id: { in: paymentProjectIds } },
        select: { id: true, name: true, sheetNo: true, budget: true, invoiced: true, paid: true },
      }),
      prisma.user.findMany({
        where: { id: { in: recorderIds } },
        select: { id: true, name: true },
      }),
    ]);

    const projectById = new Map(relatedProjects.map((p) => [p.id, p]));
    const recorderById = new Map(recorders.map((u) => [u.id, u]));

    const paymentsWithRelations = payments.map((payment) => ({
      ...payment,
      project: projectById.get(payment.projectId) ?? null,
      recordedBy: recorderById.get(payment.recordedById) ?? null,
    }));

    /*
     * ---------------------------------------------------------------
     * Return payment records
     * ---------------------------------------------------------------
     */

    return NextResponse.json(
      paymentsWithRelations
    );
  } catch (error) {
    console.error(
      "Failed to fetch payments:",
      error
    );

    return NextResponse.json(
      {
        error:
          "Failed to load payment records",
      },
      {
        status: 500,
      }
    );
  }
}

/*
|--------------------------------------------------------------------------
| POST /api/payments
|--------------------------------------------------------------------------
|
| Records a client payment.
|
| FINANCIAL MODEL
|
| Budget   = total contract value
| Invoiced = amount billed
| Paid     = amount actually received
|
| Outstanding = Invoiced - Paid
|
| A payment is NOT allowed to make:
|
|     Paid > Invoiced
|
|--------------------------------------------------------------------------
*/

export async function POST(
  req: NextRequest
) {
  const session = await auth();

  /*
   * ---------------------------------------------------------------
   * Authentication
   * ---------------------------------------------------------------
   */

  if (!session) {
    return NextResponse.json(
      {
        error: "Unauthorized",
      },
      {
        status: 401,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * RBAC
   * ---------------------------------------------------------------
   *
   * Only administrators can record payments.
   */

  if (!canRecordPayments(session)) {
    return NextResponse.json(
      {
        error: "Forbidden",
      },
      {
        status: 403,
      }
    );
  }

  /*
   * Explicit financial authorization.
   *
   * Keep this as defense in depth.
   */

  if (!isAdmin(session)) {
    return NextResponse.json(
      {
        error:
          "Only administrators can record payments",
      },
      {
        status: 403,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Read request body
   * ---------------------------------------------------------------
   */

  let body: unknown;

  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      {
        error:
          "Invalid JSON request body",
      },
      {
        status: 400,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Validate request
   * ---------------------------------------------------------------
   */

  const parsed =
    Schema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      {
        error:
          parsed.error.flatten(),
      },
      {
        status: 400,
      }
    );
  }

  const {
    projectId,
    amount,
    date,
    reference,
    note,
  } = parsed.data;

  /*
   * ---------------------------------------------------------------
   * Validate payment date
   * ---------------------------------------------------------------
   */

  const paymentDate =
    new Date(date);

  if (
    Number.isNaN(
      paymentDate.getTime()
    )
  ) {
    return NextResponse.json(
      {
        error:
          "Invalid payment date",
      },
      {
        status: 400,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Initial project lookup
   * ---------------------------------------------------------------
   */

  let project;

  try {
    project =
      await prisma.project.findUnique({
        where: {
          id: projectId,
        },

        select: {
          id: true,
          name: true,
          sheetNo: true,

          budget: true,
          invoiced: true,
          paid: true,

          architectId: true,
          supervisorId: true,

          archivedAt: true,
        },
      });
  } catch (error) {
    console.error(
      "Failed to find project for payment:",
      error
    );

    return NextResponse.json(
      {
        error:
          "Failed to load project",
      },
      {
        status: 500,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Project existence
   * ---------------------------------------------------------------
   */

  if (!project) {
    return NextResponse.json(
      {
        error:
          "Project not found",
      },
      {
        status: 404,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Archived project protection
   * ---------------------------------------------------------------
   */

  if (project.archivedAt) {
    return NextResponse.json(
      {
        error:
          "Payments cannot be recorded for archived projects",
      },
      {
        status: 400,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * Financial validation
   * ---------------------------------------------------------------
   *
   * Correct relationship:
   *
   *     Budget >= Invoiced >= Paid
   *
   * Therefore:
   *
   *     Outstanding = Budget - Paid
   *
   * (Invoiced is tracked separately via /api/invoices for reference,
   * but no longer constrains what payments are allowed.)
   */

  const contractValue =
    Number(project.budget ?? 0);

  const currentPaid =
    Number(project.paid ?? 0);

  /*
   * Payments are capped directly against the contract budget --
   * invoicing (see /api/invoices) is informational tracking only and
   * no longer gates whether a payment can be recorded. A firm can
   * record a client's payment the moment it's received, whether or
   * not a formal invoice was raised for it first.
   */

  const outstandingBalance =
    Math.max(
      contractValue -
        currentPaid,
      0
    );

  /*
   * ---------------------------------------------------------------
   * Prevent overpayment
   * ---------------------------------------------------------------
   */

  if (
    amount >
    outstandingBalance
  ) {
    return NextResponse.json(
      {
        error:
          `Payment exceeds the remaining contract balance of ${outstandingBalance}`,
      },
      {
        status: 400,
      }
    );
  }

  /*
   * ---------------------------------------------------------------
   * CREATE PAYMENT + UPDATE PAID ATOMICALLY
   * ---------------------------------------------------------------
   */

  try {
    const result =
      await prisma.$transaction(
        async (tx) => {
          /*
           * -----------------------------------------------------
           * Re-read current project state
           * -----------------------------------------------------
           */

          const currentProject =
            await tx.project.findUnique({
              where: {
                id: projectId,
              },

              select: {
                id: true,
                name: true,
                sheetNo: true,

                budget: true,
                invoiced: true,
                paid: true,

                architectId: true,
                supervisorId: true,

                archivedAt: true,
              },
            });

          if (!currentProject) {
            throw new Error(
              "PROJECT_NOT_FOUND"
            );
          }

          /*
           * -----------------------------------------------------
           * Archived project check
           * -----------------------------------------------------
           */

          if (
            currentProject.archivedAt
          ) {
            throw new Error(
              "PROJECT_ARCHIVED"
            );
          }

          /*
           * -----------------------------------------------------
           * Recalculate from latest state
           * -----------------------------------------------------
           */

          const currentBudget =
            Number(
              currentProject.budget ??
                0
            );

          const currentPaid =
            Number(
              currentProject.paid ??
                0
            );

          /*
           * -----------------------------------------------------
           * Latest outstanding balance (capped directly by
           * contract budget -- invoicing is informational only
           * and no longer gates whether a payment is allowed)
           * -----------------------------------------------------
           */

          const currentOutstanding =
            Math.max(
              currentBudget -
                currentPaid,
              0
            );

          /*
           * -----------------------------------------------------
           * Prevent overpayment
           * -----------------------------------------------------
           */

          if (
            amount >
            currentOutstanding
          ) {
            throw new Error(
              `PAYMENT_EXCEEDS_BALANCE:${currentOutstanding}`
            );
          }

          /*
           * -----------------------------------------------------
           * Create payment record
           * -----------------------------------------------------
           */

          const payment =
            await tx.payment.create({
              data: {
                projectId,

                recordedById:
                  session.user.id,

                amount,

                date: paymentDate,

                reference:
                  reference?.trim() ||
                  null,

                note:
                  note?.trim() ||
                  null,
              },

              select: {
                id: true,

                amount: true,

                date: true,

                reference: true,

                note: true,

                createdAt: true,

                projectId: true,

                recordedById: true,
              },
            });

          /*
           * -----------------------------------------------------
           * Update project paid amount
           * -----------------------------------------------------
           *
           * Payment increases PAID.
           *
           * Payment does NOT increase INVOICED.
           */

          const updatedProject =
            await tx.project.update({
              where: {
                id: projectId,
              },

              data: {
                paid: {
                  increment: amount,
                },
              },

              select: {
                id: true,
                name: true,
                sheetNo: true,

                budget: true,
                invoiced: true,
                paid: true,

                architectId: true,
                supervisorId: true,
              },
            });

          /*
           * -----------------------------------------------------
           * Final consistency check
           * -----------------------------------------------------
           */

          const updatedBudget =
            Number(
              updatedProject.budget ??
                0
            );

          const updatedPaid =
            Number(
              updatedProject.paid ??
                0
            );

          if (
            updatedPaid >
            updatedBudget
          ) {
            throw new Error(
              "UPDATED_PAID_EXCEEDS_BUDGET"
            );
          }

          return {
            payment,
            updatedProject,
          };
        }
      );

    /*
     * ---------------------------------------------------------------
     * Calculate financial position
     * ---------------------------------------------------------------
     */

    const newBudget =
      Number(
        result.updatedProject
          .budget ?? 0
      );

    const newInvoiced =
      Number(
        result.updatedProject
          .invoiced ?? 0
      );

    const newPaid =
      Number(
        result.updatedProject
          .paid ?? 0
      );

    const newOutstandingBalance =
      Math.max(
        newBudget -
          newPaid,
        0
      );

    const newUninvoicedBalance =
      Math.max(
        newBudget -
          newInvoiced,
        0
      );

    /*
     * ---------------------------------------------------------------
     * Notifications
     * ---------------------------------------------------------------
     */

    const recipients = [
      result.updatedProject
        .architectId,

      result.updatedProject
        .supervisorId,
    ].filter(
      (
        id
      ): id is string =>
        Boolean(id) &&
        id !== session.user.id
    );

    const uniqueRecipients = [
      ...new Set(recipients),
    ];

    await Promise.all(
      uniqueRecipients.map(
        async (userId) => {
          try {
            await notifyPaymentUpdate({
              userId,

              projectId:
                result.updatedProject
                  .id,

              projectName:
                `${result.updatedProject.name} (${result.updatedProject.sheetNo})`,

              amount,

              outstandingBalance:
                newOutstandingBalance,
            });
          } catch (error) {
            console.error(
              `Failed to notify user ${userId} about payment:`,
              error
            );
          }
        }
      )
    );

    /*
     * ---------------------------------------------------------------
     * Return payment + financial summary
     * ---------------------------------------------------------------
     */

    return NextResponse.json(
      {
        ...result.payment,

        project: {
          id: result.updatedProject.id,
          name: result.updatedProject.name,
          sheetNo: result.updatedProject.sheetNo,
          budget: newBudget,
          invoiced: newInvoiced,
          paid: newPaid,
        },

        recordedBy: {
          id: session.user.id,
          name: session.user.name,
        },

        financialSummary: {
          budget:
            newBudget,

          invoiced:
            newInvoiced,

          paid:
            newPaid,

          outstanding:
            newOutstandingBalance,

          uninvoiced:
            newUninvoicedBalance,
        },
      },
      {
        status: 201,
      }
    );
  } catch (error) {
    /*
     * ---------------------------------------------------------------
     * Known business errors
     * ---------------------------------------------------------------
     */

    if (
      error instanceof Error
    ) {
      if (
        error.message ===
        "PROJECT_NOT_FOUND"
      ) {
        return NextResponse.json(
          {
            error:
              "Project not found",
          },
          {
            status: 404,
          }
        );
      }

      if (
        error.message ===
        "PROJECT_ARCHIVED"
      ) {
        return NextResponse.json(
          {
            error:
              "Payments cannot be recorded for archived projects",
          },
          {
            status: 400,
          }
        );
      }

      if (
        error.message ===
        "UPDATED_PAID_EXCEEDS_BUDGET"
      ) {
        return NextResponse.json(
          {
            error:
              "The project's paid amount exceeds its contract budget.",
          },
          {
            status: 400,
          }
        );
      }

      if (
        error.message.startsWith(
          "PAYMENT_EXCEEDS_BALANCE:"
        )
      ) {
        const balance =
          error.message.substring(
            "PAYMENT_EXCEEDS_BALANCE:"
              .length
          );

        return NextResponse.json(
          {
            error:
              `Payment exceeds the remaining contract balance of ${balance}`,
          },
          {
            status: 400,
          }
        );
      }
    }

    /*
     * ---------------------------------------------------------------
     * Unexpected server error
     * ---------------------------------------------------------------
     */

    console.error(
      "Payment creation error:",
      error
    );

    return NextResponse.json(
      {
        error:
          "Failed to record payment",
      },
      {
        status: 500,
      }
    );
  }
}
'@
Write-PatchFile "src/app/api/payments/route.ts" $content

# --- [MOD] src/app/api/invoices/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import {
  canRecordInvoices,
  canViewPayments,
  isAdmin,
  relatedProjectAccessWhere,
} from "@/lib/rbac";
import { z } from "zod";

const Schema = z.object({
  projectId: z.string().min(1),
  amount: z.number().positive(),
  date: z.string().min(1),
  reference: z.string().max(200).optional(),
  note: z.string().max(2000).optional(),
});

/*
|--------------------------------------------------------------------------
| GET /api/invoices
|--------------------------------------------------------------------------
| Same read-authorization shape as /api/payments: ADMIN and SENIOR_ARCHITECT
| see everything, ARCHITECT only their own assigned/supervised projects.
| Recording remains ADMIN-only, handled by POST below.
|--------------------------------------------------------------------------
*/
export async function GET(req: NextRequest) {
  const session = await auth();

  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!canViewPayments(session)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const { searchParams } = new URL(req.url);
  const projectId = searchParams.get("projectId");

  const relatedWhere = relatedProjectAccessWhere(session);

  const projectWhere =
    relatedWhere === undefined
      ? projectId
        ? { id: projectId }
        : undefined
      : {
          AND: [
            relatedWhere,
            ...(projectId ? [{ id: projectId }] : []),
          ],
        };

  try {
    /*
     * Same fix as /api/payments GET: converts the relational
     * project-access filter into a flat list of allowed project IDs
     * first, instead of `where: { project: projectWhere }` (a join).
     * On HostPinnacle, queries involving relation joins -- whether in
     * a select OR a where clause -- fail with "Connection terminated
     * unexpectedly"; a plain `projectId: { in: [...] }` filter avoids
     * the join entirely.
     */
    let projectIdFilter: string[] | undefined;

    if (projectWhere !== undefined) {
      const accessibleProjects = await prisma.project.findMany({
        where: projectWhere,
        select: { id: true },
      });
      projectIdFilter = accessibleProjects.map((p) => p.id);
    }

    const invoices = await prisma.invoice.findMany({
      where: {
        ...(projectIdFilter ? { projectId: { in: projectIdFilter } } : {}),
      },
      select: {
        id: true,
        amount: true,
        date: true,
        reference: true,
        note: true,
        createdAt: true,
        projectId: true,
        recordedById: true,
      },
      orderBy: [{ date: "desc" }, { createdAt: "desc" }],
    });

    const invoiceProjectIds = [...new Set(invoices.map((i) => i.projectId))];
    const recorderIds = [...new Set(invoices.map((i) => i.recordedById))];

    const [relatedProjects, recorders] = await Promise.all([
      prisma.project.findMany({
        where: { id: { in: invoiceProjectIds } },
        select: { id: true, name: true, sheetNo: true, budget: true, invoiced: true, paid: true },
      }),
      prisma.user.findMany({
        where: { id: { in: recorderIds } },
        select: { id: true, name: true },
      }),
    ]);

    const projectById = new Map(relatedProjects.map((p) => [p.id, p]));
    const recorderById = new Map(recorders.map((u) => [u.id, u]));

    const invoicesWithRelations = invoices.map((invoice) => ({
      ...invoice,
      project: projectById.get(invoice.projectId) ?? null,
      recordedBy: recorderById.get(invoice.recordedById) ?? null,
    }));

    return NextResponse.json(invoicesWithRelations);
  } catch (error) {
    console.error("Failed to fetch invoices:", error);
    return NextResponse.json(
      { error: "Failed to load invoice records" },
      { status: 500 }
    );
  }
}

/*
|--------------------------------------------------------------------------
| POST /api/invoices
|--------------------------------------------------------------------------
| Raises an invoice against a project's budget -- the step that was
| entirely missing before this route existed. Payments were always
| correctly capped at "can't exceed invoiced" (see /api/payments); this
| is what actually lets `invoiced` become greater than zero in the
| first place.
|
| Same safety shape as recording a payment: amount re-validated against
| a FRESH read of current state inside the transaction (not the request
| body's stale view), so two concurrent invoice requests can't together
| push `invoiced` past `budget`.
|--------------------------------------------------------------------------
*/
export async function POST(req: NextRequest) {
  const session = await auth();

  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  if (!canRecordInvoices(session)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  // Defense in depth, same pattern as /api/payments.
  if (!isAdmin(session)) {
    return NextResponse.json(
      { error: "Only administrators can record invoices" },
      { status: 403 }
    );
  }

  let body: unknown;

  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON request body" }, { status: 400 });
  }

  const parsed = Schema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });
  }

  const { projectId, amount, date, reference, note } = parsed.data;

  const invoiceDate = new Date(date);

  if (Number.isNaN(invoiceDate.getTime())) {
    return NextResponse.json({ error: "Invalid date" }, { status: 400 });
  }

  try {
    const result = await prisma.$transaction(async (tx) => {
      const currentProject = await tx.project.findUnique({
        where: { id: projectId },
        select: { id: true, budget: true, invoiced: true, paid: true },
      });

      if (!currentProject) {
        throw new Error("PROJECT_NOT_FOUND");
      }

      const currentBudget = Number(currentProject.budget ?? 0);
      const currentInvoiced = Number(currentProject.invoiced ?? 0);

      const remainingToInvoice = Math.max(currentBudget - currentInvoiced, 0);

      if (amount > remainingToInvoice) {
        throw new Error(`INVOICE_EXCEEDS_BUDGET:${remainingToInvoice}`);
      }

      const invoice = await tx.invoice.create({
        data: {
          projectId,
          recordedById: session.user.id,
          amount,
          date: invoiceDate,
          reference: reference?.trim() || null,
          note: note?.trim() || null,
        },
        select: {
          id: true,
          amount: true,
          date: true,
          reference: true,
          note: true,
          createdAt: true,
          projectId: true,
          recordedById: true,
        },
      });

      const updatedProject = await tx.project.update({
        where: { id: projectId },
        data: { invoiced: { increment: amount } },
        select: { id: true, budget: true, invoiced: true, paid: true },
      });

      return { invoice, project: updatedProject };
    });

    return NextResponse.json(result, { status: 201 });
  } catch (error) {
    if (error instanceof Error && error.message === "PROJECT_NOT_FOUND") {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    if (error instanceof Error && error.message.startsWith("INVOICE_EXCEEDS_BUDGET:")) {
      const remaining = error.message.split(":")[1];
      return NextResponse.json(
        {
          error: `This invoice would exceed the project's remaining budget. Ksh ${Number(remaining).toLocaleString()} is still available to invoice.`,
        },
        { status: 400 }
      );
    }

    console.error("Failed to record invoice:", error);
    return NextResponse.json({ error: "Failed to record invoice" }, { status: 500 });
  }
}

'@
Write-PatchFile "src/app/api/invoices/route.ts" $content

Write-Host ""
Write-Host "Patch 50 applied. Now:" -ForegroundColor Cyan
Write-Host "  git add ."
Write-Host "  git commit -m ""Fix CI crash and extend flat-query fix to payments/invoices"""
Write-Host "  git push origin main"
Write-Host ""
Write-Host "Watch the Actions tab -- CI will catch any real type error before it deploys." -ForegroundColor Yellow
