<#
  Architect Hub -- patch 17: fixes the REAL cause of the Vercel build
  failure. Patch 16's standalone-output fix was real but not the whole
  story -- this was the other half.
  Generated by Claude -- 2026-08-22

  ROOT CAUSE: there was no `postinstall` script and no `prisma generate`
  step in `build` at all -- just "build": "next build". This has worked
  on your own machine this whole session because you've been manually
  running `npx prisma generate` yourself before every build (which I've
  had you do throughout). Vercel does a completely clean install with no
  memory of that -- it never generated a Prisma Client at all before
  running next build, so any route touching prisma (change-password,
  and really any API route) failed to initialize it. Same reason the
  error mentions clientVersion/errorCode -- that's Prisma's own
  initialization-failure shape.

  The Dockerfile already had this right (explicit `RUN npx prisma
  generate` before `RUN npm run build`) -- Vercel and any other clean-
  install-only environment were the actual gap.

  FIX: added "postinstall": "prisma generate" to package.json. This
  runs automatically after every npm install, on any platform, so
  Vercel's clean build always has a real generated client before
  next build runs. Your schema has no explicit binaryTargets override,
  so Prisma auto-detects whatever machine is running -- generating on
  Vercel's own build machine produces the correct binary for Vercel
  automatically, no extra config needed.

  This is redundant with the Dockerfile's explicit generate step (now
  runs twice there -- harmless, a few extra seconds) and with CI's
  explicit step -- left both as-is rather than removing them, since
  relying on postinstall alone assumes npm ci always runs install
  scripts, which is the default but not guaranteed in every environment.

  62/62 tests on your machine (same 3 sandbox-only failures here as
  before, confirmed unrelated).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-17.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 17 (fix the real Vercel build cause)..." -ForegroundColor Cyan

# --- [MOD] package.json ---
$content = @'
{
  "name": "architect-hub",
  "version": "0.1.0",
  "private": true,
 "scripts": {
  "dev": "next dev",
  "build": "next build",
  "start": "next start",
  "lint": "eslint .",
  "postinstall": "prisma generate",
  "db:generate": "prisma generate",
  "db:push": "prisma db push",
  "db:migrate": "prisma migrate dev",
  "db:studio": "prisma studio",
  "worker": "tsx --env-file=.env src/worker.ts",
  "test": "vitest run",
  "test:watch": "vitest"
},

  "dependencies": {
    "@aws-sdk/client-s3": "^3.1106.0",
    "@aws-sdk/s3-request-presigner": "^3.1106.0",
    "@prisma/client": "^5.22.0",
    "@radix-ui/react-dialog": "^1.1.23",
    "@radix-ui/react-popover": "^1.1.23",
    "@radix-ui/react-progress": "^1.1.16",
    "@radix-ui/react-select": "^2.3.7",
    "@radix-ui/react-slot": "^1.3.3",
    "bcryptjs": "^2.4.3",
    "bullmq": "^6.0.9",
    "class-variance-authority": "^0.7.1",
    "clsx": "^2.1.1",
    "ioredis": "^6.0.0",
    "lucide-react": "^0.453.0",
    "next": "^16.3.0",
    "next-auth": "^5.0.0-beta.25",
    "otplib": "^12.0.1",
    "qrcode": "^1.5.4",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "resend": "^4.0.0",
    "tailwind-merge": "^2.5.4",
    "zod": "^3.23.8"
  },
  "devDependencies": {
    "@types/bcryptjs": "^2.4.6",
    "@types/node": "^22.7.5",
    "@types/qrcode": "^1.5.5",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.0",
    "autoprefixer": "^10.4.20",
    "eslint": "^9.15.0",
    "eslint-config-next": "^16.3.0",
    "postcss": "^8.4.47",
    "prisma": "^5.22.0",
    "tailwindcss": "^3.4.14",
    "ts-node": "^10.9.2",
    "tsx": "^4.23.0",
    "typescript": "^5.6.3",
    "vitest": "^4.1.10"
  }
}

'@
Write-PatchFile "package.json" $content

Write-Host ""
Write-Host "Patch 17 applied. Sanity check locally:" -ForegroundColor Green
Write-Host "  npm install"
Write-Host "  (watch for prisma generate running automatically as part of install now)"
Write-Host "  npm run build"
Write-Host "Then commit, push, let Vercel rebuild." -ForegroundColor Green
