<#
  Architect Hub -- patch 16: fixes the Vercel build failure
  ("Failed to collect page data for /api/auth/change-password").
  Generated by Claude -- 2026-08-22

  ROOT CAUSE: output: "standalone" is what the Dockerfile (Railway/
  self-hosted path) needs -- a self-contained server.js with only each
  route's actual dependencies bundled in. Vercel has its own packaging
  system for serverless functions entirely, and combining the two
  causes exactly this failure on API routes that touch Prisma during
  Vercel's build-time page-data collection step.

  FIX: output: "standalone" now only applies when NOT building on
  Vercel (Vercel sets process.env.VERCEL automatically during its own
  builds, so this needs no manual toggle -- it just does the right
  thing on whichever platform is actually running the build). Verified
  directly: output resolves to "standalone" without VERCEL set (your
  Railway/Docker path, unaffected) and to undefined with VERCEL=1 set
  (matches what Vercel actually wants).

  Lint clean, 62/62 tests on your machine.

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-16.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 16 (fix Vercel build)..." -ForegroundColor Cyan

# --- [MOD] next.config.js ---
$content = @'
/** @type {import('next').NextConfig} */
const isProd = process.env.NODE_ENV === "production";

// Derived from the same env vars src/lib/s3.ts actually uses, so this
// always matches whatever bucket/region is really configured at deploy
// time -- a hardcoded guess here would silently break every document
// thumbnail and avatar in production the moment it didn't match the
// real bucket, and (like the CSP itself) nothing in dev would ever
// reveal that mismatch since this header is skipped in dev entirely.
const s3ImgSrc =
  process.env.AWS_S3_BUCKET && process.env.AWS_REGION
    ? `https://${process.env.AWS_S3_BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com`
    : ""; // S3 not configured -- falls back to local disk storage, nothing to allowlist

const nextConfig = {
  reactStrictMode: true,
  // "standalone" output is what the Dockerfile (Railway/self-hosted
  // path) needs -- it produces a self-contained server.js with only the
  // dependencies each route actually uses. Vercel has its own packaging
  // system for serverless functions and doesn't want this: combined
  // with Vercel's build, it causes exactly the "Failed to collect page
  // data" error on API routes that touch Prisma. process.env.VERCEL is
  // set automatically by Vercel's build environment, so this correctly
  // targets each platform's own expectations without needing a manual
  // toggle.
  ...(process.env.VERCEL ? {} : { output: "standalone" }),
  experimental: { serverActions: { allowedOrigins: ["localhost:3000"] } },
  async headers() {
    if (!isProd) return []; // don't apply CSP/HSTS in dev — breaks HMR/Fast Refresh

    const csp = [
      "default-src 'self'",
      // 'unsafe-inline' is required here -- Next.js's App Router injects
      // inline hydration scripts (self.__next_f.push(...)) into every
      // page. Without this, a browser enforcing this CSP blocks those
      // scripts and the app fails to hydrate at all -- blank page,
      // nothing interactive. This CSP header only activates in
      // production (see isProd above), so this had never actually been
      // exercised until now; dev mode always skips it.
      //
      // The "correct" alternative is a per-request nonce generated in
      // middleware instead of 'unsafe-inline'. That's deliberately NOT
      // done here: as of this Next.js version, nonce-based CSP is
      // broken specifically for the Turbopack + output:"standalone"
      // combination this app uses -- Next's own injected scripts don't
      // receive the nonce at all, so the app breaks the same way either
      // way. 'unsafe-inline' is also Next.js's own documented
      // recommendation for apps not implementing per-request nonces.
      // Revisit once that upstream bug is fixed.
      "script-src 'self' 'unsafe-inline'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data:" + (s3ImgSrc ? ` ${s3ImgSrc}` : ""),
      "font-src 'self' data:",
      "connect-src 'self'",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "object-src 'none'",
    ].join("; ");

    return [
      {
        source: "/(.*)",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
        ],
      },
    ];
  },
};
module.exports = nextConfig;
'@
Write-PatchFile "next.config.js" $content

Write-Host ""
Write-Host "Patch 16 applied. Run locally as a sanity check:" -ForegroundColor Green
Write-Host "  npm run build"
Write-Host "Then commit, push, and let Vercel rebuild -- it should get past the change-password route this time." -ForegroundColor Green
Write-Host "Also double check DATABASE_URL and DIRECT_URL are actually set in the Vercel dashboard's Environment Variables -- a missing/wrong one there is the other common first-deploy cause of build or runtime failures." -ForegroundColor Yellow
