<#
  Architect Hub -- patch 24: fixes the staff-delete relation I missed
  last time, and a real error-message bug that made the project-creation
  400 look worse than it was.
  Generated by Claude -- 2026-08-22

  1. STAFF DELETE (still incomplete after patch 23): the FK violation
     you hit -- AssignmentRecord_toArchitectId_fkey -- comes from
     project reassignment/takeover history, a relation I didn't check
     last time. Went through the ENTIRE schema this time (grepped every
     single User-pointing relation, not just the obvious ones) and
     added: AssignmentRecord (from/to architect + performed-by),
     ProjectTask assignment, ProjectMilestone/ProgressSnapshot creation,
     and project archive/restore history to the pre-check.

     More importantly: added a safety net. Manually enumerating every
     relation has now proven fragile twice. The DELETE handler now also
     catches ANY foreign-key violation (Prisma code P2003) generically
     and returns the same clear "has existing records, deactivate
     instead" message -- so even a relation I still haven't thought of
     (there's also LoginEvent, for instance) gets a helpful answer
     instead of a raw crash. Added the same safety net to client
     deletion for consistency.

  2. ERROR MESSAGES: found why "API request failed: POST /api/projects
     (HTTP 400)" told you nothing useful. The server returns Zod's
     parsed.error.flatten() as `error` on validation failures -- an
     OBJECT (fieldErrors/formErrors), not a string. apiFetch only
     checked for a string, so the actual reason (in your case,
     "location must be at least 2 characters" -- you'd typed "k") was
     silently dropped every time, on every route using this pattern,
     not just project creation. Now extracts a real, specific message
     from that shape. Confirms your optional-architect fix from patch
     22 IS working correctly -- this was a genuinely separate, minor
     validation rule with an unhelpful error message, not a regression.

  Lint clean on all three files, 62/62 tests on your machine (same 3
  sandbox-only failures here, confirmed unrelated in every earlier
  patch).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-24.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 24..." -ForegroundColor Cyan

# --- [MOD] src/app/api/staff/[id]/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import bcrypt from "bcryptjs";
import { validatePassword, generateTemporaryPassword } from "@/lib/password-policy";

export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const isSelf = id === session.user.id;
  const isAdmin = session.user.role === "ADMIN";

  if (!isAdmin && !isSelf) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body = await req.json();

  // Only admins can change role, email, department, or active status.
  if (!isAdmin && (body.role || body.email || body.department !== undefined || body.isActive !== undefined)) {
    return NextResponse.json({ error: "Only an admin can change role, email, department, or active status" }, { status: 403 });
  }

  // Prevent an admin from locking themselves out entirely.
  if (isAdmin && isSelf && body.isActive === false) {
    return NextResponse.json({ error: "You cannot deactivate your own account" }, { status: 400 });
  }

  const initials = body.name
    ? body.name.split(" ").map((w: string) => w[0]).join("").slice(0, 2).toUpperCase()
    : undefined;

  let hashedPassword: string | undefined;
  let generatedPassword: string | undefined;
  let mustResetPassword: boolean | undefined;

  if (body.password) {
    if (isSelf && !isAdmin) {
      // Self-service password change must prove the current password first.
      const existing = await prisma.user.findUnique({ where: { id } });
      if (!existing) return NextResponse.json({ error: "Not found" }, { status: 404 });
      if (!body.currentPassword || !(await bcrypt.compare(body.currentPassword, existing.password))) {
        return NextResponse.json({ error: "Current password is incorrect" }, { status: 400 });
      }
    }
    const check = validatePassword(body.password);
    if (!check.valid) return NextResponse.json({ error: check.errors.join(" ") }, { status: 400 });
    hashedPassword = await bcrypt.hash(body.password, 12);
    mustResetPassword = false;
  } else if (isAdmin && body.resetPassword === true) {
    // Admin-triggered reset: generate a fresh temp password, force change on next login.
    generatedPassword = generateTemporaryPassword();
    hashedPassword = await bcrypt.hash(generatedPassword, 12);
    mustResetPassword = true;
  }

  const user = await prisma.user.update({
    where: { id },
    data: {
      ...(body.name && { name: body.name, initials }),
      ...(isAdmin && body.email && { email: body.email }),
      ...(isAdmin && body.role && { role: body.role }),
      ...(body.phone !== undefined && { phone: body.phone }),
      ...(isAdmin && body.department !== undefined && { department: body.department }),
      ...(isAdmin && body.isActive !== undefined && { isActive: body.isActive }),
      ...(hashedPassword && { password: hashedPassword, passwordChangedAt: new Date() }),
      ...(mustResetPassword !== undefined && { mustResetPassword }),
      ...(hashedPassword && { failedLoginAttempts: 0, lockedUntil: null }),
    },
    select: {
      id: true, name: true, email: true, role: true, phone: true, department: true,
      initials: true, avatarUrl: true, isActive: true, mustResetPassword: true,
    },
  });

  return NextResponse.json({ ...user, temporaryPassword: generatedPassword });
}

export async function DELETE(_: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  if (session.user.role !== "ADMIN") return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { id } = await params;
  if (id === session.user.id) return NextResponse.json({ error: "Cannot delete yourself" }, { status: 400 });

  const existing = await prisma.user.findUnique({ where: { id }, select: { id: true, name: true } });
  if (!existing) {
    return NextResponse.json({ error: "Staff member not found" }, { status: 404 });
  }

  /*
   * A staff account almost always has real work attached to it --
   * assigned projects, daily logs they submitted, documents they
   * uploaded, payments/invoices they recorded -- none of which cascade
   * on user deletion (correctly: deleting a person shouldn't delete
   * the firm's project history or financial records). Attempting a
   * raw delete against any of that throws an unhandled foreign-key
   * violation, which is why this previously just silently failed.
   * Check first and give a clear, actionable answer instead.
   */
  const [
    assignedProjects,
    supervisedProjects,
    dailyLogs,
    documents,
    payments,
    invoices,
    assignmentRecords,
    taskAssignments,
    milestonesCreated,
    snapshotsCreated,
    archiveHistory,
  ] =
    await Promise.all([
      prisma.project.count({ where: { architectId: id } }),
      prisma.project.count({ where: { supervisorId: id } }),
      prisma.dailyLog.count({ where: { authorId: id } }),
      prisma.document.count({ where: { uploadedById: id } }),
      prisma.payment.count({ where: { recordedById: id } }),
      prisma.invoice.count({ where: { recordedById: id } }),
      prisma.assignmentRecord.count({
        where: {
          OR: [
            { fromArchitectId: id },
            { toArchitectId: id },
            { performedById: id },
          ],
        },
      }),
      prisma.projectTask.count({ where: { assigneeId: id } }),
      prisma.projectMilestone.count({ where: { createdById: id } }),
      prisma.progressSnapshot.count({ where: { createdById: id } }),
      prisma.project.count({
        where: {
          OR: [{ archivedById: id }, { restoredById: id }],
        },
      }),
    ]);

  const hasHistory =
    assignedProjects > 0 ||
    supervisedProjects > 0 ||
    dailyLogs > 0 ||
    documents > 0 ||
    payments > 0 ||
    invoices > 0 ||
    assignmentRecords > 0 ||
    taskAssignments > 0 ||
    milestonesCreated > 0 ||
    snapshotsCreated > 0 ||
    archiveHistory > 0;

  if (hasHistory) {
    return NextResponse.json(
      {
        error: `${existing.name} has existing work on record (projects, daily logs, documents, payments, or invoices) and can't be permanently deleted -- that history needs to stay intact. Deactivate their account instead to block their login while keeping the firm's records complete.`,
      },
      { status: 409 }
    );
  }

  try {
    await prisma.user.delete({ where: { id } });
    return NextResponse.json({ success: true });
  } catch (error) {
    console.error(`Failed to delete staff member ${id}:`, error);

    /*
     * Safety net: the pre-check above enumerates the relations we know
     * about, but this schema has enough User-referencing tables (audit
     * trails, login history, etc.) that a manual list can miss one --
     * it already has once. Any foreign-key violation (Prisma code
     * P2003) at this point means the same underlying situation as the
     * pre-check catches, just via a table we didn't explicitly count.
     * Give the same clear, actionable answer either way instead of a
     * generic failure message.
     */
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "P2003"
    ) {
      return NextResponse.json(
        {
          error: `${existing.name} has existing records elsewhere in the system and can't be permanently deleted -- that history needs to stay intact. Deactivate their account instead to block their login while keeping the firm's records complete.`,
        },
        { status: 409 }
      );
    }

    return NextResponse.json({ error: "Failed to delete staff member" }, { status: 500 });
  }
}

'@
Write-PatchFile "src/app/api/staff/[id]/route.ts" $content

# --- [MOD] src/app/api/clients/[id]/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canManageClients, isAdmin } from "@/lib/rbac";
import { z } from "zod";

const UpdateSchema = z
  .object({
    name: z
      .string()
      .trim()
      .min(2, "Client name must be at least 2 characters")
      .optional(),

    contactPerson: z
      .string()
      .trim()
      .min(2, "Contact person must be at least 2 characters")
      .optional(),

    email: z
      .string()
      .trim()
      .email("Invalid email address")
      .optional()
      .or(z.literal("")),

    phone: z
      .string()
      .trim()
      .optional(),

    address: z
      .string()
      .trim()
      .optional(),
  })
  .refine(
    (data) => Object.keys(data).length > 0,
    {
      message: "At least one field must be provided for update.",
    }
  );

const SafeClientSelect = {
  id: true,
  name: true,
  contactPerson: true,
  email: true,
  phone: true,
  address: true,
  portalEnabled: true,
  createdAt: true,
  updatedAt: true,
  lastPortalLoginAt: true,
} as const;

export async function PATCH(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  /*
   * Client management is ADMIN ONLY.
   */
  if (!canManageClients(session)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const { id } = await params;

  if (!id) {
    return NextResponse.json(
      { error: "Client ID is required." },
      { status: 400 }
    );
  }

  let body: unknown;

  try {
    body = await req.json();
  } catch {
    return NextResponse.json(
      { error: "Invalid JSON request body." },
      { status: 400 }
    );
  }

  const parsed = UpdateSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.flatten() },
      { status: 400 }
    );
  }

  const data = parsed.data;

  try {
    /*
     * Explicitly select safe fields.
     *
     * passwordHash is never returned from this endpoint.
     */
    const client = await prisma.client.update({
      where: { id },

      data: {
        ...(data.name !== undefined && {
          name: data.name,
        }),

        ...(data.contactPerson !== undefined && {
          contactPerson: data.contactPerson,
        }),

        ...(data.email !== undefined && {
          email: data.email || null,
        }),

        ...(data.phone !== undefined && {
          phone: data.phone || null,
        }),

        ...(data.address !== undefined && {
          address: data.address || null,
        }),
      },

      select: SafeClientSelect,
    });

    return NextResponse.json(client);
  } catch (error) {
    console.error(
      `Failed to update client ${id}:`,
      error
    );

    /*
     * Prisma P2025 = record not found.
     */
    if (
      typeof error === "object" &&
      error !== null &&
      "code" in error &&
      error.code === "P2025"
    ) {
      return NextResponse.json(
        { error: "Client not found." },
        { status: 404 }
      );
    }

    return NextResponse.json(
      {
        error:
          "Failed to update client. Please try again.",
      },
      { status: 500 }
    );
  }
}

export async function DELETE(
  _: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  /*
   * Client deletion is ADMIN ONLY.
   */
  if (!isAdmin(session)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const { id } = await params;

  if (!id) {
    return NextResponse.json(
      { error: "Client ID is required." },
      { status: 400 }
    );
  }

  try {
    /*
     * Do not allow deletion while projects still belong
     * to this client.
     */
    const projectCount = await prisma.project.count({
      where: {
        clientId: id,
      },
    });

    if (projectCount > 0) {
      return NextResponse.json(
        {
          error:
            "Cannot delete a client with existing projects. Delete or reassign their projects first.",
        },
        { status: 409 }
      );
    }

    /*
     * Also block deletion if there are comment/communication records
     * tied to this client -- ClientComment.clientId doesn't cascade on
     * delete (correctly: those records should outlive the client if
     * the client's projects are still around), so a raw delete would
     * otherwise fail with a generic error instead of this clear one.
     */
    const commentCount = await prisma.clientComment.count({
      where: { clientId: id },
    });

    if (commentCount > 0) {
      return NextResponse.json(
        {
          error:
            "Cannot delete a client with existing communication records. Those need to be cleared first.",
        },
        { status: 409 }
      );
    }

    /*
     * Verify the client exists before deletion.
     */
    const client = await prisma.client.findUnique({
      where: { id },
      select: { id: true },
    });

    if (!client) {
      return NextResponse.json(
        { error: "Client not found." },
        { status: 404 }
      );
    }

    await prisma.client.delete({
      where: { id },
    });

    return NextResponse.json({
      success: true,
    });
  } catch (error) {
    console.error(
      `Failed to delete client ${id}:`,
      error
    );

    /*
     * Safety net matching the one added to staff deletion: the checks
     * above enumerate the relations we know about (projects, comments),
     * but a foreign-key violation on any other table this schema might
     * reference from Client means the same underlying situation --
     * existing records elsewhere depending on this client. Give the
     * same clear answer rather than a generic failure.
     */
    if (
      error &&
      typeof error === "object" &&
      "code" in error &&
      error.code === "P2003"
    ) {
      return NextResponse.json(
        {
          error:
            "This client has existing records elsewhere in the system and can't be deleted yet. Remove the related records first.",
        },
        { status: 409 }
      );
    }

    return NextResponse.json(
      {
        error:
          "Failed to delete client. Please try again.",
      },
      { status: 500 }
    );
  }
}
'@
Write-PatchFile "src/app/api/clients/[id]/route.ts" $content

# --- [MOD] src/store/app-store.tsx ---
$content = @'
"use client";

import {
  createContext,
  useContext,
  useState,
  useCallback,
  useEffect,
  useRef,
  ReactNode,
} from "react";
import { useSession } from "next-auth/react";
import { isFilePickerOpen, consumeFilePickerReturn } from "@/lib/file-picker-guard";

// ─── Types ───────────────────────────────────────────────────────────────────

export type Role = "ADMIN" | "SENIOR_ARCHITECT" | "ARCHITECT";

export type ProjectStatus =
  | "ON_TRACK"
  | "AT_RISK"
  | "DELAYED"
  | "COMPLETED";

export type PaymentStatus =
  | "paid"
  | "partial"
  | "overdue"
  | "pending";

export type Priority =
  | "LOW"
  | "MEDIUM"
  | "HIGH";

export type CommentType =
  | "FEEDBACK"
  | "APPROVAL"
  | "CHANGE_REQUEST"
  | "QUERY";

export type NotificationType =
  | "INFO"
  | "WARNING"
  | "SUCCESS"
  | "ERROR";

// ─── Interfaces ──────────────────────────────────────────────────────────────

export interface StaffMember {
  id: string;
  name: string;
  initials: string;
  avatarUrl?: string | null;
  email: string;
  role: Role;
  phone?: string;
  department?: string;
  joinDate: string;
  isActive?: boolean;
  mustResetPassword?: boolean;
  mfaEnabled?: boolean;

  _count?: {
    assignedProjects: number;
    dailyLogs: number;
  };
}

export interface Client {
  id: string;
  name: string;
  contactPerson: string;
  email?: string;
  phone?: string;
  address?: string;
  createdAt: string;

  projects?: Project[];

  portalEnabled?: boolean;
  lastPortalLoginAt?: string;
}

export interface Project {
  id: string;
  sheetNo: string;
  name: string;

  clientId: string;
  client?: Client;

  location: string;
  description?: string;

  status: ProjectStatus;
  progress: number;

  architectId?: string;
  architect?: StaffMember;

  supervisorId?: string;
  supervisor?: StaffMember;

  startDate: string;
  dueDate: string;

  budget: number;
  invoiced: number;
  paid: number;

  priority: Priority;

  assignmentHistory?: AssignmentRecord[];
  dailyLogs?: DailyLog[];
  comments?: ClientComment[];
  payments?: Payment[];
}

export interface AssignmentRecord {
  id: string;
  projectId: string;

  fromArchitectId?: string;

  fromArchitect?: {
    id: string;
    name: string;
  };

  toArchitectId: string;

  toArchitect?: {
    id: string;
    name: string;
  };

  reason?: string;
  date: string;

  performedBy?: {
    id: string;
    name: string;
  };
}

export interface DailyLog {
  id: string;
  projectId: string;

  project?: {
    id: string;
    name: string;
    sheetNo: string;
  };

  authorId: string;

  author?: {
    id: string;
    name: string;
    initials: string;
    avatarUrl?: string | null;
  };

  date: string;

  workCompleted: string;
  challenges: string;
  pendingWork: string;
  nextActions: string;

  progress: number;

  submittedAt: string;

  attachments?: {
    id: string;
    name: string;
    fileUrl: string;
    fileSize: number;
    mimeType: string;
  }[];
}

export interface ClientComment {
  id: string;
  projectId: string;

  project?: {
    id: string;
    name: string;
    sheetNo: string;
  };

  clientId: string;

  client?: {
    id: string;
    name: string;
  };

  author: string;
  content: string;

  type: CommentType;

  viaPortal?: boolean;

  createdAt: string;
  resolvedAt?: string;
}

export interface Payment {
  id: string;
  projectId: string;

  project?: {
    id: string;
    name: string;
    sheetNo: string;
  };

  amount: number;
  date: string;

  reference?: string;
  note?: string;

  recordedBy?: {
    id: string;
    name: string;
  };
}

export interface Notification {
  id: string;
  message: string;
  type: NotificationType;
  read: boolean;
  createdAt: string;
}

export interface Document {
  id: string;
  name: string;

  fileKey: string;
  fileUrl: string;

  fileSize: number;
  mimeType: string;

  version: number;

  uploadedAt: string;

  projectId: string;

  project?: {
    id: string;
    name: string;
    sheetNo: string;
  };

  uploadedById: string;

  clientVisible?: boolean;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function formatKsh(n: number) {
  return new Intl.NumberFormat("en-KE", {
    style: "currency",
    currency: "KES",
    maximumFractionDigits: 0,
  }).format(n);
}

export function statusLabel(s: ProjectStatus) {
  return {
    ON_TRACK: "On track",
    AT_RISK: "At risk",
    DELAYED: "Delayed",
    COMPLETED: "Completed",
  }[s];
}

export function roleLabel(r: Role) {
  return {
    ADMIN: "Admin",
    SENIOR_ARCHITECT: "Senior Architect",
    ARCHITECT: "Architect",
  }[r];
}

export function commentTypeLabel(t: CommentType) {
  return {
    FEEDBACK: "Feedback",
    APPROVAL: "Approval",
    CHANGE_REQUEST: "Change request",
    QUERY: "Query",
  }[t];
}

export function priorityLabel(p: Priority) {
  return {
    LOW: "Low",
    MEDIUM: "Medium",
    HIGH: "High",
  }[p];
}

export function formatFileSize(bytes: number) {
  if (bytes < 1024) {
    return `${bytes} B`;
  }

  if (bytes < 1024 * 1024) {
    return `${(bytes / 1024).toFixed(1)} KB`;
  }

  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// ─── API Helper ──────────────────────────────────────────────────────────────

async function apiFetch<T>(
  url: string,
  options: RequestInit = {}
): Promise<T> {
  const method = options.method ?? "GET";

  const headers = new Headers(options.headers);

  /*
   * Only add Content-Type for requests that actually send JSON.
   * This is important because FormData uploads must NOT have
   * Content-Type manually set.
   */
  if (
    options.body &&
    !(options.body instanceof FormData) &&
    !headers.has("Content-Type")
  ) {
    headers.set("Content-Type", "application/json");
  }

  try {
    const res = await fetch(url, {
      ...options,
      method,
      headers,
      credentials: "same-origin",
      cache: "no-store",
    });

    const contentType =
      res.headers.get("content-type") || "";

    const isJson =
      contentType.includes("application/json");

    let responseBody: unknown = null;

    if (isJson) {
      responseBody = await res
        .json()
        .catch(() => null);
    } else {
      responseBody = await res
        .text()
        .catch(() => "");
    }

    if (!res.ok) {
      console.error(
        `[API ${res.status}] ${method} ${url}`,
        responseBody
      );

      if (res.status === 401) {
        throw new Error(
          `Unauthorized: your session may have expired.`
        );
      }

      if (res.status === 403) {
        throw new Error(
          `Forbidden: you do not have permission to perform this action.`
        );
      }

      if (res.status === 404) {
        throw new Error(
          `API endpoint not found: ${method} ${url}`
        );
      }

      if (res.status === 413) {
        throw new Error(
          `The uploaded file is too large.`
        );
      }

      let serverMessage = "";

      if (
        typeof responseBody === "object" &&
        responseBody !== null
      ) {
        const body = responseBody as Record<
          string,
          unknown
        >;

        if (typeof body.error === "string") {
          serverMessage = body.error;
        } else if (
          typeof body.error === "object" &&
          body.error !== null
        ) {
          /*
           * Many routes return Zod's parsed.error.flatten() directly
           * as `error` on a 400 -- an object shaped like
           * { formErrors: string[], fieldErrors: { [field]: string[] } },
           * not a plain string. Without this, that whole object was
           * silently dropped and the person just saw a generic
           * "API request failed" message with zero indication of what
           * was actually wrong (e.g. "location must be at least 2
           * characters" -- a real, specific, fixable reason).
           */
          const zodShape = body.error as {
            fieldErrors?: Record<string, string[]>;
            formErrors?: string[];
          };

          const fieldMessages = zodShape.fieldErrors
            ? Object.entries(zodShape.fieldErrors)
                .filter(([, msgs]) => Array.isArray(msgs) && msgs.length > 0)
                .map(([field, msgs]) => `${field}: ${msgs.join(", ")}`)
            : [];

          const formMessages = Array.isArray(zodShape.formErrors)
            ? zodShape.formErrors
            : [];

          serverMessage = [...fieldMessages, ...formMessages].join("; ");
        } else if (
          typeof body.message === "string"
        ) {
          serverMessage = body.message;
        }
      } else if (
        typeof responseBody === "string"
      ) {
        serverMessage = responseBody;
      }

      throw new Error(
        serverMessage ||
          `API request failed: ${method} ${url} (HTTP ${res.status})`
      );
    }

    if (!isJson) {
      throw new Error(
        `Server returned a non-JSON response for ${method} ${url}.`
      );
    }

    return responseBody as T;
  } catch (error) {
    if (error instanceof Error) {
      console.error(
        `API request failed: ${method} ${url}`,
        error
      );

      throw error;
    }

    throw new Error(
      `API request failed: ${method} ${url}`
    );
  }
}

// ─── Application State ───────────────────────────────────────────────────────

interface AppState {
  staff: StaffMember[];
  clients: Client[];
  projects: Project[];
  logs: DailyLog[];
  comments: ClientComment[];
  payments: Payment[];
  notifications: Notification[];
  documents: Document[];

  loading: boolean;
  error: string | null;
}

// ─── Application Actions ─────────────────────────────────────────────────────

interface AppActions {
  refresh: () => Promise<void>;

  addStaff: (
    s: Omit<
      StaffMember,
      "id" | "initials" | "_count" | "joinDate"
    > & {
      password?: string;
    }
  ) => Promise<{
    temporaryPassword?: string;
    invited?: boolean;
  }>;

  updateStaff: (
    id: string,
    patch: Partial<StaffMember> & {
      password?: string;
      currentPassword?: string;
      resetPassword?: boolean;
    }
  ) => Promise<{
    temporaryPassword?: string;
  }>;

  removeStaff: (
    id: string
  ) => Promise<void>;

  addClient: (
    c: Omit<
      Client,
      "id" | "createdAt" | "projects"
    >
  ) => Promise<void>;

  updateClient: (
    id: string,
    patch: Partial<Client>
  ) => Promise<void>;

  removeClient: (
    id: string
  ) => Promise<void>;

  addProject: (p: {
    name: string;
    clientId: string;
    location: string;
    description?: string;
    architectId?: string;
    supervisorId?: string;
    startDate: string;
    dueDate: string;
    budget: number;
    priority: Priority;
  }) => Promise<void>;

  updateProject: (
    id: string,
    patch: Partial<Project>
  ) => Promise<void>;

  removeProject: (
    id: string
  ) => Promise<void>;

  reassignProject: (
    projectId: string,
    toArchitectId: string,
    reason: string
  ) => Promise<void>;

  addLog: (l: {
    projectId: string;
    workCompleted: string;
    challenges: string;
    pendingWork: string;
    nextActions: string;
    progress: number;
  }) => Promise<{ id: string }>;

  addComment: (c: {
    projectId: string;
    clientId: string;
    author: string;
    content: string;
    type: CommentType;
  }) => Promise<void>;

  resolveComment: (
    id: string
  ) => Promise<void>;

  addPayment: (p: {
    projectId: string;
    amount: number;
    date: string;
    reference?: string;
    note?: string;
  }) => Promise<void>;

  addInvoice: (p: {
    projectId: string;
    amount: number;
    date: string;
    reference?: string;
    note?: string;
  }) => Promise<void>;

  markNotificationRead: (
    id: string
  ) => Promise<void>;

  uploadDocument: (
    projectId: string,
    file: File,
    category?: string
  ) => Promise<void>;

  removeDocument: (
    id: string
  ) => Promise<void>;

  toggleDocumentVisibility: (
    id: string,
    clientVisible: boolean
  ) => Promise<void>;

  uploadAvatar: (
    file: File
  ) => Promise<void>;

  removeAvatar: () => Promise<void>;
}

// ─── Context ─────────────────────────────────────────────────────────────────

const Ctx = createContext<
  (AppState & AppActions) | null
>(null);

// ─── Provider ────────────────────────────────────────────────────────────────

export function AppProvider({
  children,
}: {
  children: ReactNode;
}) {
  const {
    status,
    data: session,
  } = useSession();

  const isStaffSession =
    status === "authenticated" &&
    session?.user?.role !== "CLIENT";

  const [state, setState] =
    useState<AppState>({
      staff: [],
      clients: [],
      projects: [],
      logs: [],
      comments: [],
      payments: [],
      notifications: [],
      documents: [],
      loading: false,
      error: null,
    });

  /*
   * Prevent multiple refresh calls from executing
   * simultaneously. If a call comes in while one is already
   * running, we don't just hand back the in-flight promise as-is —
   * that promise may have been *started* before this caller's own
   * mutation (e.g. an avatar or document upload) finished writing to
   * the server, so its snapshot would be stale by the time it
   * resolves. Instead we mark `refreshQueued` and guarantee a fresh
   * follow-up run starts the moment the current one finishes, so
   * every caller is guaranteed data fetched *after* their own write.
   */
  const refreshInFlight =
    useRef<Promise<void> | null>(null);
  const refreshQueued = useRef(false);

  /*
   * True once the FIRST successful (or failed) load has completed.
   * Used to tell the initial page load (nothing on screen yet, a
   * full-page spinner is the right call) apart from every background
   * refresh after that (the 30s poll, window focus, post-mutation
   * refreshes) -- those should update data silently, never blank the
   * whole app back to a spinner. Before this existed, `loading` was set
   * true on every single refresh call, which made the entire app visibly
   * flash back to a full-page spinner every ~30 seconds (or more often
   * under frequent focus events) -- looked exactly like the page
   * reloading, because visually it was.
   */
  const hasLoadedOnce = useRef(false);

  // ─── Refresh all staff data ───────────────────────────────────────────────

  const refresh = useCallback(async (): Promise<void> => {
    if (!isStaffSession) {
      return;
    }

    if (refreshInFlight.current) {
      refreshQueued.current = true;
      return refreshInFlight.current;
    }

    const runOnce = (): Promise<void> => (async () => {
      try {
        if (!hasLoadedOnce.current) {
          setState((s) => ({
            ...s,
            loading: true,
            error: null,
          }));
        }

        /*
         * Each request is deliberately kept separate inside Promise.all.
         * If one endpoint returns HTTP 500, the improved apiFetch()
         * will now tell us EXACTLY which endpoint failed.
         */
        const [
          staff,
          clients,
          projects,
          logs,
          comments,
          payments,
          notificationResponse,
          documents,
        ] = await Promise.all([
          apiFetch<StaffMember[]>(
            "/api/staff"
          ),

          apiFetch<Client[]>(
            "/api/clients"
          ),

          apiFetch<Project[]>(
            "/api/projects"
          ),

          apiFetch<DailyLog[]>(
            "/api/logs"
          ),

          apiFetch<ClientComment[]>(
            "/api/comments"
          ),

          apiFetch<Payment[]>(
            "/api/payments"
          ),

          apiFetch<{
            notifications: Notification[];
            unreadCount: number;
          }>(
            "/api/notifications"
          ),

          apiFetch<Document[]>(
            "/api/documents"
          ),
        ]);

        const notifications =
          notificationResponse?.notifications ??
          [];

        setState({
          staff: staff ?? [],
          clients: clients ?? [],
          projects: projects ?? [],
          logs: logs ?? [],
          comments: comments ?? [],
          payments: payments ?? [],
          notifications,
          documents: documents ?? [],
          loading: false,
          error: null,
        });

        hasLoadedOnce.current = true;
      } catch (error) {
        console.error(
          "Failed to refresh application data:",
          error
        );

        const message =
          error instanceof Error
            ? error.message
            : "Failed to load application data.";

        if (!hasLoadedOnce.current) {
          // Initial load failed -- there's nothing on screen yet, so
          // showing the blocking error state is the right call, and this
          // also marks the "first load" attempt as resolved either way.
          setState((s) => ({
            ...s,
            loading: false,
            error: message,
          }));
          hasLoadedOnce.current = true;
        } else {
          // A background refresh failed after we already have real data
          // on screen (e.g. a transient network blip during the 30s
          // poll). Don't blank the whole app to an error screen over
          // this -- keep showing the last-known-good data and quietly
          // try again on the next cycle.
          setState((s) => ({
            ...s,
            loading: false,
          }));
        }
      }
    })();

    const promise = runOnce().then(() => {
      // If another caller asked for a refresh while this run was in
      // flight, their write may have landed after our fetch started —
      // run once more immediately so they get a fresh snapshot instead
      // of silently keeping whatever we just fetched.
      if (refreshQueued.current) {
        refreshQueued.current = false;
        refreshInFlight.current = runOnce().finally(() => {
          refreshInFlight.current = null;
        });
        return refreshInFlight.current;
      }
      refreshInFlight.current = null;
    });

    refreshInFlight.current = promise;

    return promise;
  }, [isStaffSession]);

  // ─── Initial data load ────────────────────────────────────────────────────

  useEffect(() => {
  if (status === "loading") {
    return;
  }

  if (isStaffSession) {
    void refresh();
  }
}, [status, isStaffSession, refresh]);

  // ─── Keep data fresh ──────────────────────────────────────────────────────

  useEffect(() => {
    if (!isStaffSession) {
      return;
    }

    // Passive refresh triggers (the 30s poll, window focus) are throttled
    // to at most once per 10s combined, no matter how many of either
    // fire -- window focus in particular can fire far more often than
    // once per 30s (alt-tabbing, notifications stealing focus, a second
    // monitor). This is purely about the BACKGROUND refresh triggers;
    // action-triggered refreshes (after submitting a log, adding a
    // client, etc.) always call refresh() directly and are never
    // throttled, so the person who just did something still sees it
    // immediately.
    const MIN_PASSIVE_REFRESH_GAP_MS = 10_000;
    let lastPassiveRefreshAt = 0;

    const passiveRefresh = () => {
      const now = Date.now();
      if (now - lastPassiveRefreshAt < MIN_PASSIVE_REFRESH_GAP_MS) {
        return;
      }
      lastPassiveRefreshAt = now;
      void refresh();
    };

    const refreshIfVisible = () => {
      if (
        document.visibilityState ===
          "visible" &&
        !isFilePickerOpen()
      ) {
        passiveRefresh();
      }
    };

    const interval = setInterval(
      refreshIfVisible,
      30000
    );

    const onFocus = () => {
      // If a native file picker was open, this focus event is the dialog
      // closing -- skip exactly this one refresh so React's onChange for
      // the file input gets a chance to run first. See
      // src/lib/file-picker-guard.ts.
      if (consumeFilePickerReturn()) {
        return;
      }
      passiveRefresh();
    };

    const onVisibilityChange = () => {
      refreshIfVisible();
    };

    window.addEventListener(
      "focus",
      onFocus
    );

    document.addEventListener(
      "visibilitychange",
      onVisibilityChange
    );

    return () => {
      clearInterval(interval);

      window.removeEventListener(
        "focus",
        onFocus
      );

      document.removeEventListener(
        "visibilitychange",
        onVisibilityChange
      );
    };
  }, [
    isStaffSession,
    refresh,
  ]);

  // ─── Staff ────────────────────────────────────────────────────────────────

  const addStaff = useCallback(
    async (
      data: Parameters<
        AppActions["addStaff"]
      >[0]
    ) => {
      const result =
        await apiFetch<{
          temporaryPassword?: string;
          invited?: boolean;
        }>("/api/staff", {
          method: "POST",
          body: JSON.stringify({
            ...data,
            role: data.role.toUpperCase(),
          }),
        });

      await refresh();

      return result;
    },
    [refresh]
  );

  const updateStaff = useCallback(
    async (
      id: string,
      patch: Parameters<
        AppActions["updateStaff"]
      >[1]
    ) => {
      const result =
        await apiFetch<{
          temporaryPassword?: string;
        }>(`/api/staff/${id}`, {
          method: "PATCH",
          body: JSON.stringify(patch),
        });

      await refresh();

      return result;
    },
    [refresh]
  );

  const removeStaff = useCallback(
    async (id: string) => {
      await apiFetch(
        `/api/staff/${id}`,
        {
          method: "DELETE",
        }
      );

      await refresh();
    },
    [refresh]
  );

  // ─── Clients ──────────────────────────────────────────────────────────────

  const addClient = useCallback(
    async (
      data: Parameters<
        AppActions["addClient"]
      >[0]
    ) => {
      await apiFetch(
        "/api/clients",
        {
          method: "POST",
          body: JSON.stringify(data),
        }
      );

      await refresh();
    },
    [refresh]
  );

  const updateClient = useCallback(
    async (
      id: string,
      patch: Partial<Client>
    ) => {
      await apiFetch(
        `/api/clients/${id}`,
        {
          method: "PATCH",
          body: JSON.stringify(patch),
        }
      );

      await refresh();
    },
    [refresh]
  );

  const removeClient = useCallback(
    async (id: string) => {
      await apiFetch(
        `/api/clients/${id}`,
        {
          method: "DELETE",
        }
      );

      await refresh();
    },
    [refresh]
  );

  // ─── Projects ─────────────────────────────────────────────────────────────

  const addProject = useCallback(
    async (
      data: Parameters<
        AppActions["addProject"]
      >[0]
    ) => {
      await apiFetch(
        "/api/projects",
        {
          method: "POST",
          body: JSON.stringify({
            ...data,
            priority:
              data.priority.toUpperCase(),
          }),
        }
      );

      await refresh();
    },
    [refresh]
  );

  const updateProject = useCallback(
    async (
      id: string,
      patch: Partial<Project>
    ) => {
      await apiFetch(
        `/api/projects/${id}`,
        {
          method: "PATCH",
          body: JSON.stringify(patch),
        }
      );

      await refresh();
    },
    [refresh]
  );

  const removeProject = useCallback(
    async (id: string) => {
      await apiFetch(
        `/api/projects/${id}`,
        {
          method: "DELETE",
        }
      );

      await refresh();
    },
    [refresh]
  );

  const reassignProject =
    useCallback(
      async (
        projectId: string,
        toArchitectId: string,
        reason: string
      ) => {
        await apiFetch(
          `/api/projects/${projectId}/reassign`,
          {
            method: "POST",
            body: JSON.stringify({
              toArchitectId,
              reason,
            }),
          }
        );

        await refresh();
      },
      [refresh]
    );

  // ─── Daily Logs ───────────────────────────────────────────────────────────

  const addLog = useCallback(
    async (
      data: Parameters<
        AppActions["addLog"]
      >[0]
    ) => {
      const created = await apiFetch<{ id: string }>(
        "/api/logs",
        {
          method: "POST",
          body: JSON.stringify(data),
        }
      );

      await refresh();

      return created;
    },
    [refresh]
  );

  // ─── Comments ─────────────────────────────────────────────────────────────

  const addComment = useCallback(
    async (
      data: Parameters<
        AppActions["addComment"]
      >[0]
    ) => {
      await apiFetch(
        "/api/comments",
        {
          method: "POST",
          body: JSON.stringify({
            ...data,
            type:
              data.type.toUpperCase(),
          }),
        }
      );

      await refresh();
    },
    [refresh]
  );

  const resolveComment = useCallback(
    async (id: string) => {
      await apiFetch(
        `/api/comments/${id}/resolve`,
        {
          method: "POST",
        }
      );

      await refresh();
    },
    [refresh]
  );

  // ─── Payments ─────────────────────────────────────────────────────────────

  const addPayment = useCallback(
    async (
      data: Parameters<
        AppActions["addPayment"]
      >[0]
    ) => {
      await apiFetch(
        "/api/payments",
        {
          method: "POST",
          body: JSON.stringify(data),
        }
      );

      await refresh();
    },
    [refresh]
  );

  const addInvoice = useCallback(
    async (
      data: Parameters<
        AppActions["addInvoice"]
      >[0]
    ) => {
      await apiFetch(
        "/api/invoices",
        {
          method: "POST",
          body: JSON.stringify(data),
        }
      );

      await refresh();
    },
    [refresh]
  );

  // ─── Notifications ───────────────────────────────────────────────────────

  const markNotificationRead =
    useCallback(
      async (id: string) => {
        await apiFetch(
          `/api/notifications/${id}`,
          {
            method: "PATCH",
          }
        );

        setState((s) => ({
          ...s,
          notifications:
            s.notifications.map(
              (notification) =>
                notification.id === id
                  ? {
                      ...notification,
                      read: true,
                    }
                  : notification
            ),
        }));
      },
      []
    );

  // ─── Document Upload ──────────────────────────────────────────────────────

  const uploadDocument =
    useCallback(
      async (
        projectId: string,
        file: File,
        category = "OTHER"
      ): Promise<void> => {
        if (!projectId) {
          throw new Error(
            "A project must be selected before uploading."
          );
        }

        if (!(file instanceof File)) {
          throw new Error(
            "Invalid file selected."
          );
        }

        if (file.size === 0) {
          throw new Error(
            `"${file.name}" is empty.`
          );
        }

        console.log(
          "Starting document upload:",
          {
            projectId,
            fileName: file.name,
            fileSize: file.size,
            mimeType: file.type,
            category,
          }
        );

        const formData =
          new FormData();

        formData.append(
          "file",
          file,
          file.name
        );

        formData.append(
          "projectId",
          projectId
        );

        formData.append(
          "category",
          category
        );

        let response: Response;

        try {
          response = await fetch(
            "/api/documents",
            {
              method: "POST",
              body: formData,
              credentials:
                "same-origin",
              cache: "no-store",
            }
          );
        } catch (error) {
          console.error(
            "Document upload network error:",
            error
          );

          throw new Error(
            "Could not connect to the document upload service."
          );
        }

        const contentType =
          response.headers.get(
            "content-type"
          ) || "";

        let result: unknown = null;

        if (
          contentType.includes(
            "application/json"
          )
        ) {
          result = await response
            .json()
            .catch(() => null);
        } else {
          const text =
            await response
              .text()
              .catch(() => "");

          result = {
            error:
              text ||
              `Upload failed with HTTP ${response.status}`,
          };
        }

        console.log(
          "Document upload response:",
          {
            status: response.status,
            result,
          }
        );

        if (!response.ok) {
          if (
            response.status === 401
          ) {
            throw new Error(
              "Your session has expired. Please log in again."
            );
          }

          if (
            response.status === 403
          ) {
            throw new Error(
              "You do not have permission to upload documents to this project."
            );
          }

          if (
            response.status === 413
          ) {
            throw new Error(
              "The file is too large to upload."
            );
          }

          let message =
            `Upload failed with HTTP ${response.status}`;

          if (
            typeof result ===
              "object" &&
            result !== null
          ) {
            const body =
              result as Record<
                string,
                unknown
              >;

            if (
              typeof body.error ===
              "string"
            ) {
              message =
                body.error;
            } else if (
              typeof body.message ===
              "string"
            ) {
              message =
                body.message;
            }
          }

          throw new Error(message);
        }

        if (
          typeof result !==
            "object" ||
          result === null ||
          !("id" in result)
        ) {
          console.error(
            "Upload response did not contain a document ID:",
            result
          );

          throw new Error(
            "The server accepted the upload but did not return a document record."
          );
        }

        console.log(
          "Document uploaded successfully:",
          result
        );

        await refresh();
      },
      [refresh]
    );

  // ─── Documents ────────────────────────────────────────────────────────────

  const removeDocument =
    useCallback(
      async (id: string) => {
        await apiFetch(
          `/api/documents/${id}`,
          {
            method: "DELETE",
          }
        );

        await refresh();
      },
      [refresh]
    );

  const toggleDocumentVisibility =
    useCallback(
      async (
        id: string,
        clientVisible: boolean
      ) => {
        await apiFetch(
          `/api/documents/${id}`,
          {
            method: "PATCH",
            body: JSON.stringify({
              clientVisible,
            }),
          }
        );

        await refresh();
      },
      [refresh]
    );

  // ─── Avatar ───────────────────────────────────────────────────────────────

  const uploadAvatar = useCallback(
    async (file: File) => {
      if (!(file instanceof File)) {
        throw new Error(
          "Invalid file selected."
        );
      }

      const form =
        new FormData();

      form.append(
        "file",
        file,
        file.name
      );

      const res =
        await fetch(
          "/api/users/me/avatar",
          {
            method: "POST",
            body: form,
            credentials:
              "same-origin",
            cache: "no-store",
          }
        );

      if (!res.ok) {
        const contentType =
          res.headers.get(
            "content-type"
          ) || "";

        let message =
          `Avatar upload failed with HTTP ${res.status}`;

        if (
          contentType.includes(
            "application/json"
          )
        ) {
          const err =
            await res
              .json()
              .catch(() => null);

          if (
            err &&
            typeof err ===
              "object"
          ) {
            const body =
              err as Record<
                string,
                unknown
              >;

            if (
              typeof body.error ===
              "string"
            ) {
              message =
                body.error;
            } else if (
              typeof body.message ===
              "string"
            ) {
              message =
                body.message;
            }
          }
        }

        throw new Error(message);
      }

      // Patch local state immediately from the response so the new
      // photo shows up right away, instead of waiting on the full
      // 8-endpoint refresh() round-trip. refresh() below still runs
      // to reconcile everything else, but the photo itself no longer
      // depends on its timing.
      const updated = (await res.json()) as { id: string; avatarUrl: string | null };
      setState((s) => ({
        ...s,
        staff: s.staff.map((member) =>
          member.id === updated.id ? { ...member, avatarUrl: updated.avatarUrl } : member
        ),
      }));

      await refresh();
    },
    [refresh]
  );

  const removeAvatar =
    useCallback(
      async () => {
        await apiFetch(
          "/api/users/me/avatar",
          {
            method: "DELETE",
          }
        );

        const myId = session?.user?.id;
        if (myId) {
          setState((s) => ({
            ...s,
            staff: s.staff.map((member) =>
              member.id === myId ? { ...member, avatarUrl: null } : member
            ),
          }));
        }

        await refresh();
      },
      [refresh, session?.user?.id]
    );

  // ─── Provider ─────────────────────────────────────────────────────────────

  return (
    <Ctx.Provider
      value={{
        ...state,

        refresh,

        addStaff,
        updateStaff,
        removeStaff,

        addClient,
        updateClient,
        removeClient,

        addProject,
        updateProject,
        removeProject,
        reassignProject,

        addLog,

        addComment,
        resolveComment,

        addPayment,
        addInvoice,

        markNotificationRead,

        uploadDocument,
        removeDocument,
        toggleDocumentVisibility,

        uploadAvatar,
        removeAvatar,
      }}
    >
      {children}
    </Ctx.Provider>
  );
}

// ─── Hook ────────────────────────────────────────────────────────────────────

export function useStore() {
  const ctx = useContext(Ctx);

  if (!ctx) {
    throw new Error(
      "useStore must be used within AppProvider"
    );
  }

  return ctx;
}
'@
Write-PatchFile "src/store/app-store.tsx" $content

Write-Host ""
Write-Host "Patch 24 applied. No schema change -- just run:" -ForegroundColor Green
Write-Host "  npm run build"
Write-Host ""
Write-Host "To test: try deleting the same staff member that failed before -- should now either delete cleanly" -ForegroundColor Green
Write-Host "or give a clear reason. Try creating a project with a 1-character location -- you should now see" -ForegroundColor Green
Write-Host "the actual validation reason instead of a generic failure message." -ForegroundColor Green
