<#
  Architect Hub -- patch 36: skips redundant type-checking and linting
  during the production build itself, targeting the most likely
  remaining EAGAIN cause.
  Generated by Claude -- 2026-08-22

  The crash is now confirmed happening specifically in jest-worker
  (Next.js's internal worker library), which defaults to spawning
  SEPARATE CHILD PROCESSES (not threads) for several build phases --
  type-checking, linting, and static page generation each get their
  own worker spawn. cpus: 1 reduces the pool to one, but even ONE
  additional process is apparently too many for this account's process
  limit -- a tighter constraint than a simple pool-size setting alone
  can fully work around.

  This targets the most likely culprit: type-checking typically runs
  very early in the "Creating an optimized production build" phase,
  matching exactly where the crash has been occurring. Your CI pipeline
  already runs full type-checking (npx tsc --noEmit) and linting
  (npm run lint) as dedicated steps on every push, before this code is
  ever deployed -- doing either again during the build here is
  redundant work, and each one spawns its own worker process. Skipping
  them removes two whole spawn points at once. This does NOT weaken
  your actual safety net -- CI still catches real type/lint errors
  before they ever reach this stage.

  HONEST EXPECTATION SETTING: if the build progresses further and hits
  another EAGAIN during a LATER phase (most likely "Generating static
  pages", which also uses worker-based parallelism and hasn't been
  reached yet in any attempt so far), that would mean this account's
  process limit is tighter than any Next.js config can work around, and
  the real fix becomes building somewhere with more resources (GitHub
  Actions, your own machine) and deploying the finished, pre-built
  output to HostPinnacle rather than building on the constrained server
  at all. Worth knowing now rather than being surprised by it.

  next.config.js verified loading correctly, 62/62 tests on your
  machine (same 3 sandbox-only failures here, confirmed unrelated in
  every earlier patch).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-36.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 36 (skip build-time type-check/lint)..." -ForegroundColor Cyan

# --- [MOD] next.config.js ---
$content = @'
/** @type {import('next').NextConfig} */
const isProd = process.env.NODE_ENV === "production";

// Derived from the same env vars src/lib/s3.ts actually uses, so this
// always matches whatever bucket/region is really configured at deploy
// time -- a hardcoded guess here would silently break every document
// thumbnail and avatar in production the moment it didn't match the
// real bucket, and (like the CSP itself) nothing in dev would ever
// reveal that mismatch since this header is skipped in dev entirely.
const s3ImgSrc =
  process.env.AWS_S3_BUCKET && process.env.AWS_REGION
    ? `https://${process.env.AWS_S3_BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com`
    : ""; // S3 not configured -- falls back to local disk storage, nothing to allowlist

const nextConfig = {
  reactStrictMode: true,
  // Type errors and lint issues are already caught by CI
  // (.github/workflows/ci.yml runs `npx tsc --noEmit` and `npm run
  // lint` as dedicated steps on every push) before this code is ever
  // deployed -- redoing either check during the production build here
  // is genuinely redundant, and each one spawns its own jest-worker
  // child process (see the cpus/workerThreads comment below for why
  // that matters specifically on resource-constrained shared hosting).
  // This is the standard, documented way to skip them -- NOT a way to
  // let real errors slip through, since CI still blocks on both.
  typescript: { ignoreBuildErrors: true },
  eslint: { ignoreDuringBuilds: true },
  // "standalone" output is what the Dockerfile (Railway/self-hosted
  // path) needs -- it produces a self-contained server.js with only the
  // dependencies each route actually uses. Vercel has its own packaging
  // system for serverless functions and doesn't want this: combined
  // with Vercel's build, it causes exactly the "Failed to collect page
  // data" error on API routes that touch Prisma. process.env.VERCEL is
  // set automatically by Vercel's build environment, so this correctly
  // targets each platform's own expectations without needing a manual
  // toggle.
  // "standalone" output is what the Dockerfile (Railway/self-hosted
  // path) needs. Vercel doesn't want it (see comment above). Shared
  // hosting environments with a managed Node.js app runner (e.g.
  // HostAfrica's DirectAdmin Node.js Selector) generally expect a plain
  // `next start` too -- standalone mode's server.js needs the static
  // assets and public folder manually copied alongside it (that's what
  // the Dockerfile's explicit COPY steps do), which most managed
  // Node.js hosting panels have no built-in way to do. Set
  // DISABLE_STANDALONE_BUILD=true on that kind of host to get a normal
  // build instead.
  ...(process.env.VERCEL || process.env.DISABLE_STANDALONE_BUILD === "true"
    ? {}
    : { output: "standalone" }),
  experimental: {
    serverActions: { allowedOrigins: ["localhost:3000"] },
    // Fixes "Error: EAGAIN ... ERR_WORKER_INIT_FAILED" during the build
    // step specifically on resource-constrained shared hosting (cPanel/
    // CloudLinux CageFS, like HostPinnacle) -- Next.js spawns many
    // parallel worker threads by default to speed up builds, which
    // exceeds the process/thread limit CageFS enforces per account.
    // Forces a single-threaded build instead. Applied everywhere, not
    // just conditionally for that host -- costs a little build time on
    // platforms with ample resources (Vercel/Railway), in exchange for
    // one fewer thing that can silently differ between environments.
    workerThreads: false,
    cpus: 1,
  },
  async headers() {
    if (!isProd) return []; // don't apply CSP/HSTS in dev — breaks HMR/Fast Refresh

    const csp = [
      "default-src 'self'",
      // 'unsafe-inline' is required here -- Next.js's App Router injects
      // inline hydration scripts (self.__next_f.push(...)) into every
      // page. Without this, a browser enforcing this CSP blocks those
      // scripts and the app fails to hydrate at all -- blank page,
      // nothing interactive. This CSP header only activates in
      // production (see isProd above), so this had never actually been
      // exercised until now; dev mode always skips it.
      //
      // The "correct" alternative is a per-request nonce generated in
      // middleware instead of 'unsafe-inline'. That's deliberately NOT
      // done here: as of this Next.js version, nonce-based CSP is
      // broken specifically for the Turbopack + output:"standalone"
      // combination this app uses -- Next's own injected scripts don't
      // receive the nonce at all, so the app breaks the same way either
      // way. 'unsafe-inline' is also Next.js's own documented
      // recommendation for apps not implementing per-request nonces.
      // Revisit once that upstream bug is fixed.
      "script-src 'self' 'unsafe-inline'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data:" + (s3ImgSrc ? ` ${s3ImgSrc}` : ""),
      "font-src 'self' data:",
      "connect-src 'self'",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "object-src 'none'",
    ].join("; ");

    return [
      {
        source: "/(.*)",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
        ],
      },
    ];
  },
};
module.exports = nextConfig;
'@
Write-PatchFile "next.config.js" $content

Write-Host ""
Write-Host "Patch 36 applied. Push, pull on the server, then run:" -ForegroundColor Green
Write-Host "  npm run build"
Write-Host "If it fails again with EAGAIN at a LATER point (past type-checking), tell me exactly" -ForegroundColor Yellow
Write-Host "what phase it reached -- that changes the next fix from a config tweak to a build-elsewhere strategy." -ForegroundColor Yellow
