<#
  Architect Hub -- patch 20: true permanent project deletion (separate
  from archiving, which was the only option before).
  Generated by Claude -- 2026-08-22

  NEW: POST /api/projects/[id]/permanent-delete -- irreversibly deletes
  a project and everything cascading from it (11 related record types:
  daily logs, documents, payments, invoices, comments, tasks,
  milestones, phases, assignment history). Two real safeguards, not
  just a UI confirm():
    1. The project must already be archived first -- no direct path
       from an active project to permanent deletion.
    2. The request must include the project's EXACT sheet number as
       confirmation, checked server-side, not just client-side -- a
       misclick or stray API call can't trigger this.

  UI: "Delete permanently" button added next to "Restore" on the
  archived-projects page, opening a modal that requires typing the
  sheet number before the button even enables.

  Note: does not delete the underlying S3 files, only the database
  records referencing them -- see the comment in the route file for why
  that's an intentional tradeoff, not an oversight.

  Lint clean, 62/62 tests on your machine (same 3 sandbox-only failures
  here, confirmed unrelated in every earlier patch).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-20.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 20 (permanent delete)..." -ForegroundColor Cyan

# --- [NEW] src/app/api/projects/[id]/permanent-delete/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { isAdmin } from "@/lib/rbac";

/**
 * Permanently and irreversibly deletes a project and everything attached
 * to it -- daily logs, documents, payments, invoices, client comments,
 * tasks, milestones, phases, assignment history. All of that cascades
 * automatically via the FK constraints already defined in schema.prisma
 * (Cascade on every projectId relation) once prisma.project.delete()
 * actually runs.
 *
 * This is deliberately much harder to trigger by accident than the
 * existing DELETE /api/projects/[id], which only archives (soft-delete,
 * fully reversible via /unarchive):
 *
 *   1. The project must already be archived first -- no direct path from
 *      an active project straight to permanent deletion.
 *   2. The request body must include the project's exact sheetNo as
 *      confirmation, not just an admin session -- protects against a
 *      misclick or a stray API call, mirroring the "type the repo name"
 *      pattern used by GitHub/etc. for equally irreversible actions.
 *
 * Note: this does NOT delete the underlying files from S3 -- Document
 * rows referencing S3 keys are removed from the database, but the
 * objects themselves are left in the bucket. Acceptable tradeoff here
 * (avoids this endpoint also depending on S3 being reachable to
 * complete a database operation), but means orphaned S3 objects will
 * accumulate for permanently-deleted projects. Worth a periodic S3
 * lifecycle/cleanup policy if that matters at your storage volume.
 */
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await auth();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }
  if (!isAdmin(session)) {
    return NextResponse.json(
      { error: "Only administrators can permanently delete a project" },
      { status: 403 }
    );
  }

  const { id } = await params;

  const existing = await prisma.project.findUnique({
    where: { id },
    select: { id: true, name: true, sheetNo: true, archivedAt: true },
  });

  if (!existing) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  if (!existing.archivedAt) {
    return NextResponse.json(
      { error: "Only an archived project can be permanently deleted. Archive it first." },
      { status: 400 }
    );
  }

  const body = await req.json().catch(() => null);
  const confirmSheetNo = (body?.confirmSheetNo as string | undefined)?.trim();

  if (confirmSheetNo !== existing.sheetNo) {
    return NextResponse.json(
      { error: "Confirmation text does not match the project's sheet number." },
      { status: 400 }
    );
  }

  try {
    await prisma.project.delete({ where: { id } });
  } catch (error) {
    console.error("Failed to permanently delete project:", error);
    return NextResponse.json(
      { error: "Failed to permanently delete project" },
      { status: 500 }
    );
  }

  try {
    await prisma.notification.create({
      data: {
        userId: session.user.id,
        message: `Project "${existing.name}" (${existing.sheetNo}) was permanently deleted`,
        type: "SUCCESS",
      },
    });
  } catch (error) {
    console.error("Permanent-delete notification failed:", error);
  }

  return NextResponse.json({ success: true });
}

'@
Write-PatchFile "src/app/api/projects/[id]/permanent-delete/route.ts" $content

# --- [MOD] src/app/projects/archived/page.tsx ---
$content = @'
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { AppShell } from "@/components/layout/app-shell";
import { Card } from "@/components/ui/card";
import { Modal } from "@/components/ui/modal";
import { ArrowLeft, ArchiveRestore, Trash2, AlertTriangle } from "lucide-react";

interface ArchivedProject {
  id: string;
  sheetNo: string;
  name: string;
  location: string;
  archivedAt: string;
  client?: { name: string };
}

/**
 * DELETE /api/projects/[id] soft-deletes (sets archivedAt) rather than
 * removing data — see that route. Without this page, an archived project
 * would be permanently invisible in the UI with no way back short of a
 * direct database edit, since PATCH refuses to touch archived projects.
 */
export default function ArchivedProjectsPage() {
  const { data: session } = useSession();
  const isAdmin = session?.user?.role === "ADMIN";
  const [projects, setProjects] = useState<ArchivedProject[] | null>(null);
  const [error, setError] = useState("");
  const [restoringId, setRestoringId] = useState<string | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<ArchivedProject | null>(null);
  const [confirmText, setConfirmText] = useState("");
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState("");

  async function load() {
    try {
      const res = await fetch("/api/projects?archived=true");
      if (!res.ok) throw new Error((await res.json()).error || "Failed to load archived projects");
      setProjects(await res.json());
    } catch (err) {
      setError((err as Error).message);
    }
  }

  useEffect(() => {
    if (isAdmin) Promise.resolve().then(load);
  }, [isAdmin]);

  async function handleUnarchive(id: string, name: string) {
    if (!confirm(`Restore "${name}" to the active projects list?`)) return;
    setRestoringId(id);
    try {
      const res = await fetch(`/api/projects/${id}/unarchive`, { method: "POST" });
      if (!res.ok) throw new Error((await res.json()).error || "Failed to restore project");
      await load();
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setRestoringId(null);
    }
  }

  async function handlePermanentDelete() {
    if (!deleteTarget) return;
    setDeleting(true);
    setDeleteError("");
    try {
      const res = await fetch(`/api/projects/${deleteTarget.id}/permanent-delete`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ confirmSheetNo: confirmText }),
      });
      if (!res.ok) throw new Error((await res.json()).error || "Failed to delete project");
      setDeleteTarget(null);
      setConfirmText("");
      await load();
    } catch (err) {
      setDeleteError((err as Error).message);
    } finally {
      setDeleting(false);
    }
  }

  return (
    <AppShell>
      <div>
        <Link href="/projects" className="inline-flex items-center gap-1.5 text-muted hover:text-ink text-[12.5px] mb-3">
          <ArrowLeft size={14} />Back to projects
        </Link>
        <h1 className="font-display font-bold text-[20px] text-ink mb-1">Archived projects</h1>
        <p className="text-muted text-[12px] mb-5">Data is kept, not deleted — restore a project to bring it back to the active list.</p>

        {!isAdmin && <Card className="p-6 text-center text-muted text-[12.5px]">Only an admin can view archived projects.</Card>}

        {isAdmin && error && <p className="text-brick text-[13px] mb-3">{error}</p>}
        {isAdmin && !projects && !error && <p className="text-muted text-[13px]">Loading…</p>}
        {isAdmin && projects?.length === 0 && (
          <Card className="p-6 text-center text-muted text-[12.5px]">No archived projects.</Card>
        )}

        {isAdmin && projects && projects.length > 0 && (
          <Card className="divide-y divide-line overflow-hidden">
            {projects.map(p => (
              <div key={p.id} className="flex items-center justify-between px-4 py-3">
                <div className="min-w-0">
                  <div className="font-mono text-[11px] text-muted">{p.sheetNo}{p.client ? ` · ${p.client.name}` : ""}</div>
                  <div className="text-ink font-medium text-[13px] truncate">{p.name}</div>
                  <div className="text-muted text-[11px] mt-0.5">Archived {new Date(p.archivedAt).toLocaleDateString("en-KE", { dateStyle: "medium" })}</div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                <button
                  disabled={restoringId === p.id}
                  onClick={() => handleUnarchive(p.id, p.name)}
                  className="flex items-center gap-1.5 border border-line text-blueprint rounded-md px-3 py-1.5 text-[12px] font-medium hover:bg-blueprint-bg disabled:opacity-50 shrink-0"
                >
                  <ArchiveRestore size={14} />{restoringId === p.id ? "Restoring…" : "Restore"}
                </button>
                <button
                  onClick={() => { setDeleteTarget(p); setConfirmText(""); setDeleteError(""); }}
                  className="flex items-center gap-1.5 border border-brick/30 text-brick rounded-md px-3 py-1.5 text-[12px] font-medium hover:bg-brick-bg shrink-0"
                >
                  <Trash2 size={14} />Delete permanently
                </button>
                </div>
              </div>
            ))}
          </Card>
        )}

        {/* PERMANENT DELETE CONFIRMATION */}
        <Modal
          open={!!deleteTarget}
          onClose={() => { setDeleteTarget(null); setConfirmText(""); setDeleteError(""); }}
          title="Delete project permanently"
        >
          <div className="flex flex-col gap-3">
            <div className="flex items-start gap-2.5 rounded-md border border-brick/20 bg-brick-bg p-3">
              <AlertTriangle size={16} className="text-brick mt-0.5 shrink-0" />
              <p className="text-[12.5px] text-ink">
                This permanently deletes <span className="font-medium">{deleteTarget?.name}</span> ({deleteTarget?.sheetNo}) and everything attached to it — daily logs, documents, payments, invoices, client comments, and all history. <span className="font-medium">This cannot be undone.</span> Consider whether &quot;Restore&quot; is what you actually want instead.
              </p>
            </div>

            <label className="text-[12px] text-muted">
              Type <span className="font-mono font-medium text-ink">{deleteTarget?.sheetNo}</span> to confirm
            </label>
            <input
              type="text"
              value={confirmText}
              onChange={(e) => setConfirmText(e.target.value)}
              placeholder={deleteTarget?.sheetNo}
              className="rounded-md border border-line px-3 py-2 text-[13px] font-mono focus:outline-none focus:ring-2 focus:ring-brick/30"
            />

            {deleteError && <p className="text-brick text-[12px]">{deleteError}</p>}

            <div className="flex justify-end gap-2 pt-1 border-t border-line mt-1">
              <button
                type="button"
                onClick={() => { setDeleteTarget(null); setConfirmText(""); setDeleteError(""); }}
                className="px-4 py-2 rounded-md text-[12.5px] border border-line text-muted hover:bg-vellum"
              >
                Cancel
              </button>
              <button
                type="button"
                disabled={deleting || confirmText !== deleteTarget?.sheetNo}
                onClick={handlePermanentDelete}
                className="px-4 py-2 rounded-md text-[12.5px] bg-brick text-white font-medium hover:opacity-90 disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {deleting ? "Deleting…" : "Delete permanently"}
              </button>
            </div>
          </div>
        </Modal>
      </div>
    </AppShell>
  );
}

'@
Write-PatchFile "src/app/projects/archived/page.tsx" $content

Write-Host ""
Write-Host "Patch 20 applied. No schema change this time -- just run:" -ForegroundColor Green
Write-Host "  npm run build"
Write-Host ""
Write-Host "To test: archive a test project first (never a real one), then go to /projects/archived" -ForegroundColor Green
Write-Host "and try Delete permanently -- the button stays disabled until you type the exact sheet number." -ForegroundColor Green
