<#
  Architect Hub -- patch 7: full-app audit fixes (Senior Architect
  consistency gaps found by review, not by you reporting a bug).
  Generated by Claude -- 2026-08-22

  1. dashboard/page.tsx: all 12 "isAdmin ? firm-wide : personal" branches
     now also apply to Senior Architects (revenue KPI, all-projects view,
     weekly charts, etc.) -- these were left admin-only even though the
     underlying data (rbac.ts) was already firm-wide for that role.
  2. dashboard/page.tsx: "missing submissions" count no longer counts
     Senior Architects as staff expected to submit a daily log (only
     ARCHITECT does hands-on site reporting).
  3. projects/[id]/takeover/page.tsx: the take-over confirm button now
     also shows for Senior Architects -- it calls the same
     /api/projects/[id]/reassign endpoint that already accepts them
     (patch 2), so this was a frontend gate stricter than the backend.

  Tests re-run clean after these changes (44/44) before this was sent.

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-7.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 7 (audit fixes)..." -ForegroundColor Cyan

# --- [MOD] src/app/dashboard/page.tsx ---
$content = @'
"use client";

import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { Card } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import {
  useStore,
  formatKsh,
  commentTypeLabel,
} from "@/store/app-store";
import { useSession } from "next-auth/react";
import {
  AlertTriangle,
  Bell,
  CheckCircle,
} from "lucide-react";
import { Avatar } from "@/components/ui/avatar";

export default function DashboardPage() {
  const {
    projects = [],
    staff = [],
    logs = [],
    comments = [],
    payments = [],
    notifications = [],
    markNotificationRead,
  } = useStore();

  const { data: session } = useSession();

  const isAdmin = session?.user?.role === "ADMIN";
  const isSeniorArchitect = session?.user?.role === "SENIOR_ARCHITECT";
  // Every hasFirmWideView branch below this point is about "firm-wide dashboard
  // view vs. personal view" -- not an admin-only action -- and senior
  // architects have the same firm-wide data access (see rbac.ts), so they
  // get the same view here too.
  const hasFirmWideView = isAdmin || isSeniorArchitect;

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  const dayKey = (value: string | Date) => {
    const date = new Date(value);

    if (Number.isNaN(date.getTime())) {
      return "";
    }

    return date.toISOString().split("T")[0];
  };

  const safeNumber = (value: unknown, fallback = 0): number => {
    const number = Number(value);

    return Number.isFinite(number) ? number : fallback;
  };

  const percentage = (part: number, total: number): number => {
    if (!Number.isFinite(part) || !Number.isFinite(total) || total <= 0) {
      return 0;
    }

    const result = (part / total) * 100;

    if (!Number.isFinite(result)) {
      return 0;
    }

    return Math.min(100, Math.max(0, Math.round(result * 10) / 10));
  };

  // ---------------------------------------------------------------------------
  // Current date / logs
  // ---------------------------------------------------------------------------

  const now = new Date();
  const today = dayKey(now);

  const todayLogs = logs.filter(
    (log) => dayKey(log.date) === today
  );

  // ---------------------------------------------------------------------------
  // Project health
  // ---------------------------------------------------------------------------

  const delayed = projects.filter(
    (project) => project.status === "DELAYED"
  );

  const atRisk = projects.filter(
    (project) => project.status === "AT_RISK"
  );

  const onTrack = projects.filter(
    (project) => project.status === "ON_TRACK"
  );

  const projectCount = projects.length;

  /*
   * IMPORTANT:
   * These values are always finite numbers.
   * This prevents React/SVG from receiving NaN.
   */
  const onTrackPct = percentage(onTrack.length, projectCount);
  const atRiskPct = percentage(atRisk.length, projectCount);
  const delayedPct = percentage(delayed.length, projectCount);

  // ---------------------------------------------------------------------------
  // Notifications / comments
  // ---------------------------------------------------------------------------

  const unread = notifications.filter(
    (notification) => !notification.read
  );

  const unresolved = comments.filter(
    (comment) => !comment.resolvedAt
  );

  // ---------------------------------------------------------------------------
  // Finance
  // ---------------------------------------------------------------------------

  const totalContractValue = projects.reduce(
  (sum, project) =>
    sum + safeNumber(project.budget),
  0
);

const totalRevenue = projects.reduce(
  (sum, project) =>
    sum + safeNumber(project.paid),
  0
);

const totalOutstanding = Math.max(
  totalContractValue - totalRevenue,
  0
);

  // ---------------------------------------------------------------------------
  // Missing daily submissions
  // ---------------------------------------------------------------------------

  // Daily logs are hands-on site reporting -- only ARCHITECT does that.
  // ADMIN and SENIOR_ARCHITECT are oversight roles and aren't expected to
  // submit one, same reasoning as the ADMIN exclusion that was already here.
  const loggingStaffCount = staff.filter(
    (member) => member.role === "ARCHITECT"
  ).length;

  const missingSubmissions = hasFirmWideView
    ? Math.max(0, loggingStaffCount - todayLogs.length)
    : 0;

  // ---------------------------------------------------------------------------
  // Weekly logs
  // ---------------------------------------------------------------------------

  const mondayOffset = (now.getDay() + 6) % 7;

  const startOfWeek = new Date(now);

  startOfWeek.setHours(0, 0, 0, 0);
  startOfWeek.setDate(
    now.getDate() - mondayOffset
  );

  const weekDayKeys = Array.from(
    { length: 7 },
    (_, index) => {
      const date = new Date(startOfWeek);

      date.setDate(
        startOfWeek.getDate() + index
      );

      return dayKey(date);
    }
  );

  const weeklyLogs = weekDayKeys.map(
    (key) =>
      logs.filter(
        (log) => dayKey(log.date) === key
      ).length
  );

  const maxWeeklyLogs = Math.max(
    ...weeklyLogs,
    1
  );

  const todayIndex = mondayOffset;

  // ---------------------------------------------------------------------------
  // Revenue trend
  // ---------------------------------------------------------------------------

  const monthLabel = (date: Date) =>
    `${date.getFullYear()}-${date.getMonth()}`;

  const monthBuckets = Array.from(
    { length: 6 },
    (_, index) => {
      const date = new Date(
        now.getFullYear(),
        now.getMonth() - (5 - index),
        1
      );

      return {
        key: monthLabel(date),
        total: 0,
      };
    }
  );

  payments.forEach((payment) => {
    const paymentDate = new Date(payment.date);

    if (Number.isNaN(paymentDate.getTime())) {
      return;
    }

    const key = monthLabel(paymentDate);

    const bucket = monthBuckets.find(
      (item) => item.key === key
    );

    if (bucket) {
      bucket.total += safeNumber(payment.amount);
    }
  });

  const maxMonthTotal = Math.max(
    ...monthBuckets.map((bucket) =>
      safeNumber(bucket.total)
    ),
    1
  );

  const trendPoints = monthBuckets.map(
    (bucket, index) => ({
      x:
        4 +
        index *
          (200 / (monthBuckets.length - 1)),
      y:
        64 -
        (safeNumber(bucket.total) /
          maxMonthTotal) *
          52,
    })
  );

  const trendPolyline = trendPoints
    .map(
      (point) =>
        `${point.x},${point.y}`
    )
    .join(" ");

  const trendArea =
    trendPoints.length > 0
      ? `${trendPolyline} ${
          trendPoints[
            trendPoints.length - 1
          ].x
        },68 ${trendPoints[0].x},68`
      : "";

  const lastMonthTotal =
    monthBuckets[
      monthBuckets.length - 1
    ]?.total ?? 0;

  const prevMonthTotal =
    monthBuckets[
      monthBuckets.length - 2
    ]?.total ?? 0;

  const revenueChangePct =
    prevMonthTotal > 0
      ? Math.round(
          ((lastMonthTotal -
            prevMonthTotal) /
            prevMonthTotal) *
            1000
        ) / 10
      : lastMonthTotal > 0
        ? 100
        : 0;

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <AppShell>
      <div>
        {/* ----------------------------------------------------------------- */}
        {/* Header */}
        {/* ----------------------------------------------------------------- */}

        <div className="flex items-start justify-between mb-5">
          <div>
            <h1 className="font-display font-bold text-[20px] text-ink">
              {hasFirmWideView
                ? "Admin Dashboard"
                : "My Dashboard"}
            </h1>

            <p className="text-muted text-[12px] mt-0.5">
              {now.toLocaleDateString(
                "en-KE",
                {
                  weekday: "long",
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                }
              )}{" "}
              — {projects.length}{" "}
              {hasFirmWideView
                ? `active projects across ${loggingStaffCount} staff`
                : "projects assigned to you"}
            </p>
          </div>
        </div>

        {/* ----------------------------------------------------------------- */}
        {/* KPI ROW */}
        {/* ----------------------------------------------------------------- */}

        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-3.5">
          {/* Active projects */}

          <Card className="p-3.5">
            <div className="text-muted text-[11px]">
              Active projects
            </div>

            <div className="font-display font-bold text-[28px] text-ink mt-0.5">
              {projects.length}
            </div>

            <div className="text-moss text-[11px] mt-1">
              ↑ {onTrack.length} on track
            </div>
          </Card>

          {/* Revenue / comments */}

          {hasFirmWideView ? (
            <Card className="p-3.5">
              <div className="text-muted text-[11px]">
                Total revenue
              </div>

              <div className="font-mono font-medium text-[17px] text-ink mt-1">
                {formatKsh(totalRevenue)}
              </div>

              <div className="text-muted text-[11px] mt-1.5">
                Outstanding:{" "}
                {formatKsh(totalOutstanding)}
              </div>
            </Card>
          ) : (
            <Card className="p-3.5">
              <div className="text-muted text-[11px]">
                Unresolved client comments
              </div>

              <div className="font-display font-bold text-[28px] text-ochre mt-0.5">
                {unresolved.length}
              </div>

              <div className="text-muted text-[11px] mt-1">
                {delayed.length} delayed
              </div>
            </Card>
          )}

          {/* Daily logs */}

          <Card className="p-3.5">
            <div className="text-muted text-[11px]">
              {hasFirmWideView
                ? "Logs today"
                : "Your logs today"}
            </div>

            <div className="font-display font-bold text-[28px] text-ink mt-0.5">
              {todayLogs.length}
            </div>

            {hasFirmWideView ? (
              <div className="text-brick text-[11px] mt-1">
                {missingSubmissions} missing submissions
              </div>
            ) : (
              <div className="text-muted text-[11px] mt-1">
                Across your projects
              </div>
            )}
          </Card>

          {/* Admin comments */}

          {hasFirmWideView && (
            <Card className="p-3.5">
              <div className="text-muted text-[11px]">
                Unresolved client comments
              </div>

              <div className="font-display font-bold text-[28px] text-ochre mt-0.5">
                {unresolved.length}
              </div>

              <div className="text-muted text-[11px] mt-1">
                {delayed.length} delayed projects
              </div>
            </Card>
          )}
        </div>

        {/* ----------------------------------------------------------------- */}
        {/* CHARTS ROW */}
        {/* ----------------------------------------------------------------- */}

        <div
          className={`grid grid-cols-1 gap-3 mb-3.5 ${
            hasFirmWideView
              ? "lg:grid-cols-3"
              : "lg:grid-cols-2"
          }`}
        >
          {/* Project health */}

          <Card className="p-3.5">
            <div className="font-medium text-ink text-[12.5px] mb-3">
              Project health
            </div>

            <div className="flex items-center gap-4">
              <svg
                width="90"
                height="90"
                viewBox="0 0 36 36"
                aria-hidden="true"
              >
                {/* Background ring */}

                <circle
                  cx="18"
                  cy="18"
                  r="15.5"
                  fill="none"
                  stroke="#E6E9EA"
                  strokeWidth="5"
                  pathLength="100"
                />

                {/* On track */}

                {onTrackPct > 0 && (
                  <circle
                    cx="18"
                    cy="18"
                    r="15.5"
                    fill="none"
                    stroke="#2F7A5E"
                    strokeWidth="5"
                    strokeDasharray={`${onTrackPct} 100`}
                    strokeDashoffset="0"
                    strokeLinecap="butt"
                    pathLength="100"
                    transform="rotate(-90 18 18)"
                  />
                )}

                {/* At risk */}

                {atRiskPct > 0 && (
                  <circle
                    cx="18"
                    cy="18"
                    r="15.5"
                    fill="none"
                    stroke="#B07F1F"
                    strokeWidth="5"
                    strokeDasharray={`${atRiskPct} 100`}
                    strokeDashoffset={-onTrackPct}
                    strokeLinecap="butt"
                    pathLength="100"
                    transform="rotate(-90 18 18)"
                  />
                )}

                {/* Delayed */}

                {delayedPct > 0 && (
                  <circle
                    cx="18"
                    cy="18"
                    r="15.5"
                    fill="none"
                    stroke="#B5502E"
                    strokeWidth="5"
                    strokeDasharray={`${delayedPct} 100`}
                    strokeDashoffset={
                      -(onTrackPct + atRiskPct)
                    }
                    strokeLinecap="butt"
                    pathLength="100"
                    transform="rotate(-90 18 18)"
                  />
                )}
              </svg>

              <div className="flex flex-col gap-2 text-[11.5px]">
                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-sm bg-moss inline-block" />

                  <span className="text-ink font-medium">
                    {onTrack.length}
                  </span>

                  <span className="text-muted">
                    On track
                  </span>
                </div>

                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-sm bg-ochre inline-block" />

                  <span className="text-ink font-medium">
                    {atRisk.length}
                  </span>

                  <span className="text-muted">
                    At risk
                  </span>
                </div>

                <div className="flex items-center gap-2">
                  <span className="w-2 h-2 rounded-sm bg-brick inline-block" />

                  <span className="text-ink font-medium">
                    {delayed.length}
                  </span>

                  <span className="text-muted">
                    Delayed
                  </span>
                </div>
              </div>
            </div>
          </Card>

          {/* Weekly logs */}

          <Card className="p-3.5">
            <div className="font-medium text-ink text-[12.5px] mb-2">
              {hasFirmWideView
                ? "Daily logs this week"
                : "Your daily logs this week"}
            </div>

            <svg
              width="100%"
              height="70"
              viewBox="0 0 160 70"
              aria-hidden="true"
            >
              {weeklyLogs.map(
                (value, index) => {
                  const numericValue =
                    safeNumber(value);

                  const height =
                    numericValue === 0
                      ? 2
                      : Math.min(
                          56,
                          (numericValue /
                            maxWeeklyLogs) *
                            56
                        );

                  return (
                    <rect
                      key={index}
                      x={6 + index * 22}
                      y={64 - height}
                      width="14"
                      height={height}
                      fill={
                        index === todayIndex
                          ? "#2451C4"
                          : numericValue === 0
                            ? "#E6E9EA"
                            : "#B5D4F4"
                      }
                      rx="2"
                    />
                  );
                }
              )}
            </svg>

            <div className="flex justify-between text-[9.5px] text-muted font-mono px-1">
              {[
                "M",
                "T",
                "W",
                "T",
                "F",
                "S",
                "S",
              ].map((day, index) => (
                <span key={index}>
                  {day}
                </span>
              ))}
            </div>
          </Card>

          {/* Revenue trend */}

          {hasFirmWideView && (
            <Card className="p-3.5">
              <div className="flex justify-between items-center mb-2">
                <div className="font-medium text-ink text-[12.5px]">
                  Revenue trend
                </div>

                <div
                  className={`text-[11px] ${
                    revenueChangePct >= 0
                      ? "text-moss"
                      : "text-brick"
                  }`}
                >
                  {revenueChangePct >= 0
                    ? "+"
                    : ""}
                  {revenueChangePct}%
                </div>
              </div>

              <svg
                width="100%"
                height="68"
                viewBox="0 0 220 68"
                aria-hidden="true"
              >
                <polyline
                  points={trendPolyline}
                  fill="none"
                  stroke="#2451C4"
                  strokeWidth="2"
                />

                <polyline
                  points={trendArea}
                  fill="#E7EDFA"
                  stroke="none"
                />

                {trendPoints.map(
                  (point, index) => (
                    <circle
                      key={index}
                      cx={point.x}
                      cy={point.y}
                      r="2.5"
                      fill="#2451C4"
                    />
                  )
                )}
              </svg>
            </Card>
          )}
        </div>

        {/* ----------------------------------------------------------------- */}
        {/* PROJECTS + NOTIFICATIONS */}
        {/* ----------------------------------------------------------------- */}

        <div className="grid grid-cols-1 lg:grid-cols-[1.5fr_1fr] gap-3 mb-3.5">
          {/* Projects */}

          <Card className="p-3.5">
            <div className="flex justify-between items-center mb-3">
              <div className="font-medium text-ink text-[12.5px]">
                {hasFirmWideView
                  ? "All projects"
                  : "My projects"}
              </div>

              <Link
                href="/projects"
                className="text-blueprint text-[11px] font-mono"
              >
                Manage →
              </Link>
            </div>

            {projects.length === 0 ? (
              <div className="py-8 text-center">
                <p className="text-muted text-[12px]">
                  No projects available.
                </p>

                {hasFirmWideView && (
                  <Link
                    href="/projects"
                    className="inline-block mt-2 text-blueprint text-[11px]"
                  >
                    Create your first project →
                  </Link>
                )}
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full border-collapse text-[11.5px]">
                  <thead>
                    <tr className="text-muted text-left">
                      <th className="font-medium pb-2">
                        Sheet
                      </th>

                      <th className="font-medium pb-2">
                        Project
                      </th>

                      <th className="font-medium pb-2">
                        Architect
                      </th>

                      <th className="font-medium pb-2 text-right">
                        Progress
                      </th>

                      <th className="font-medium pb-2">
                        Status
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    {projects.map(
                      (project) => {
                        const architect =
                          staff.find(
                            (member) =>
                              member.id ===
                              project.architectId
                          );

                        const progress = Math.min(
                          100,
                          Math.max(
                            0,
                            safeNumber(
                              project.progress
                            )
                          )
                        );

                        return (
                          <tr
                            key={project.id}
                            className="border-t border-line hover:bg-vellum/50"
                          >
                            <td className="py-2 font-mono text-muted text-[11px]">
                              {
                                project.sheetNo
                              }
                            </td>

                            <td className="py-2 text-ink font-medium">
                              <Link
                                href={`/projects/${project.id}`}
                                className="hover:text-blueprint"
                              >
                                {project.name}
                              </Link>
                            </td>

                            <td className="py-2 text-muted">
                              {architect ? (
                                architect.name
                              ) : (
                                <span className="text-brick">
                                  Unassigned
                                </span>
                              )}
                            </td>

                            <td className="py-2 font-mono text-right">
                              {progress}%
                            </td>

                            <td className="py-2">
                              <StatusPill
                                status={
                                  project.status
                                }
                              />
                            </td>
                          </tr>
                        );
                      }
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </Card>

          {/* Notifications */}

          <Card className="p-3.5">
            <div className="flex justify-between items-center mb-3">
              <div className="font-medium text-ink text-[12.5px]">
                Notifications
              </div>

              {unread.length > 0 && (
                <span className="text-[11px] text-muted">
                  {unread.length} unread
                </span>
              )}
            </div>

            <div className="flex flex-col gap-2">
              {notifications.length === 0 ? (
                <p className="text-muted text-[12px]">
                  No notifications.
                </p>
              ) : (
                notifications
                  .slice(0, 6)
                  .map((notification) => (
                    <div
                      key={notification.id}
                      className={`flex gap-2.5 p-2.5 rounded-md cursor-pointer transition-colors ${
                        notification.read
                          ? "bg-transparent"
                          : "bg-vellum"
                      }`}
                      onClick={() =>
                        markNotificationRead(
                          notification.id
                        )
                      }
                    >
                      {notification.type ===
                        "ERROR" && (
                        <AlertTriangle
                          size={14}
                          className="text-brick mt-0.5 shrink-0"
                        />
                      )}

                      {notification.type ===
                        "WARNING" && (
                        <AlertTriangle
                          size={14}
                          className="text-ochre mt-0.5 shrink-0"
                        />
                      )}

                      {notification.type ===
                        "SUCCESS" && (
                        <CheckCircle
                          size={14}
                          className="text-moss mt-0.5 shrink-0"
                        />
                      )}

                      {notification.type ===
                        "INFO" && (
                        <Bell
                          size={14}
                          className="text-blueprint mt-0.5 shrink-0"
                        />
                      )}

                      <div>
                        <p
                          className={`text-[11.5px] leading-snug ${
                            notification.read
                              ? "text-muted"
                              : "text-ink"
                          }`}
                        >
                          {
                            notification.message
                          }
                        </p>

                        {!notification.read && (
                          <span className="text-[10px] text-blueprint">
                            Click to mark read
                          </span>
                        )}
                      </div>
                    </div>
                  ))
              )}
            </div>
          </Card>
        </div>

        {/* ----------------------------------------------------------------- */}
        {/* TODAY'S LOGS + CLIENT COMMENTS */}
        {/* ----------------------------------------------------------------- */}

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
          {/* Today's logs */}

          <Card className="p-3.5">
            <div className="flex justify-between items-center mb-3">
              <div className="font-medium text-ink text-[12.5px]">
                Today&apos;s submitted logs
              </div>

              <Link
                href="/daily-logs"
                className="text-blueprint text-[11px] font-mono"
              >
                View all →
              </Link>
            </div>

            {todayLogs.length === 0 ? (
              <p className="text-muted text-[12px]">
                No logs submitted yet today.
              </p>
            ) : (
              todayLogs.map((log) => {
                const author = staff.find(
                  (member) =>
                    member.id ===
                    log.authorId
                );

                const project = projects.find(
                  (item) =>
                    item.id ===
                    log.projectId
                );

                return (
                  <div
                    key={log.id}
                    className="border-t border-line pt-2.5 mt-2.5 first:border-0 first:mt-0 first:pt-0"
                  >
                    <div className="flex items-center gap-2 mb-1">
                      <Avatar
                        avatarUrl={
                          author?.avatarUrl
                        }
                        initials={
                          author?.initials
                        }
                        name={author?.name}
                        size={20}
                        fontSize={9}
                      />

                      <span className="text-ink text-[12px] font-medium">
                        {author?.name ??
                          "Unknown user"}
                      </span>

                      <span className="text-muted text-[11px]">
                        —{" "}
                        {project?.name ??
                          "Unknown project"}
                      </span>
                    </div>

                    <p className="text-[11.5px] text-muted leading-snug line-clamp-2">
                      {log.workCompleted}
                    </p>
                  </div>
                );
              })
            )}
          </Card>

          {/* Client comments */}

          <Card className="p-3.5">
            <div className="flex justify-between items-center mb-3">
              <div className="font-medium text-ink text-[12.5px]">
                Recent client comments
              </div>

              <Link
                href="/client-comms"
                className="text-blueprint text-[11px] font-mono"
              >
                View all →
              </Link>
            </div>

            {comments.length === 0 ? (
              <p className="text-muted text-[12px]">
                No client comments yet.
              </p>
            ) : (
              comments
                .slice(0, 3)
                .map((comment) => {
                  const project =
                    projects.find(
                      (item) =>
                        item.id ===
                        comment.projectId
                    );

                  return (
                    <div
                      key={comment.id}
                      className="border-t border-line pt-2.5 mt-2.5 first:border-0 first:mt-0 first:pt-0"
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-ink text-[12px] font-medium">
                          {comment.author}
                        </span>

                        <span
                          className={`text-[10px] px-1.5 py-0.5 rounded ${
                            comment.type ===
                            "CHANGE_REQUEST"
                              ? "bg-brick-bg text-brick"
                              : comment.type ===
                                  "APPROVAL"
                                ? "bg-moss-bg text-moss"
                                : "bg-blueprint-bg text-blueprint"
                          }`}
                        >
                          {commentTypeLabel(
                            comment.type
                          )}
                        </span>
                      </div>

                      <p className="text-[11px] text-muted">
                        {project?.name ??
                          "Unknown project"}
                      </p>

                      <p className="text-[11.5px] text-ink mt-0.5 leading-snug line-clamp-2">
                        {comment.content}
                      </p>
                    </div>
                  );
                })
            )}
          </Card>
        </div>
      </div>
    </AppShell>
  );
}
'@
Write-PatchFile "src/app/dashboard/page.tsx" $content

# --- [MOD] src/app/projects/[id]/takeover/page.tsx ---
$content = @'
"use client";
import { use, useMemo, useState } from "react";
import { notFound, useRouter } from "next/navigation";
import Link from "next/link";
import { useSession } from "next-auth/react";
import { AppShell } from "@/components/layout/app-shell";
import { Card } from "@/components/ui/card";
import { StatusPill } from "@/components/ui/status-pill";
import { Field, Select, Textarea } from "@/components/ui/form-field";
import {
  useStore,
  formatKsh,
  formatFileSize,
  commentTypeLabel,
  priorityLabel,
} from "@/store/app-store";
import {
  ArrowLeft,
  FileText,
  Upload,
  MessageSquare,
  Wallet,
  History,
  CheckCircle,
  AlertTriangle,
  Repeat,
  Download,
  Clock,
} from "lucide-react";

/**
 * Take Over Project — the platform's flagship "knowledge continuity" feature.
 *
 * When an architect is unavailable, whoever is picking up the project (or an
 * admin arranging the handover) needs one screen that answers "where does
 * this project actually stand right now?" without hunting through email,
 * personal folders, or the previous architect. Everything here is read from
 * the same live store the rest of the app uses — nothing is duplicated or
 * cached separately, so this can never drift from reality.
 *
 * Viewing the dossier is available to anyone with legitimate access to the
 * project (its current architect/supervisor, or an admin) — that's the
 * point of continuity. Actually confirming a handover (reassigning the
 * project) is admin-gated, same as the existing reassign flow, since it's
 * a formal ownership change with notification and audit-trail consequences.
 */
export default function TakeOverProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const router = useRouter();
  const { data: session } = useSession();
  const { projects, staff, clients, logs, comments, payments, documents, reassignProject } = useStore();

  const projectData = projects.find(p => p.id === id);
  if (!projectData) notFound();
  const project = projectData;

  const role = session?.user?.role;
  const isAdmin = role === "ADMIN";
  const isSeniorArchitect = role === "SENIOR_ARCHITECT";
  // Take-over is a project reassignment under the hood (reassignProject ->
  // /api/projects/[id]/reassign), and that route now permits Senior
  // Architects too (see rbac.ts canReassignProjects) -- this was left as
  // admin-only client-side, which just meant a senior architect saw no
  // confirm button even though the backend would have accepted the call.
  const hasFirmWideView = isAdmin || isSeniorArchitect;
  const canView =
    hasFirmWideView || project.architectId === session?.user?.id || project.supervisorId === session?.user?.id;
  const canConfirmHandover = hasFirmWideView;

  const client = clients.find(c => c.id === project.clientId);
  const currentArchitect = staff.find(s => s.id === project.architectId);
  const supervisor = staff.find(s => s.id === project.supervisorId);
  const otherArchitects = staff.filter(s => s.role === "ARCHITECT" && s.id !== project.architectId);

  const projectLogs = useMemo(
    () =>
      logs
        .filter(l => l.projectId === project.id)
        .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()),
    [logs, project.id]
  );
  const projectDocuments = useMemo(
    () =>
      documents
        .filter(d => d.projectId === project.id)
        .sort((a, b) => new Date(b.uploadedAt).getTime() - new Date(a.uploadedAt).getTime()),
    [documents, project.id]
  );
  const projectComments = useMemo(
    () =>
      comments
        .filter(c => c.projectId === project.id)
        .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()),
    [comments, project.id]
  );
  const projectPayments = useMemo(
    () => payments.filter(p => p.projectId === project.id).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()),
    [payments, project.id]
  );

  const latestLog = projectLogs[0];
  const outstandingComments = projectComments.filter(c => !c.resolvedAt);
  const pendingApprovals = projectComments.filter(c => c.type === "APPROVAL" && !c.resolvedAt);
  const outstandingBalance = project.invoiced - project.paid;

  // Has a log been submitted today? Compares by calendar day, not raw string,
  // so this stays correct regardless of timezone/serialization format.
  const todayKey = new Date().toISOString().split("T")[0];
  const hasLogToday = projectLogs.some(l => new Date(l.date).toISOString().split("T")[0] === todayKey);
  const daysSinceLastLog = latestLog
    ? Math.floor((new Date(todayKey).getTime() - new Date(new Date(latestLog.date).toISOString().split("T")[0]).getTime()) / 86400000)
    : null;

  // Unified per-project activity feed, same construction as the global
  // activity page but scoped to this one project.
  const timeline = useMemo(() => {
    type Ev = { id: string; label: string; timestamp: string; icon: React.ReactNode };
    const events: Ev[] = [
      ...projectLogs.map(l => ({
        id: `log-${l.id}`,
        label: `${l.author?.name ?? "Someone"} submitted a daily log — ${l.progress}% progress`,
        timestamp: l.submittedAt,
        icon: <History size={13} className="text-blueprint" />,
      })),
      ...projectDocuments.map(d => ({
        id: `doc-${d.id}`,
        label: `Document uploaded — ${d.name}`,
        timestamp: d.uploadedAt,
        icon: <Upload size={13} className="text-blueprint" />,
      })),
      ...projectComments.map(c => ({
        id: `comment-${c.id}`,
        label: `${commentTypeLabel(c.type)} logged by ${c.author}`,
        timestamp: c.createdAt,
        icon: <MessageSquare size={13} className="text-ochre" />,
      })),
      ...projectPayments.map(p => ({
        id: `payment-${p.id}`,
        label: `Payment recorded — ${formatKsh(p.amount)}`,
        timestamp: `${p.date}T12:00:00`,
        icon: <Wallet size={13} className="text-moss" />,
      })),
      ...(project.assignmentHistory ?? []).map(r => ({
        id: `assign-${r.id}`,
        label: `Reassigned to ${r.toArchitect?.name ?? "someone"}${r.reason ? ` — ${r.reason}` : ""}`,
        timestamp: `${r.date}T09:00:00`,
        icon: <Repeat size={13} className="text-brick" />,
      })),
    ];
    return events.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()).slice(0, 12);
  }, [projectLogs, projectDocuments, projectComments, projectPayments, project.assignmentHistory]);

  const [handoverTo, setHandoverTo] = useState("");
  const [handoverReason, setHandoverReason] = useState("");
  const [confirming, setConfirming] = useState(false);
  const [confirmed, setConfirmed] = useState(false);

  async function handleConfirmHandover(e: React.FormEvent) {
    e.preventDefault();
    if (!handoverTo) return;
    setConfirming(true);
    try {
      await reassignProject(project.id, handoverTo, handoverReason || "Project take-over — knowledge continuity handover");
      setConfirmed(true);
    } finally {
      setConfirming(false);
    }
  }

  if (!canView) {
    return (
      <AppShell>
        <Card className="p-8 text-center">
          <p className="text-ink font-medium mb-1">You don&apos;t have access to this project&apos;s handover dossier.</p>
          <p className="text-muted text-[12.5px]">Only the assigned architect, supervisor, or an admin can view it.</p>
        </Card>
      </AppShell>
    );
  }

  return (
    <AppShell>
      <div>
        <Link href={`/projects/${project.id}`} className="inline-flex items-center gap-1.5 text-muted hover:text-ink text-[12px] mb-3">
          <ArrowLeft size={14} />Back to project
        </Link>

        {/* Header */}
        <div className="flex items-start justify-between mb-5 gap-4 flex-wrap">
          <div>
            <div className="font-mono text-[11.5px] text-muted">{project.sheetNo} · {project.location}</div>
            <h1 className="font-display font-bold text-[21px] text-ink mt-0.5">Take over: {project.name}</h1>
            <p className="text-muted text-[12.5px] mt-1">
              Everything the next architect needs to pick this up with nothing lost — {client?.name}, {priorityLabel(project.priority)} priority.
            </p>
          </div>
          <StatusPill status={project.status} className="px-2.5 py-1" />
        </div>

        {/* At-a-glance risk banner */}
        {(!hasLogToday && (daysSinceLastLog === null || daysSinceLastLog > 0)) && (
          <div className="flex items-center gap-2.5 bg-ochre-bg text-ochre rounded-md px-4 py-2.5 mb-4 text-[12.5px]">
            <AlertTriangle size={15} className="shrink-0" />
            {latestLog
              ? `No daily log submitted today — the last one was ${daysSinceLastLog} day${daysSinceLastLog === 1 ? "" : "s"} ago.`
              : "No daily logs have ever been submitted for this project."}
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-[1.4fr_1fr] gap-3.5">
          {/* Left column — the dossier */}
          <div className="flex flex-col gap-3.5">
            {/* Ownership */}
            <Card className="p-4">
              <div className="font-medium text-ink text-[12.5px] mb-3">Current ownership</div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <div className="text-muted text-[11px]">Architect</div>
                  <div className="text-ink text-[13px] font-medium mt-0.5">{currentArchitect?.name ?? <span className="text-brick">Unassigned</span>}</div>
                </div>
                <div>
                  <div className="text-muted text-[11px]">Supervisor</div>
                  <div className="text-ink text-[13px] font-medium mt-0.5">{supervisor?.name ?? "—"}</div>
                </div>
              </div>
              <div className="mt-3 pt-3 border-t border-line">
                <div className="text-muted text-[11px] mb-1">Progress</div>
                <div className="w-full h-2 bg-vellum rounded-full overflow-hidden">
                  <div className="h-full bg-blueprint rounded-full" style={{ width: `${project.progress}%` }} />
                </div>
                <div className="text-[11px] text-muted mt-1">{project.progress}% complete · due {new Date(project.dueDate).toLocaleDateString("en-KE", { dateStyle: "medium" })}</div>
              </div>
            </Card>

            {/* Where things stand right now */}
            <Card className="p-4">
              <div className="font-medium text-ink text-[12.5px] mb-3">Where things stand</div>
              {latestLog ? (
                <div className="flex flex-col gap-3 text-[12.5px]">
                  <div>
                    <div className="text-muted text-[11px] mb-1">Last submitted by {latestLog.author?.name} — {new Date(latestLog.date).toLocaleDateString("en-KE", { dateStyle: "medium" })}</div>
                    <div className="text-ink leading-relaxed">{latestLog.workCompleted}</div>
                  </div>
                  {latestLog.pendingWork && (
                    <div>
                      <div className="text-muted text-[11px] mb-1">Pending work</div>
                      <div className="text-ink leading-relaxed">{latestLog.pendingWork}</div>
                    </div>
                  )}
                  {latestLog.nextActions && (
                    <div>
                      <div className="text-muted text-[11px] mb-1">Next actions</div>
                      <div className="text-ink leading-relaxed">{latestLog.nextActions}</div>
                    </div>
                  )}
                  {latestLog.challenges && (
                    <div>
                      <div className="text-muted text-[11px] mb-1">Open challenges</div>
                      <div className="text-brick leading-relaxed">{latestLog.challenges}</div>
                    </div>
                  )}
                </div>
              ) : (
                <p className="text-muted text-[12.5px]">No daily logs recorded yet for this project.</p>
              )}
            </Card>

            {/* Recent daily logs */}
            <Card className="p-4">
              <div className="flex items-center justify-between mb-3">
                <div className="font-medium text-ink text-[12.5px]">Daily log history</div>
                <span className="text-muted text-[11px]">{projectLogs.length} total</span>
              </div>
              {projectLogs.length === 0 ? (
                <p className="text-muted text-[12.5px]">No logs yet.</p>
              ) : (
                <div className="flex flex-col gap-2.5 max-h-72 overflow-y-auto">
                  {projectLogs.slice(0, 8).map(log => (
                    <div key={log.id} className="border-t border-line pt-2.5 first:border-0 first:pt-0">
                      <div className="flex items-center gap-2 text-[11px] text-muted mb-0.5">
                        <span className="font-medium text-ink">{log.author?.name}</span>
                        <span>· {new Date(log.date).toLocaleDateString("en-KE", { dateStyle: "medium" })}</span>
                        <span className="ml-auto font-mono">{log.progress}%</span>
                      </div>
                      <p className="text-[12px] text-ink leading-snug line-clamp-2">{log.workCompleted}</p>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            {/* Documents */}
            <Card className="p-4">
              <div className="flex items-center justify-between mb-3">
                <div className="font-medium text-ink text-[12.5px]">Latest drawings & documents</div>
                <span className="text-muted text-[11px]">{projectDocuments.length} total</span>
              </div>
              {projectDocuments.length === 0 ? (
                <p className="text-muted text-[12.5px]">No documents uploaded yet.</p>
              ) : (
                <div className="flex flex-col gap-2">
                  {projectDocuments.slice(0, 6).map(doc => (
                    <div key={doc.id} className="flex items-center justify-between gap-2 py-1.5 border-t border-line first:border-0">
                      <div className="flex items-center gap-2 min-w-0">
                        <FileText size={14} className="text-muted shrink-0" />
                        <div className="min-w-0">
                          <div className="text-ink text-[12px] font-medium truncate">{doc.name}</div>
                          <div className="text-muted text-[10.5px] font-mono">v{doc.version} · {formatFileSize(doc.fileSize)} · {new Date(doc.uploadedAt).toLocaleDateString("en-KE")}</div>
                        </div>
                      </div>
                      <a href={doc.fileUrl} download={doc.name} className="text-blueprint shrink-0" title="Download">
                        <Download size={14} />
                      </a>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            {/* Client communications */}
            <Card className="p-4">
              <div className="flex items-center justify-between mb-3">
                <div className="font-medium text-ink text-[12.5px]">Client communications</div>
                <span className="text-muted text-[11px]">{outstandingComments.length} unresolved</span>
              </div>
              {projectComments.length === 0 ? (
                <p className="text-muted text-[12.5px]">No client communications recorded.</p>
              ) : (
                <div className="flex flex-col gap-2.5 max-h-64 overflow-y-auto">
                  {projectComments.slice(0, 8).map(c => (
                    <div key={c.id} className={`border-t border-line pt-2.5 first:border-0 first:pt-0 ${c.resolvedAt ? "opacity-60" : ""}`}>
                      <div className="flex items-center gap-2 mb-1">
                        <span className="text-ink text-[12px] font-medium">{c.author}</span>
                        <span className={`text-[10px] px-1.5 py-0.5 rounded-[3px] font-medium ${c.type === "CHANGE_REQUEST" ? "bg-brick-bg text-brick" : c.type === "APPROVAL" ? "bg-moss-bg text-moss" : c.type === "QUERY" ? "bg-blueprint-bg text-blueprint" : "bg-ochre-bg text-ochre"}`}>
                          {commentTypeLabel(c.type)}
                        </span>
                        {!c.resolvedAt && <span className="text-[10px] text-brick ml-auto">Unresolved</span>}
                      </div>
                      <p className="text-[12px] text-ink leading-snug line-clamp-2">{c.content}</p>
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </div>

          {/* Right column — financials, approvals, timeline, action */}
          <div className="flex flex-col gap-3.5">
            {/* Financial status */}
            <Card className="p-4">
              <div className="font-medium text-ink text-[12.5px] mb-3">Financial status</div>
              <div className="flex flex-col gap-2 text-[12.5px]">
                <div className="flex justify-between"><span className="text-muted">Contract value</span><span className="font-mono text-ink">{formatKsh(project.budget)}</span></div>
                <div className="flex justify-between"><span className="text-muted">Invoiced</span><span className="font-mono text-ink">{formatKsh(project.invoiced)}</span></div>
                <div className="flex justify-between"><span className="text-muted">Paid</span><span className="font-mono text-moss">{formatKsh(project.paid)}</span></div>
                <div className="flex justify-between pt-2 border-t border-line"><span className="text-ink font-medium">Outstanding</span><span className="font-mono text-brick font-medium">{formatKsh(outstandingBalance)}</span></div>
              </div>
              {projectPayments.length > 0 && (
                <div className="mt-3 pt-3 border-t border-line text-[11px] text-muted">
                  Last payment {formatKsh(projectPayments[0].amount)} on {new Date(projectPayments[0].date).toLocaleDateString("en-KE", { dateStyle: "medium" })}
                </div>
              )}
            </Card>

            {/* Pending approvals */}
            <Card className="p-4">
              <div className="font-medium text-ink text-[12.5px] mb-3">Pending approvals</div>
              {pendingApprovals.length === 0 ? (
                <p className="text-muted text-[12px] flex items-center gap-1.5"><CheckCircle size={13} className="text-moss" />Nothing awaiting approval.</p>
              ) : (
                <div className="flex flex-col gap-2">
                  {pendingApprovals.map(c => (
                    <div key={c.id} className="text-[12px] text-ink bg-moss-bg/40 rounded-md p-2">
                      {c.content}
                    </div>
                  ))}
                </div>
              )}
            </Card>

            {/* Activity timeline (project-scoped) */}
            <Card className="p-4">
              <div className="font-medium text-ink text-[12.5px] mb-3">Recent activity</div>
              {timeline.length === 0 ? (
                <p className="text-muted text-[12px]">No activity recorded yet.</p>
              ) : (
                <div className="flex flex-col gap-2.5 max-h-80 overflow-y-auto">
                  {timeline.map(ev => (
                    <div key={ev.id} className="flex items-start gap-2">
                      <span className="mt-0.5 shrink-0">{ev.icon}</span>
                      <div>
                        <p className="text-[11.5px] text-ink leading-snug">{ev.label}</p>
                        <p className="text-[10px] text-muted font-mono flex items-center gap-1 mt-0.5"><Clock size={10} />{new Date(ev.timestamp).toLocaleString("en-KE", { dateStyle: "medium", timeStyle: "short" })}</p>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>

            {/* Confirm handover */}
            {canConfirmHandover && (
              <Card className="p-4">
                <div className="font-medium text-ink text-[12.5px] mb-1">Confirm handover</div>
                <p className="text-muted text-[11.5px] mb-3">The new architect gets instant access to everything above — nothing is re-entered or lost.</p>
                {confirmed ? (
                  <div className="flex items-center gap-2 text-moss text-[12.5px] bg-moss-bg rounded-md p-3">
                    <CheckCircle size={16} />
                    Handover complete. The project is now assigned and the new architect has been notified.
                  </div>
                ) : (
                  <form onSubmit={handleConfirmHandover} className="flex flex-col gap-3">
                    <Field label="Hand over to" required>
                      <Select value={handoverTo} onChange={e => setHandoverTo(e.target.value)} required>
                        <option value="">Select architect</option>
                        {otherArchitects.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}
                      </Select>
                    </Field>
                    <Field label="Handover notes">
                      <Textarea rows={2} value={handoverReason} onChange={e => setHandoverReason(e.target.value)} placeholder="Anything the incoming architect should know that isn't already captured above…" />
                    </Field>
                    <button
                      type="submit"
                      disabled={!handoverTo || confirming}
                      className="flex items-center justify-center gap-1.5 bg-brick text-white rounded-md px-3 py-2 text-[12.5px] font-medium hover:bg-brick/90 disabled:opacity-50"
                    >
                      <Repeat size={14} />{confirming ? "Confirming…" : "Confirm take over"}
                    </button>
                  </form>
                )}
              </Card>
            )}
          </div>
        </div>
      </div>
    </AppShell>
  );
}

'@
Write-PatchFile "src/app/projects/[id]/takeover/page.tsx" $content

Write-Host ""
Write-Host "Patch 7 applied. Run:" -ForegroundColor Green
Write-Host "  npm run build"
