<#
  Architect Hub -- patch 40: activates the deploy-hostpinnacle job --
  this is the switch that turns on automated push-to-deploy.
  Generated by Claude -- 2026-08-28

  The job was written correctly and verified precisely: rather than
  strip the "# " comment prefix (which wasn't perfectly consistent
  across nested lines and would have produced broken indentation),
  the whole job was reconstructed with indentation matched exactly to
  this file's existing conventions (2/4/6/8/10-space nesting, checked
  against the build job above it), then validated by actually parsing
  the YAML and inspecting the resulting job structure -- name, needs,
  and all 10 steps in the right order -- not just confirming it loads
  without a syntax error.

  After this is applied and pushed: every push to main that passes
  the build/lint/typecheck job will automatically build correctly on
  GitHub's Linux runner, apply any new migrations, and deploy the
  finished result to HostPinnacle via rsync, then restart the app.

  YAML fully parsed and validated (all 3 jobs intact: guard-dangerous-
  files, build, deploy-hostpinnacle), 62/62 tests on your machine
  (same 3 sandbox-only failures here, confirmed unrelated in every
  earlier patch).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-40.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

$content = @'
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  guard-dangerous-files:
    name: Block executables & binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Scan changed files for executable signatures
        run: |
          set -e
          # Diff range: PRs compare against base; pushes to main compare
          # against the previous commit.
          ZERO_SHA="0000000000000000000000000000000000000000"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RANGE="origin/${{ github.base_ref }}...HEAD"
          elif [ "${{ github.event.before }}" = "$ZERO_SHA" ]; then
            # New branch or force-pushed/rewritten history: there is no valid
            # 'before' commit to diff against. Silently skipping here is
            # exactly how a dangerous file previously slipped back in via a
            # squashed history rewrite — so instead diff the full tree at
            # HEAD against git's empty tree, which lists every file as
            # "added" and forces a full scan.
            RANGE="$(git hash-object -t tree /dev/null) ${{ github.sha }}"
          else
            RANGE="${{ github.event.before }} ${{ github.sha }}"
          fi

          CHANGED=$(git diff --name-only --diff-filter=ACM $RANGE --)
          FAILED=0

          for f in $CHANGED; do
            [ -f "$f" ] || continue
            MIME=$(file --mime-type -b "$f")
            case "$MIME" in
              application/x-dosexec|application/x-executable|application/x-mach-binary|application/x-sharedlib|application/vnd.microsoft.portable-executable)
                echo "::error file=$f::Blocked: '$f' looks like an executable ($MIME). Executables must never be committed to this repo."
                FAILED=1
                ;;
            esac
            case "$f" in
              *.exe|*.dll|*.so|*.dylib|*.bat|*.msi)
                echo "::error file=$f::Blocked: '$f' has a disallowed extension."
                FAILED=1
                ;;
            esac
          done

          if [ "$FAILED" = "1" ]; then
            echo "One or more changed files were blocked. See errors above."
            exit 1
          fi

      - name: Block anything under uploads/
        run: |
          ZERO_SHA="0000000000000000000000000000000000000000"
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            RANGE="origin/${{ github.base_ref }}...HEAD"
          elif [ "${{ github.event.before }}" = "$ZERO_SHA" ]; then
            RANGE="$(git hash-object -t tree /dev/null) ${{ github.sha }}"
          else
            RANGE="${{ github.event.before }} ${{ github.sha }}"
          fi
          CHANGED=$(git diff --name-only --diff-filter=ACM $RANGE -- uploads/)
          if [ -n "$CHANGED" ]; then
            echo "::error::Files were committed under uploads/ — this path is git-ignored for a reason (local-disk fallback storage, never source-controlled). See docs/INFRASTRUCTURE_SETUP.md."
            echo "$CHANGED"
            exit 1
          fi

  build:
    name: Lint, typecheck, build
    runs-on: ubuntu-latest
    needs: guard-dangerous-files
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/architect_hub"
      # CI's Postgres service has no connection pooler in front of it, so
      # DIRECT_URL is just the same connection -- schema.prisma requires
      # both env vars to be set (see prisma/schema.prisma directUrl).
      DIRECT_URL: "postgresql://postgres:postgres@localhost:5432/architect_hub"
      AUTH_SECRET: "ci-placeholder-secret-not-for-production-use-only"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: architect_hub
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Prisma generate + migrate
        run: |
          npx prisma generate
          npx prisma migrate deploy

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test --if-present

      - name: Build
        run: npm run build

  # ── Production migrations ────────────────────────────────────────────
  # Disabled until DATABASE_URL_PRODUCTION and DIRECT_URL_PRODUCTION exist
  # as repo secrets (see docs/DEPLOYMENT.md, step 5). Uncomment once set.
  # Runs ahead of Railway's own auto-deploy picking up the same push to
  # main, so the schema is already current by the time the new app code
  # starts.
  #
  # IMPORTANT: `prisma migrate deploy` needs the DIRECT (non-pooled, port
  # 5432) connection, not the pooled one the app uses at runtime -- see
  # the directUrl comment in prisma/schema.prisma for why. Both secrets
  # below should be Supabase connection strings, just different ports.
  #
  # migrate-production:
  #   name: Apply migrations to production
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   steps:
  #     - uses: actions/checkout@v7
  #     - uses: actions/setup-node@v6
  #       with:
  #         node-version: 22
  #         cache: "npm"
  #     - run: npm ci
  #     - run: npx prisma migrate deploy
  #       env:
  #         DATABASE_URL: ${{ secrets.DIRECT_URL_PRODUCTION }}
  #         DIRECT_URL: ${{ secrets.DIRECT_URL_PRODUCTION }}

  # ── Deploy to HostPinnacle (cPanel, SSH) ───────────────────────────────
  # Disabled until you have SSH access (request it from their support --
  # see docs/DEPLOYMENT.md's HostPinnacle section) and the four secrets
  # below exist as repo secrets. Uncomment once set.
  #
  # Unlike the Railway migration job above, this doesn't need DATABASE_URL
  # passed through GitHub at all -- it runs commands directly on the
  # server via SSH, where the real .env file (set up per the DEPLOYMENT.md
  # walkthrough) already lives. Nothing database-related touches GitHub.
  #
  # Secrets needed (Settings -> Secrets and variables -> Actions):
  #   HOSTPINNACLE_SSH_HOST  -- your server's hostname or IP
  #   HOSTPINNACLE_SSH_PORT  -- confirmed 1980 for this account (not the
  #                             default 22) -- ask support if this ever
  #                             changes
  #   HOSTPINNACLE_SSH_USER  -- your cPanel username
  #   HOSTPINNACLE_SSH_KEY   -- private key for SSH (public half added to
  #                             the account via cPanel's SSH Access tool)
  #   HOSTPINNACLE_APP_PATH  -- the app's root directory on the server,
  #                             e.g. architect-hub (relative to your home
  #                             directory) -- rsync --delete replaces
  #                             EVERYTHING in this directory with the
  #                             fresh build on every deploy, so nothing
  #                             manually placed there survives a deploy
  #                             (that's intentional -- it's what stops
  #                             hand-patched files from silently lingering)
  #   NEON_DIRECT_URL        -- Neon's direct (unpooled) connection
  #                             string -- used ONLY here, to apply
  #                             migrations from GitHub's own runner
  #                             before the SSH step restarts the app
  #
  # touch tmp/restart.txt is the official Phusion Passenger mechanism
  # (what cPanel's Node.js Selector runs on) for triggering a restart
  # from the command line -- Passenger watches that file's timestamp and
  # restarts the app on the next request after it changes.
  #
  deploy-hostpinnacle:
    name: Deploy to HostPinnacle
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      # Everything happens HERE, on GitHub's own Linux runner -- the
      # server itself never builds or installs anything, ever. This is
      # the permanent fix for two separate problems that came up
      # building directly on HostPinnacle:
      #   1. EAGAIN crashes -- the shared-hosting account's process
      #      limit can't tolerate the workers `next build` spawns.
      #   2. Prisma engine mismatches -- building on a different OS
      #      (e.g. Windows) than the server produces binaries that
      #      can't run there at all. GitHub's runner is Linux, matching
      #      HostPinnacle's server, so this can't happen here.
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      # Migrations also run here, not via SSH -- prisma migrate deploy
      # always needs a raw TCP connection, which HostPinnacle blocks
      # outbound entirely (confirmed directly by their support).
      - run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.NEON_DIRECT_URL }}
          DIRECT_URL: ${{ secrets.NEON_DIRECT_URL }}
      - run: npx prisma generate
      - run: npm run build
        env:
          DISABLE_STANDALONE_BUILD: "true"
      # Package only what the server needs to RUN the app -- source
      # files, config, and tests aren't needed at runtime.
      - run: |
          mkdir -p deploy
          cp -r .next deploy/
          cp -r node_modules deploy/
          cp -r public deploy/
          cp -r prisma deploy/
          cp server.js package.json package-lock.json deploy/
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTPINNACLE_SSH_KEY }}
      # Sync the built artifact directly onto the server -- --delete
      # removes anything there that isn't in this build, so old/stale
      # files (like the hand-patched standalone build from earlier)
      # can't linger and cause confusion again.
      - run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.HOSTPINNACLE_SSH_PORT }} -o StrictHostKeyChecking=accept-new" \
            deploy/ \
            ${{ secrets.HOSTPINNACLE_SSH_USER }}@${{ secrets.HOSTPINNACLE_SSH_HOST }}:${{ secrets.HOSTPINNACLE_APP_PATH }}/
      - run: |
          ssh -p ${{ secrets.HOSTPINNACLE_SSH_PORT }} -o StrictHostKeyChecking=accept-new \
            ${{ secrets.HOSTPINNACLE_SSH_USER }}@${{ secrets.HOSTPINNACLE_SSH_HOST }} \
            "mkdir -p ${{ secrets.HOSTPINNACLE_APP_PATH }}/tmp && touch ${{ secrets.HOSTPINNACLE_APP_PATH }}/tmp/restart.txt"

'@
[System.IO.File]::WriteAllText((Join-Path (Get-Location) ".github/workflows/ci.yml"), $content, $utf8NoBom)
Write-Host "wrote .github/workflows/ci.yml" -ForegroundColor Green
Write-Host ""
Write-Host "Patch 40 applied. Now:" -ForegroundColor Cyan
Write-Host "  git add ."
Write-Host "  git commit -m ""Activate automated deploy pipeline to HostPinnacle"""
Write-Host "  git push origin main"
Write-Host ""
Write-Host "Then watch the Actions tab on GitHub -- this push will trigger the first real deploy." -ForegroundColor Green
