<#
  Architect Hub -- patch 14 (FINAL). Completion-rate cleanup, CSP fix,
  and progress test coverage.
  Generated by Claude -- 2026-08-22

  1. PROJECT COMPLETION RATE -- how it actually works (see the long
     explanation in the chat reply, this is just the code summary):
     task-weighted percent complete, 0-100%, recalculated and persisted
     to Project.progress automatically whenever a task changes OR a
     daily log is submitted. Milestones are a defined-but-currently-dead
     extension (20% weight in the formula) -- no API route anywhere
     can ever create or update one, so in practice every project has
     zero milestones and progress is 100% task-driven today. That's
     fine and logical as-is; flagged, not "fixed", since ripping out an
     unused schema field days before launch is not worth the risk.
     tasks/[taskId]/route.ts previously had its own hand-copied version
     of the progress formula instead of calling the shared one in
     project-progress.ts -- real math was identical, but a genuine
     future drift risk. Now imports and calls the single shared
     implementation.

  2. project-progress.test.ts (NEW): first-ever test coverage for the
     completion-rate math. 15/18 pass in my sandbox; 3 fail here ONLY
     because project-progress.ts itself imports a Prisma runtime enum
     that this specific sandbox can't fully generate (unrelated network
     restriction, not a real bug) -- RUN `npm test` YOURSELF after this
     patch for the authoritative result; expect 62/62 passing on your
     machine, where Prisma generates cleanly.

  3. next.config.js -- two real production-only bugs, both invisible in
     dev because this CSP header is skipped entirely outside NODE_ENV=
     production, meaning NEITHER of these had ever actually been
     exercised before now:
       a) script-src had no 'unsafe-inline' and no nonce. Next.js
          injects inline hydration scripts into every page; without
          this, a browser would have blocked them and the app could
          have failed to render AT ALL on first production deploy.
          Confirmed via research this is Next's own documented guidance
          for apps not implementing per-request nonces -- and nonces
          are currently broken for this exact stack (Turbopack +
          output:"standalone") per an open upstream Next.js bug anyway.
       b) img-src allowlisted a hardcoded, guessed S3 bucket name/region
          that didn't match any actual configured value anywhere else
          in the app -- would have silently broken every document
          thumbnail and avatar in production if it didn't match your
          real bucket. Now derived from the same AWS_S3_BUCKET/
          AWS_REGION env vars src/lib/s3.ts actually uses, so it always
          matches whatever you actually configure at deploy time.
     Verified both: CSP builds correctly with real env vars set, and
     falls back cleanly (no broken syntax) when S3 is unconfigured.

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-14.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 14 (FINAL)..." -ForegroundColor Cyan

# --- [MOD] src/app/api/projects/[id]/tasks/[taskId]/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canAccessProject } from "@/lib/rbac";
import { calculateProjectProgress } from "@/lib/project-progress";

type RouteContext = {
  params: Promise<{
    id: string;
    taskId: string;
  }>;
};

export async function GET(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, taskId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const task =
    await prisma.projectTask.findFirst({
      where: {
        id: taskId,
        projectId: id,
      },
      include: {
        phase: true,
        assignee: true,
        updates: {
          orderBy: {
            createdAt: "desc",
          },
        },
      },
    });

  if (!task) {
    return NextResponse.json(
      { error: "Task not found" },
      { status: 404 }
    );
  }

  return NextResponse.json(task);
}

export async function PATCH(
  req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, taskId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const existing =
    await prisma.projectTask.findFirst({
      where: {
        id: taskId,
        projectId: id,
      },
    });

  if (!existing) {
    return NextResponse.json(
      { error: "Task not found" },
      { status: 404 }
    );
  }

  const body = await req.json();

  let completion =
    typeof body.completion === "number"
      ? Math.min(
          Math.max(body.completion, 0),
          100
        )
      : existing.completion;

  let status =
    typeof body.status === "string"
      ? body.status
      : existing.status;

  if (completion === 100) {
    status = "COMPLETED";
  }

  if (
    status === "COMPLETED" ||
    status === "VERIFIED"
  ) {
    completion = 100;
  }

  const task =
    await prisma.projectTask.update({
      where: {
        id: taskId,
      },

      data: {
        ...(typeof body.title === "string" && {
          title: body.title.trim(),
        }),

        ...(typeof body.description === "string" && {
          description: body.description,
        }),

        ...(typeof body.phaseId === "string" && {
          phaseId: body.phaseId,
        }),

        ...(typeof body.weight === "number" && {
          weight: Math.max(body.weight, 0),
        }),

        completion,

        status,
      },
    });

  /**
   * Recalculate overall project progress
   * whenever a task changes.
   */
  const projectData =
    await prisma.project.findUnique({
      where: { id },
      include: {
        tasks: {
          select: {
            weight: true,
            completion: true,
            status: true,
          },
        },

        milestones: {
          select: {
            weight: true,
            status: true,
          },
        },
      },
    });

  if (projectData) {
    // Single source of truth for the formula -- see
    // src/lib/project-progress.ts. This used to be a hand-copied version
    // of the same math living here too, which risked silently drifting
    // out of sync with the real implementation if the formula ever
    // changed in one place and not the other.
    const calculatedProgress = calculateProjectProgress({
      tasks: projectData.tasks,
      milestones: projectData.milestones,
    });

    await prisma.project.update({
      where: { id },
      data: {
        progress: calculatedProgress,
      },
    });
  }

  return NextResponse.json(task);
}

export async function DELETE(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, taskId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const existing =
    await prisma.projectTask.findFirst({
      where: {
        id: taskId,
        projectId: id,
      },
    });

  if (!existing) {
    return NextResponse.json(
      { error: "Task not found" },
      { status: 404 }
    );
  }

  await prisma.projectTask.delete({
    where: {
      id: taskId,
    },
  });

  return NextResponse.json({
    success: true,
  });
}
'@
Write-PatchFile "src/app/api/projects/[id]/tasks/[taskId]/route.ts" $content

# --- [NEW] src/lib/project-progress.test.ts ---
$content = @'
import { describe, expect, it } from "vitest";
import {
  clampPercentage,
  calculateTaskProgress,
  calculateMilestoneProgress,
  calculateProjectProgress,
  calculateFinancialProgress,
} from "./project-progress";
import type { TaskStatus, MilestoneStatus } from "@prisma/client";

// Using the literal string values rather than importing the TaskStatus/
// MilestoneStatus runtime enum objects -- these are just string enums
// under the hood, so this is exactly equivalent, but doesn't depend on
// a fully generated Prisma client to run (this file's own logic has
// nothing to do with the database at all).
const IN_PROGRESS = "IN_PROGRESS" as TaskStatus;
const TASK_COMPLETED = "COMPLETED" as TaskStatus;
const MILESTONE_COMPLETED = "COMPLETED" as MilestoneStatus;
const APPROVED = "APPROVED" as MilestoneStatus;
const PENDING = "PENDING" as MilestoneStatus;

describe("clampPercentage", () => {
  it("leaves in-range values untouched", () => {
    expect(clampPercentage(42)).toBe(42);
  });
  it("clamps above 100 down to 100", () => {
    expect(clampPercentage(150)).toBe(100);
  });
  it("clamps below 0 up to 0", () => {
    expect(clampPercentage(-10)).toBe(0);
  });
});

describe("calculateTaskProgress", () => {
  it("returns 0 for no tasks", () => {
    expect(calculateTaskProgress([])).toBe(0);
  });

  it("weights each task's completion by its weight", () => {
    // Task A: 50% complete, weight 2. Task B: 100% complete, weight 1.
    // (50*2 + 100*1) / 3 = 66.67 -> rounds to 67.
    const result = calculateTaskProgress([
      { weight: 2, completion: 50, status: IN_PROGRESS },
      { weight: 1, completion: 100, status: TASK_COMPLETED },
    ]);
    expect(result).toBe(67);
  });

  it("treats equal weights as a plain average", () => {
    const result = calculateTaskProgress([
      { weight: 1, completion: 20, status: IN_PROGRESS },
      { weight: 1, completion: 80, status: IN_PROGRESS },
    ]);
    expect(result).toBe(50);
  });

  it("returns 0 rather than dividing by zero when every task has zero weight", () => {
    const result = calculateTaskProgress([
      { weight: 0, completion: 100, status: TASK_COMPLETED },
    ]);
    expect(result).toBe(0);
  });

  it("clamps an out-of-range completion value before weighting it", () => {
    const result = calculateTaskProgress([
      { weight: 1, completion: 150, status: TASK_COMPLETED },
    ]);
    expect(result).toBe(100);
  });
});

describe("calculateMilestoneProgress", () => {
  it("returns 0 for no milestones", () => {
    expect(calculateMilestoneProgress([])).toBe(0);
  });

  it("counts COMPLETED and APPROVED as done, everything else as not", () => {
    const result = calculateMilestoneProgress([
      { weight: 1, status: MILESTONE_COMPLETED },
      { weight: 1, status: APPROVED },
      { weight: 2, status: PENDING },
    ]);
    // (1 + 1) done out of (1+1+2) total weight = 50%
    expect(result).toBe(50);
  });

  it("returns 0 rather than dividing by zero when every milestone has zero weight", () => {
    const result = calculateMilestoneProgress([
      { weight: 0, status: MILESTONE_COMPLETED },
    ]);
    expect(result).toBe(0);
  });
});

describe("calculateProjectProgress", () => {
  it("returns 0 when there are neither tasks nor milestones", () => {
    expect(calculateProjectProgress({ tasks: [], milestones: [] })).toBe(0);
  });

  it("uses task progress directly when there are no milestones (the real-world case today -- nothing in the app currently creates milestones)", () => {
    const result = calculateProjectProgress({
      tasks: [{ weight: 1, completion: 75, status: IN_PROGRESS }],
      milestones: [],
    });
    expect(result).toBe(75);
  });

  it("uses milestone progress directly when there are no tasks", () => {
    const result = calculateProjectProgress({
      tasks: [],
      milestones: [{ weight: 1, status: MILESTONE_COMPLETED }],
    });
    expect(result).toBe(100);
  });

  it("blends 80% tasks / 20% milestones when both exist", () => {
    // Tasks 100% complete, milestones 0% complete.
    // 100*0.8 + 0*0.2 = 80
    const result = calculateProjectProgress({
      tasks: [{ weight: 1, completion: 100, status: TASK_COMPLETED }],
      milestones: [{ weight: 1, status: PENDING }],
    });
    expect(result).toBe(80);
  });
});

describe("calculateFinancialProgress", () => {
  it("computes invoiced/collected percentages against contract value", () => {
    const result = calculateFinancialProgress({
      contractValue: 1_000_000,
      invoiced: 400_000,
      paid: 250_000,
    });
    expect(result.invoicedPercentage).toBe(40);
    expect(result.collectedPercentage).toBe(25);
    expect(result.outstanding).toBe(750_000);
  });

  it("returns 0% for both when there is no contract value, instead of dividing by zero", () => {
    const result = calculateFinancialProgress({
      contractValue: 0,
      invoiced: 0,
      paid: 0,
    });
    expect(result.invoicedPercentage).toBe(0);
    expect(result.collectedPercentage).toBe(0);
  });

  it("never lets paid exceed contract value drive outstanding negative", () => {
    const result = calculateFinancialProgress({
      contractValue: 100,
      invoiced: 100,
      paid: 150, // shouldn't happen given the API's own guards, but the math itself should still hold
    });
    expect(result.outstanding).toBe(0);
  });
});

'@
Write-PatchFile "src/lib/project-progress.test.ts" $content

# --- [MOD] next.config.js ---
$content = @'
/** @type {import('next').NextConfig} */
const isProd = process.env.NODE_ENV === "production";

// Derived from the same env vars src/lib/s3.ts actually uses, so this
// always matches whatever bucket/region is really configured at deploy
// time -- a hardcoded guess here would silently break every document
// thumbnail and avatar in production the moment it didn't match the
// real bucket, and (like the CSP itself) nothing in dev would ever
// reveal that mismatch since this header is skipped in dev entirely.
const s3ImgSrc =
  process.env.AWS_S3_BUCKET && process.env.AWS_REGION
    ? `https://${process.env.AWS_S3_BUCKET}.s3.${process.env.AWS_REGION}.amazonaws.com`
    : ""; // S3 not configured -- falls back to local disk storage, nothing to allowlist

const nextConfig = {
  reactStrictMode: true,
  output: "standalone",
  experimental: { serverActions: { allowedOrigins: ["localhost:3000"] } },
  async headers() {
    if (!isProd) return []; // don't apply CSP/HSTS in dev — breaks HMR/Fast Refresh

    const csp = [
      "default-src 'self'",
      // 'unsafe-inline' is required here -- Next.js's App Router injects
      // inline hydration scripts (self.__next_f.push(...)) into every
      // page. Without this, a browser enforcing this CSP blocks those
      // scripts and the app fails to hydrate at all -- blank page,
      // nothing interactive. This CSP header only activates in
      // production (see isProd above), so this had never actually been
      // exercised until now; dev mode always skips it.
      //
      // The "correct" alternative is a per-request nonce generated in
      // middleware instead of 'unsafe-inline'. That's deliberately NOT
      // done here: as of this Next.js version, nonce-based CSP is
      // broken specifically for the Turbopack + output:"standalone"
      // combination this app uses -- Next's own injected scripts don't
      // receive the nonce at all, so the app breaks the same way either
      // way. 'unsafe-inline' is also Next.js's own documented
      // recommendation for apps not implementing per-request nonces.
      // Revisit once that upstream bug is fixed.
      "script-src 'self' 'unsafe-inline'",
      "style-src 'self' 'unsafe-inline'",
      "img-src 'self' data:" + (s3ImgSrc ? ` ${s3ImgSrc}` : ""),
      "font-src 'self' data:",
      "connect-src 'self'",
      "frame-ancestors 'none'",
      "base-uri 'self'",
      "form-action 'self'",
      "object-src 'none'",
    ].join("; ");

    return [
      {
        source: "/(.*)",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "Strict-Transport-Security", value: "max-age=63072000; includeSubDomains; preload" },
        ],
      },
    ];
  },
};
module.exports = nextConfig;
'@
Write-PatchFile "next.config.js" $content

Write-Host ""
Write-Host "Patch 14 applied. Run, in order:" -ForegroundColor Green
Write-Host "  npm test          # expect 62/62 passing"
Write-Host "  npm run build"
Write-Host ""
Write-Host "IMPORTANT: before your actual production deploy, test with a REAL production build locally at least once:" -ForegroundColor Yellow
Write-Host "  npm run build && npm run start"
Write-Host "Then open it in a browser and confirm the app actually loads and works -- this is the first time the production CSP header will be active, and dev mode could never have shown you if it was broken." -ForegroundColor Yellow
