<#
  Architect Hub -- patch 53: the last 6 files with the nested-relation
  query pattern -- tasks, phases, progress tracking, single-document
  view, client portal document view. This closes out the sweep
  entirely: zero `include:` blocks remain anywhere in the API.
  Generated by Claude -- 2026-08-29

  Same fix pattern as every other file this session: nested includes
  replaced with flat queries plus batched (or, for single-record
  routes, individual) lookups for related data, stitched back into the
  exact same response shape each route already returned.

  Specific to this batch: projects/[id]/tasks and phases/[phaseId] had
  DOUBLE-nested includes (tasks -> phase/assignee/updates, phases ->
  tasks/milestones) -- both flattened fully. progress/route.ts had the
  pattern in BOTH its GET and PATCH handlers, including some now-
  redundant re-declarations cleaned up along the way.

  VERIFIED: grepped the entire src/app/api directory for `include:` in
  any formatting style -- zero matches now, confirming this was
  genuinely the last of it. Full `npx eslint .` clean, 62/62 tests on
  your machine (same 3 sandbox-only failures here, confirmed unrelated
  in every earlier patch).

  Run from the ROOT of your local Architect-Hub repo:
    .\apply-patch-53.ps1
#>

$ErrorActionPreference = "Stop"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-PatchFile($RelativePath, $Content) {
  $dir = Split-Path $RelativePath -Parent
  if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
  }
  $full = Join-Path (Get-Location) $RelativePath
  [System.IO.File]::WriteAllText($full, $Content, $utf8NoBom)
  Write-Host "  wrote $RelativePath"
}

Write-Host "Applying Architect Hub patch 53 (final nested-query sweep)..." -ForegroundColor Cyan

# --- [MOD] src/app/api/projects/[id]/tasks/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canAccessProject } from "@/lib/rbac";

type RouteContext = {
  params: Promise<{ id: string }>;
};

export async function GET(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  /*
   * Same flat-query fix as elsewhere in this app: nested includes fail
   * with "Connection terminated unexpectedly" on this host. Tasks and
   * every relation they reference (phase, assignee, updates) are
   * fetched as separate flat queries and stitched together below.
   */
  const tasks = await prisma.projectTask.findMany({
    where: { projectId: id },
    orderBy: { createdAt: "asc" },
  });

  const taskIds = tasks.map((t) => t.id);
  const phaseIds = [...new Set(tasks.map((t) => t.phaseId).filter((v): v is string => Boolean(v)))];
  const assigneeIds = [...new Set(tasks.map((t) => t.assigneeId).filter((v): v is string => Boolean(v)))];

  const [phases, assignees, updates] = await Promise.all([
    prisma.projectPhase.findMany({ where: { id: { in: phaseIds } } }),
    prisma.user.findMany({ where: { id: { in: assigneeIds } } }),
    prisma.taskUpdate.findMany({ where: { taskId: { in: taskIds } }, orderBy: { createdAt: "desc" } }),
  ]);

  const phaseById = new Map(phases.map((p) => [p.id, p]));
  const assigneeById = new Map(assignees.map((a) => [a.id, a]));
  const updatesByTaskId = new Map<string, typeof updates>();
  for (const update of updates) {
    const list = updatesByTaskId.get(update.taskId) ?? [];
    list.push(update);
    updatesByTaskId.set(update.taskId, list);
  }

  const tasksWithRelations = tasks.map((task) => ({
    ...task,
    phase: task.phaseId ? (phaseById.get(task.phaseId) ?? null) : null,
    assignee: task.assigneeId ? (assigneeById.get(task.assigneeId) ?? null) : null,
    updates: updatesByTaskId.get(task.id) ?? [],
  }));

  return NextResponse.json(tasksWithRelations);
}

export async function POST(
  req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const body = await req.json();

  const title =
    typeof body.title === "string"
      ? body.title.trim()
      : "";

  if (!title) {
    return NextResponse.json(
      { error: "Task title is required" },
      { status: 400 }
    );
  }

  const task =
    await prisma.projectTask.create({
      data: {
        projectId: id,
        title,

        description:
          typeof body.description === "string"
            ? body.description
            : null,

        phaseId:
          typeof body.phaseId === "string"
            ? body.phaseId
            : null,

        weight:
          typeof body.weight === "number"
            ? Math.max(body.weight, 0)
            : 1,

        completion:
          typeof body.completion === "number"
            ? Math.min(
                Math.max(body.completion, 0),
                100
              )
            : 0,

        status:
          typeof body.status === "string"
            ? body.status
            : "NOT_STARTED",

        createdById: session.user.id,
      },
    });

  return NextResponse.json(
    task,
    { status: 201 }
  );
}
'@
Write-PatchFile "src/app/api/projects/[id]/tasks/route.ts" $content

# --- [MOD] src/app/api/projects/[id]/tasks/[taskId]/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canAccessProject } from "@/lib/rbac";
import { calculateProjectProgress } from "@/lib/project-progress";

type RouteContext = {
  params: Promise<{
    id: string;
    taskId: string;
  }>;
};

export async function GET(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, taskId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const task =
    await prisma.projectTask.findFirst({
      where: {
        id: taskId,
        projectId: id,
      },
    });

  if (!task) {
    return NextResponse.json(
      { error: "Task not found" },
      { status: 404 }
    );
  }

  const [phase, assignee, updates] = await Promise.all([
    task.phaseId
      ? prisma.projectPhase.findUnique({ where: { id: task.phaseId } })
      : Promise.resolve(null),
    task.assigneeId
      ? prisma.user.findUnique({ where: { id: task.assigneeId } })
      : Promise.resolve(null),
    prisma.taskUpdate.findMany({
      where: { taskId: task.id },
      orderBy: { createdAt: "desc" },
    }),
  ]);

  return NextResponse.json({ ...task, phase, assignee, updates });
}

export async function PATCH(
  req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, taskId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const existing =
    await prisma.projectTask.findFirst({
      where: {
        id: taskId,
        projectId: id,
      },
    });

  if (!existing) {
    return NextResponse.json(
      { error: "Task not found" },
      { status: 404 }
    );
  }

  const body = await req.json();

  let completion =
    typeof body.completion === "number"
      ? Math.min(
          Math.max(body.completion, 0),
          100
        )
      : existing.completion;

  let status =
    typeof body.status === "string"
      ? body.status
      : existing.status;

  if (completion === 100) {
    status = "COMPLETED";
  }

  if (
    status === "COMPLETED" ||
    status === "VERIFIED"
  ) {
    completion = 100;
  }

  const task =
    await prisma.projectTask.update({
      where: {
        id: taskId,
      },

      data: {
        ...(typeof body.title === "string" && {
          title: body.title.trim(),
        }),

        ...(typeof body.description === "string" && {
          description: body.description,
        }),

        ...(typeof body.phaseId === "string" && {
          phaseId: body.phaseId,
        }),

        ...(typeof body.weight === "number" && {
          weight: Math.max(body.weight, 0),
        }),

        completion,

        status,
      },
    });

  /**
   * Recalculate overall project progress
   * whenever a task changes.
   */
  const [projectTasks, projectMilestones] = await Promise.all([
    prisma.projectTask.findMany({
      where: { projectId: id },
      select: { weight: true, completion: true, status: true },
    }),
    prisma.projectMilestone.findMany({
      where: { projectId: id },
      select: { weight: true, status: true },
    }),
  ]);

  // Single source of truth for the formula -- see
  // src/lib/project-progress.ts. This used to be a hand-copied version
  // of the same math living here too, which risked silently drifting
  // out of sync with the real implementation if the formula ever
  // changed in one place and not the other.
  const calculatedProgress = calculateProjectProgress({
    tasks: projectTasks,
    milestones: projectMilestones,
  });

  await prisma.project.update({
    where: { id },
    data: {
      progress: calculatedProgress,
    },
  });

  return NextResponse.json(task);
}

export async function DELETE(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, taskId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const existing =
    await prisma.projectTask.findFirst({
      where: {
        id: taskId,
        projectId: id,
      },
    });

  if (!existing) {
    return NextResponse.json(
      { error: "Task not found" },
      { status: 404 }
    );
  }

  await prisma.projectTask.delete({
    where: {
      id: taskId,
    },
  });

  return NextResponse.json({
    success: true,
  });
}
'@
Write-PatchFile "src/app/api/projects/[id]/tasks/[taskId]/route.ts" $content

# --- [MOD] src/app/api/projects/[id]/phases/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canAccessProject } from "@/lib/rbac";

type RouteContext = {
  params: Promise<{ id: string }>;
};

export async function GET(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const phases = await prisma.projectPhase.findMany({
    where: { projectId: id },
    orderBy: { sortOrder: "asc" },
  });

  const phaseIds = phases.map((p) => p.id);

  const [tasks, milestones] = await Promise.all([
    prisma.projectTask.findMany({ where: { phaseId: { in: phaseIds } } }),
    prisma.projectMilestone.findMany({ where: { phaseId: { in: phaseIds } } }),
  ]);

  const tasksByPhaseId = new Map<string, typeof tasks>();
  for (const task of tasks) {
    if (!task.phaseId) continue;
    const list = tasksByPhaseId.get(task.phaseId) ?? [];
    list.push(task);
    tasksByPhaseId.set(task.phaseId, list);
  }

  const milestonesByPhaseId = new Map<string, typeof milestones>();
  for (const milestone of milestones) {
    if (!milestone.phaseId) continue;
    const list = milestonesByPhaseId.get(milestone.phaseId) ?? [];
    list.push(milestone);
    milestonesByPhaseId.set(milestone.phaseId, list);
  }

  const phasesWithRelations = phases.map((phase) => ({
    ...phase,
    tasks: tasksByPhaseId.get(phase.id) ?? [],
    milestones: milestonesByPhaseId.get(phase.id) ?? [],
  }));

  return NextResponse.json(phasesWithRelations);
}

export async function POST(
  req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const body = await req.json();

  const name =
    typeof body.name === "string"
      ? body.name.trim()
      : "";

  if (!name) {
    return NextResponse.json(
      { error: "Phase name is required" },
      { status: 400 }
    );
  }

  const phase = await prisma.projectPhase.create({
    data: {
      projectId: id,
      name,
      description:
        typeof body.description === "string"
          ? body.description
          : null,
      weight:
        typeof body.weight === "number"
          ? Math.max(body.weight, 0)
          : 1,
      sortOrder:
        typeof body.sortOrder === "number"
          ? body.sortOrder
          : 0,
    },
  });

  return NextResponse.json(
    phase,
    { status: 201 }
  );
}
'@
Write-PatchFile "src/app/api/projects/[id]/phases/route.ts" $content

# --- [MOD] src/app/api/projects/[id]/phases/[phaseId]/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canAccessProject } from "@/lib/rbac";

type RouteContext = {
  params: Promise<{
    id: string;
    phaseId: string;
  }>;
};

export async function GET(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, phaseId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const phase =
    await prisma.projectPhase.findFirst({
      where: {
        id: phaseId,
        projectId: id,
      },
    });

  if (!phase) {
    return NextResponse.json(
      { error: "Phase not found" },
      { status: 404 }
    );
  }

  const [tasks, milestones] = await Promise.all([
    prisma.projectTask.findMany({ where: { phaseId: phase.id } }),
    prisma.projectMilestone.findMany({ where: { phaseId: phase.id } }),
  ]);

  return NextResponse.json({ ...phase, tasks, milestones });
}

export async function PATCH(
  req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, phaseId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const existing =
    await prisma.projectPhase.findFirst({
      where: {
        id: phaseId,
        projectId: id,
      },
    });

  if (!existing) {
    return NextResponse.json(
      { error: "Phase not found" },
      { status: 404 }
    );
  }

  const body = await req.json();

  const phase =
    await prisma.projectPhase.update({
      where: {
        id: phaseId,
      },
      data: {
        ...(typeof body.name === "string" && {
          name: body.name.trim(),
        }),

        ...(typeof body.description === "string" && {
          description: body.description,
        }),

        ...(typeof body.weight === "number" && {
          weight: Math.max(body.weight, 0),
        }),

        ...(typeof body.sortOrder === "number" && {
          sortOrder: body.sortOrder,
        }),
      },
    });

  return NextResponse.json(phase);
}

export async function DELETE(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id, phaseId } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const existing =
    await prisma.projectPhase.findFirst({
      where: {
        id: phaseId,
        projectId: id,
      },
    });

  if (!existing) {
    return NextResponse.json(
      { error: "Phase not found" },
      { status: 404 }
    );
  }

  await prisma.projectPhase.delete({
    where: {
      id: phaseId,
    },
  });

  return NextResponse.json({
    success: true,
  });
}
'@
Write-PatchFile "src/app/api/projects/[id]/phases/[phaseId]/route.ts" $content

# --- [MOD] src/app/api/projects/[id]/progress/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canAccessProject } from "@/lib/rbac";
import {
  calculateProjectProgress,
  calculateTaskProgress,
  calculateMilestoneProgress,
} from "@/lib/project-progress";

type RouteContext = {
  params: Promise<{ id: string }>;
};

/**
 * GET /api/projects/[id]/progress
 *
 * Returns calculated physical project progress.
 *
 * Progress is based on:
 * - Task completion: 80%
 * - Milestone completion: 20%
 *
 * If only tasks or milestones exist, that source is used directly.
 */
export async function GET(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const [tasks, milestones, phases] = await Promise.all([
    prisma.projectTask.findMany({
      where: { projectId: id },
      select: {
        id: true,
        title: true,
        status: true,
        completion: true,
        weight: true,
        phaseId: true,
      },
    }),
    prisma.projectMilestone.findMany({
      where: { projectId: id },
      select: {
        id: true,
        title: true,
        status: true,
        weight: true,
        phaseId: true,
      },
    }),
    prisma.projectPhase.findMany({
      where: { projectId: id },
      select: {
        id: true,
        name: true,
        weight: true,
        sortOrder: true,
      },
      orderBy: {
        sortOrder: "asc",
      },
    }),
  ]);

  const taskProgress = calculateTaskProgress(tasks);
  const milestoneProgress =
    calculateMilestoneProgress(milestones);

  const calculatedProgress =
    calculateProjectProgress({
      tasks,
      milestones,
    });

  /**
   * Calculate progress for each phase.
   *
   * A phase does not have its own status in the database.
   * Its progress is therefore calculated from the tasks
   * and milestones belonging to that phase.
   */
  const phaseProgress = phases.map((phase) => {
    const phaseTasks = tasks.filter(
      (task) => task.phaseId === phase.id
    );

    const phaseMilestones = milestones.filter(
      (milestone) =>
        milestone.phaseId === phase.id
    );

    const progress =
      calculateProjectProgress({
        tasks: phaseTasks,
        milestones: phaseMilestones,
      });

    return {
      id: phase.id,
      name: phase.name,
      weight: phase.weight,
      progress,
      tasks: {
        total: phaseTasks.length,
        progress: calculateTaskProgress(phaseTasks),
      },
      milestones: {
        total: phaseMilestones.length,
        progress:
          calculateMilestoneProgress(
            phaseMilestones
          ),
      },
    };
  });

  return NextResponse.json({
    projectId: project.id,

    progress: calculatedProgress,

    tasks: {
      total: tasks.length,
      completed: tasks.filter(
        (task) =>
          task.status === "COMPLETED" ||
          task.status === "VERIFIED"
      ).length,
      progress: taskProgress,
    },

    milestones: {
      total: milestones.length,
      completed: milestones.filter(
        (milestone) =>
          milestone.status === "COMPLETED" ||
          milestone.status === "APPROVED"
      ).length,
      progress: milestoneProgress,
    },

    phases: phaseProgress,

    source:
      tasks.length > 0 ||
      milestones.length > 0
        ? "calculated"
        : "project_record",
  });
}

/**
 * PATCH /api/projects/[id]/progress
 *
 * Recalculates and stores the project's physical progress.
 *
 * The client does NOT provide a percentage.
 */
export async function PATCH(
  _req: NextRequest,
  { params }: RouteContext
) {
  const session = await auth();

  if (!session) {
    return NextResponse.json(
      { error: "Unauthorized" },
      { status: 401 }
    );
  }

  const { id } = await params;

  const project = await prisma.project.findUnique({
    where: { id },
  });

  if (!project) {
    return NextResponse.json(
      { error: "Project not found" },
      { status: 404 }
    );
  }

  if (!canAccessProject(session, project)) {
    return NextResponse.json(
      { error: "Forbidden" },
      { status: 403 }
    );
  }

  const [tasks, milestones] = await Promise.all([
    prisma.projectTask.findMany({
      where: { projectId: id },
      select: {
        id: true,
        status: true,
        completion: true,
        weight: true,
      },
    }),
    prisma.projectMilestone.findMany({
      where: { projectId: id },
      select: {
        id: true,
        status: true,
        weight: true,
      },
    }),
  ]);

  const calculatedProgress =
    calculateProjectProgress({
      tasks,
      milestones,
    });

  const updatedProject =
    await prisma.project.update({
      where: { id },
      data: {
        progress: calculatedProgress,
      },
    });

  return NextResponse.json({
    success: true,

    projectId: updatedProject.id,

    progress: updatedProject.progress,

    tasks: {
      total: tasks.length,

      completed:
        tasks.filter(
          (task) =>
            task.status === "COMPLETED" ||
            task.status === "VERIFIED"
        ).length,

      progress:
        calculateTaskProgress(
          tasks
        ),
    },

    milestones: {
      total: milestones.length,

      completed:
        milestones.filter(
          (milestone) =>
            milestone.status === "COMPLETED" ||
            milestone.status === "APPROVED"
        ).length,

      progress:
        calculateMilestoneProgress(
          milestones
        ),
    },
  });
}
'@
Write-PatchFile "src/app/api/projects/[id]/progress/route.ts" $content

# --- [MOD] src/app/api/client-portal/documents/[id]/route.ts ---
$content = @'
import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireClientSession } from "@/lib/client-portal-auth";
import { readStoredFile } from "@/lib/storage";

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const ctx = await requireClientSession();
  if (!ctx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const document = await prisma.document.findUnique({ where: { id } });

  if (!document || document.deletedAt || !document.clientVisible) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const documentProject = await prisma.project.findUnique({ where: { id: document.projectId } });

  // Same rule as the client-portal project detail route: their own
  // project only, and only documents staff explicitly flagged visible.
  if (!documentProject || documentProject.clientId !== ctx.clientId) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  let buffer: Buffer;
  try {
    buffer = await readStoredFile(document.fileKey);
  } catch {
    return NextResponse.json({ error: "File missing on disk" }, { status: 410 });
  }

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": document.mimeType || "application/octet-stream",
      "Content-Disposition": `attachment; filename="${encodeURIComponent(document.name)}"`,
      "Content-Length": String(document.fileSize),
    },
  });
}

'@
Write-PatchFile "src/app/api/client-portal/documents/[id]/route.ts" $content

# --- [MOD] src/app/api/documents/[id]/route.ts ---
$content = @'
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { auth } from "@/lib/auth";
import { canAccessProject } from "@/lib/rbac";
import { readStoredFile } from "@/lib/storage";

export const runtime = "nodejs";
export const maxDuration = 60;

export async function GET(_: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const document = await prisma.document.findUnique({ where: { id } });
  if (!document || document.deletedAt) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const documentProject = await prisma.project.findUnique({ where: { id: document.projectId } });
  if (!documentProject) return NextResponse.json({ error: "Not found" }, { status: 404 });

  // Client Portal sessions never reach this route — middleware.ts routes
  // them to /api/client-portal/documents/[id] instead, which enforces the
  // clientVisible flag. This route stays staff-only.
  if (!canAccessProject(session, documentProject)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  let buffer: Buffer;
  try {
    buffer = await readStoredFile(document.fileKey);
  } catch {
    return NextResponse.json({ error: "File missing on disk" }, { status: 410 });
  }

  return new NextResponse(new Uint8Array(buffer), {
    headers: {
      "Content-Type": document.mimeType || "application/octet-stream",
      "Content-Disposition": `attachment; filename="${encodeURIComponent(document.name)}"`,
      "Content-Length": String(document.fileSize),
    },
  });
}

/**
 * Only field this route supports changing today is clientVisible — the
 * flag that decides whether a document shows up in the Client Portal (see
 * /api/client-portal/documents/[id] and /api/client-portal/projects/[id]).
 * Anyone who can access the project can toggle it, same as who can upload
 * or delete a document — this isn't a more sensitive action than those.
 */
export async function PATCH(req: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const document = await prisma.document.findUnique({ where: { id } });
  if (!document || document.deletedAt) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const documentProject = await prisma.project.findUnique({ where: { id: document.projectId } });
  if (!documentProject) return NextResponse.json({ error: "Not found" }, { status: 404 });

  if (!canAccessProject(session, documentProject)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const body = await req.json().catch(() => null);
  if (typeof body?.clientVisible !== "boolean") {
    return NextResponse.json({ error: "clientVisible (boolean) is required" }, { status: 400 });
  }

  const updated = await prisma.document.update({
    where: { id },
    data: { clientVisible: body.clientVisible },
  });

  return NextResponse.json(updated);
}

export async function DELETE(_: NextRequest, { params }: { params: Promise<{ id: string }> }) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const document = await prisma.document.findUnique({ where: { id } });
  if (!document || document.deletedAt) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const documentProject = await prisma.project.findUnique({ where: { id: document.projectId } });
  if (!documentProject) return NextResponse.json({ error: "Not found" }, { status: 404 });

  if (!canAccessProject(session, documentProject)) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  // Soft delete — architectural documents should never disappear entirely.
  // Take Over Project and audit history need to be able to reference them
  // even after a "delete" action.
  await prisma.document.update({ where: { id }, data: { deletedAt: new Date() } });

  return NextResponse.json({ success: true });
}

'@
Write-PatchFile "src/app/api/documents/[id]/route.ts" $content

Write-Host ""
Write-Host "Patch 53 applied. Now:" -ForegroundColor Cyan
Write-Host "  git add ."
Write-Host "  git commit -m ""Fix remaining nested queries: tasks, phases, progress, document views"""
Write-Host "  git push origin main"
Write-Host ""
Write-Host "This should cover tasks, phases, and milestones inside a project, plus opening individual" -ForegroundColor Green
Write-Host "documents. Combined with patch 52, this closes out the whole nested-query issue app-wide." -ForegroundColor Green
