<#
  Architect Hub -- clears the stale/corrupted .next build cache.
  Not a code bug: .next/dev/types/routes.d.ts is auto-generated by
  Next.js by scanning your route folders, not something anyone wrote or
  patched. It's gitignored (pure disposable cache) and got stale after
  this session's many route additions/renames. Safe to delete anytime.
#>

$ErrorActionPreference = "Stop"

Write-Host "Removing stale .next build cache..." -ForegroundColor Cyan
Remove-Item -Recurse -Force ".next" -ErrorAction SilentlyContinue

Write-Host "Done. Now run:" -ForegroundColor Green
Write-Host "  npm run build"
